### ISSUE TITLE
Daemon should error properly on an invalid type.

### ISSUE THREAD

**Issue by hackrush01** [lbryio/lbry#1026]
## Issue

The daemon should error properly if invalid datatype is passed on as an argument. For e.g. I passed `nout` as a string here, whereas it shouuld be an integer. But the daemon returns "Claim not found", instead it should state that nout is expected as integer.

## Logs

```
2017-12-11 00:59:40,461 ERROR    lbrynet.daemon.auth.server:353: Failed to process claim_abandon: Abandon of None/092f8d4b61c7bd61880d1ddaef19bea7a15f67ea9920a4b48198e777de8e106e:0 failed: claim not found
  Traceback (most recent call last):
    File "site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    File "site-packages/lbrynet/core/Wallet.py", line 961, in abandon_claim
  Exception: Abandon of None/092f8d4b61c7bd61880d1ddaef19bea7a15f67ea9920a4b48198e777de8e106e:0 failed: claim not found
```

**Comment by lyoshenka** [comment]
proper solution: #1010

**Comment by alyssaoc** [comment]
@hackrush01 Is this still an issue?

**Comment by alyssaoc** [comment]
closing, reopen if this is still an issue
