### ISSUE TITLE
Useless error message on publish

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry#1029]
To reproduce, run `lbrynet-cli publish x 0.01`

**Comment by tzarebczan** [comment]
Same as https://github.com/lbryio/lbry/issues/901? It was fixed(apparently), but it's not in v18.

**Comment by lyoshenka** [comment]
i don't think that's the same thing. here's the error:

```
Traceback (most recent call last):
  File "/home/grin/.virtualenvs/lbry/bin/lbrynet-cli", line 11, in <module>
    load_entry_point('lbrynet', 'console_scripts', 'lbrynet-cli')()
  File "/home/grin/code/lbry/lbry/lbrynet/daemon/DaemonCLI.py", line 131, in main
    if 'data' in error_data['error'] and 'traceback' in error_data['error']['data']:
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by lyoshenka** [comment]
hmm... maybe it is the same?
