### ISSUE TITLE
This browser is running with an incompatible version of the LBRY protocol and your install must be repaired.

### ISSUE THREAD

**Issue by RedbHawk** [lbryio/lbry#1032]
First of all thank you for this great idea! It's really **awesome** ! 

### How I installed & run
1. Downloaded deb package from [here](https://lbry.io/)
2. `sudo apt-get install libgmp3-dev build-essential python2.7 python2.7-dev python-pip git python-virtualenv libssl-dev libffi-dev python-protobuf`
3. git clone https://github.com/lbryio/lbry.git
cd lbry

virtualenv lbry-venv
source lbry-venv/bin/activate

pip install -U -r requirements.txt
pip install --editable .

4. Installed deb package via : `dpkg -i LBRY_0.19.1_amd64.deb`
5. cd lbry-venv/ && source bin/activate && lbrynet-daemon
6. Run the app

## System Configuration

Platform: {"lbrynet_version": "0.19.0rc19-dirty", "platform": "Linux-4.13.0-kali1-amd64-x86_64-with-Kali-kali-rolling-kali-rolling", "os_system": "Linux", "python_version": "2.7.14+", "os_release": "4.13.0-kali1-amd64", "lbryum_version": "3.2.0rc7", "lbryschema_version": "0.0.15rc2", "processor": "", "build": "dev"}

 
{
  "id": null,
  "jsonrpc": "2.0",
  "result": {
    "build": "dev",
    "ip": "185.217.68.238",
    "lbrynet_version": "0.19.0rc19-dirty",
    "lbryschema_version": "0.0.15rc2",
    "lbryum_version": "3.2.0rc7",
    "os_release": "4.13.0-kali1-amd64",
    "os_system": "Linux",
    "platform": "Linux-4.13.0-kali1-amd64-x86_64-with-Kali-kali-rolling-kali-rolling",
    "processor": "",
    "python_version": "2.7.14+"
  }
}

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system: Kali Linux

## Anything Else
If you can, please add video instructions of installation LBRY on different OS to your [YT channel](https://www.youtube.com/channel/UCXAcp3dJuPqeUekOacsuyaQ/videos?disable_polymer=1) 

## Screenshots
![lbry_error](https://user-images.githubusercontent.com/34606814/34073482-38c7e4ea-e2b4-11e7-9277-cd9c2488127e.png)

**Comment by tzarebczan** [comment]
The v0.19 version of the daemon(lbry/lbrynet) is not supported in the lbry app yet. 

When you install the lbry app, it comes shipped with a compatible daemon, so no need to download/install  lbry separately.

**Comment by RedbHawk** [comment]
So to try reinstall or wait 0.19 version of app?

**Comment by tzarebczan** [comment]
Just install the latest app (0.19.1) from https://github.com/lbryio/lbry-app/releases or https://github.com/lbryio/lbry-app/blob/master/README.md

The app will start up the daemon, so make sure it's not running from your lbry install.

**Comment by RedbHawk** [comment]
2017-12-17 XX:XX:29,954 INFO     lbrynet.daemon.DaemonControl:70: Starting lbrynet-daemon from command line
2017-12-17 XX:XX:33,876 INFO     lbrynet.daemon.DaemonServer:66: Using non-authenticated API
2017-12-17 XX:XX:33,882 INFO     lbrynet.daemon.Daemon:243: Starting lbrynet-daemon
2017-12-17 XX:XX:35,268 INFO     lbrynet.daemon.ExchangeRateManager:210: Starting exchange rate manager
2017-12-17 XX:XX:37,324 INFO     lbrynet.daemon.Daemon:269: Platform: {"lbrynet_version": "0.18.0", "platform": "Linux-4.13.0-kali1-amd64-x86_64-with-Kali-kali-rolling-kali-rolling", "os_system": "Linux", "python_version": "2.7.12", "os_release": "4.13.0-kali1-amd64", "lbryum_version": "3.1.11", "ip": "185.217.68.238", "lbryschema_version": "0.0.14", "processor": "", "build": "release"}
2017-12-17 XX:XX:37,336 INFO     lbrynet.daemon.Daemon:479: Loading databases
2017-12-17 XX:XX:37,339 ERROR    lbrynet.daemon.DaemonControl:100: Failed to start lbrynet-daemon
Traceback (most recent call last):
  File "site-packages/lbrynet/daemon/DaemonControl.py", line 97, in start_server_and_listen
  File "site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
  File "site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
  File "site-packages/lbrynet/daemon/DaemonServer.py", line 53, in start
  File "site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
  File "site-packages/lbrynet/daemon/Daemon.py", line 251, in setup
  File "site-packages/lbrynet/daemon/Daemon.py", line 501, in _check_db_migration
Exception: This version of lbrynet is not compatible with the database
Your database is revision 5, expected 4
2017-12-17 XX:XX:37,340 INFO     lbrynet.daemon.DaemonServer:57: Stopping the reactor
2017-12-17 XX:XX:37,340 INFO     lbrynet.daemon.Daemon:405: Closing lbrynet session
2017-12-17 XX:XX:37,340 INFO     lbrynet.daemon.Daemon:406: Status at time of shutdown: loading_db

**Comment by tzarebczan** [comment]
Ah, it's because of a database upgrade from the other version you can. Delete the entire lbrynet folder and try again https://lbry.io/faq/lbry-directories
