### ISSUE TITLE
Improve behavior when unable to connect to lbryum-server

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry#1084]
When unable to connect to `lbryum-server`, the daemon will currently fail with a trace similar to the following:

```
2018-01-26 12:09:07,804 INFO     lbrynet.core.Wallet:451: Starting wallet.
2018-01-26 12:09:11,848 INFO     lbrynet.core.Wallet:1170: Loading the wallet
2018-01-26 12:11:22,323 ERROR    lbryum.interface:70: Failed to connect to (2, 1, 6, '', ('54.243.19.249', 50001))
Traceback (most recent call last):
  File "site-packages/lbryum/interface.py", line 65, in get_simple_socket
  File "socket.py", line 228, in meth
error: [Errno 110] Connection timed out
2018-01-26 12:11:22,472 ERROR    lbrynet.daemon.DaemonControl:100: Failed to start lbrynet-daemon
Traceback (most recent call last):
  File "site-packages/lbrynet/daemon/DaemonControl.py", line 97, in start_server_and_listen
FirstError: FirstError[#1, [Failure instance: Traceback (failure with no frames): <type 'exceptions.ValueError'>: Failed to connect to network.
]]
```

There are several issues with this:
1. It's poor UX to wait a full two minutes and then simply die. `status` should instead report it is unable to connect, and can report this sooner than 2 full minutes.
1. Since the daemon doesn't report it's inability to start in a formal way, the app cannot detect and report this to the user.

**Comment by alyssaoc** [comment]
@tzarebczan Could you verify if this still happening? @eukreign Is the timeout different between lbryum and lbrymx?

**Comment by eukreign** [comment]
The new wallet times out much quicker and tries the next lbryumx server in the list.
