### ISSUE TITLE
windows build is failing on appveyor

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry#1087]
```lbrynet.tests.unit.lbrynet_daemon.test_Downloader
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\twisted\trial\runner.py", line 508, in loadPackage
    module = modinfo.load()
  File "c:\python27\lib\site-packages\twisted\python\modules.py", line 392, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "c:\python27\lib\site-packages\twisted\python\reflect.py", line 300, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "c:\python27\lib\site-packages\twisted\python\reflect.py", line 247, in _importAndCheckStack
    reraise(excValue, excTraceback)
  File "C:\projects\lbry\lbrynet\tests\unit\lbrynet_daemon\test_ExchangeRateManager.py", line 7, in <module>
    from lbrynet.tests.mocks import ExchangeRateManager as DummyExchangeRateManager
  File "C:\projects\lbry\lbrynet\tests\mocks.py", line 6, in <module>
    from lbrynet.core import PTCWallet
  File "C:\projects\lbry\lbrynet\core\PTCWallet.py", line 8, in <module>
    from lbrynet.core.client.ClientRequest import ClientRequest
  File "C:\projects\lbry\lbrynet\core\client\ClientRequest.py", line 1, in <module>
    from lbrynet.blob.blob_file import MAX_BLOB_SIZE
  File "C:\projects\lbry\lbrynet\blob\__init__.py", line 1, in <module>
    from blob_file import BlobFile
  File "C:\projects\lbry\lbrynet\blob\blob_file.py", line 4, in <module>
    from twisted.web.client import FileBodyProducer
  File "c:\python27\lib\site-packages\twisted\web\client.py", line 42, in <module>
    from twisted.internet.endpoints import TCP4ClientEndpoint, SSL4ClientEndpoint
  File "c:\python27\lib\site-packages\twisted\internet\endpoints.py", line 36, in <module>
    from twisted.internet.stdio import StandardIO, PipeAddress
  File "c:\python27\lib\site-packages\twisted\internet\stdio.py", line 30, in <module>
    from twisted.internet import _win32stdio
  File "c:\python27\lib\site-packages\twisted\internet\_win32stdio.py", line 9, in <module>
    import win32api
exceptions.ImportError: DLL load failed: The specified module could not be found.```

**Comment by jackrobison** [comment]
This error isn't happening any more, but the build is still failing (appveyor raised our limit from 1gb to 10): https://ci.appveyor.com/project/LBRY/lbry/build/1.0.3339#L1418

**Comment by IGassmann** [comment]
The error was happening due to policy changes from AppVeyor aimed to prevent abuses. Fortunately, the error isn't happening anymore.
