### ISSUE TITLE
Installation From Source Issue

### ISSUE THREAD

**Issue by andrefisch** [lbryio/lbry#1112]
## The Issue

When I install the code from source I follow all the steps (using pip2) and all of the commands execute without problems until I run the command "lbrynet-daemon". When I do I get the following output.

Traceback (most recent call last):
  File "/usr/local/bin/lbrynet-daemon", line 11, in <module>
    load_entry_point('lbrynet', 'console_scripts', 'lbrynet-daemon')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/andrefisch/lbry/lbrynet/daemon/__init__.py", line 1, in <module>
    from lbrynet.daemon.auth.client import LBRYAPIClient
  File "/home/andrefisch/lbry/lbrynet/daemon/auth/client.py", line 3, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 54, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

## System Configuration
- Operating system: Ubuntu 16.04

**Comment by tzarebczan** [comment]
Was this on a fresh

**Comment by tzarebczan** [comment]
Was this on a fresh install or did you possibly have some of the dependent objects already installed? I found this https://stackoverflow.com/questions/47197083/python-pip-error-just-after-fresh-install on stackoverflow, mind giving it a try?

**Comment by kauffj** [comment]
@andrefisch can you please post the full command line output, including the steps before this? If this wasn't done in a virtual environment, please make sure to do that.

**Comment by andrefisch** [comment]
following the instructions in the link provided by tzarebczan solved the problem
