### ISSUE TITLE
V19 - ConnectionManager spam invalid streams / cleanup of streams fails

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1117]
## The Issue
After upgrading to v19 RC35, connection manager keeps trying to recover invalid streams:

```
2018-02-15 10:15:57,802 INFO     lbrynet.daemon.Daemon:525: Starting the file manager
2018-02-15 10:15:57,835 INFO     lbrynet.file_manager.EncryptedFileManager:105: Trying to start 811 files
2018-02-15 10:15:57,835 INFO     lbrynet.file_manager.EncryptedFileManager:108: Started 0/811 files
2018-02-15 10:15:57,937 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager Titanfall_2_Theme.themepack does not have a head blob
2018-02-15 10:15:59,907 WARNING  lbrynet.core.client.StreamProgressManager:158: Error outputting blob 2f87112c765f32baf8ec99b8379e850387a4596df832a7897377f998cf6f98f80413460a6a46766ba0081cf1a547cde6: Invalid padding bytes.
2018-02-15 10:16:04,707 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
2018-02-15 10:16:17,170 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
2018-02-15 10:16:18,131 INFO     lbrynet.file_manager.EncryptedFileManager:108: Started 500/811 files
2018-02-15 10:16:19,187 WARNING  lbrynet.core.client.StreamProgressManager:158: Error outputting blob bfe5f644d0af2c4a4bc3ec04a9b5260e2625a64b608bfef2819df6e81268567e0c2b35f52e710088db9d211ef8094328: Invalid padding bytes.
2018-02-15 10:16:19,585 WARNING  lbrynet.core.client.StreamProgressManager:158: Error outputting blob 34694830635750692d877580a1aabfcf757e71a26c65e62e907bc05ddbaaa404fe968062e5133191d32d3d0f1973b61c: Invalid padding bytes.
2018-02-15 10:16:21,701 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager m0000005.mts does not have a head blob
2018-02-15 10:16:22,180 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
2018-02-15 10:16:26,132 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager 1 - 'Fear the Boom and Bust' - Keynes vs. Hayek Rap Battle.mp4 does not have a head blob
2018-02-15 10:16:27,193 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
2018-02-15 10:16:28,342 INFO     lbrynet.file_manager.EncryptedFileManager:123: Started 811 lbry files
2018-02-15 10:16:28,348 INFO     lbrynet.file_manager.EncryptedFileManager:48: Started file manager
2018-02-15 10:16:28,348 INFO     lbrynet.daemon.Daemon:529: Done setting up file manager
2018-02-15 10:16:28,348 INFO     lbrynet.daemon.Daemon:324: Daemon bound to port: 3333
2018-02-15 10:16:28,400 INFO     lbrynet.daemon.Daemon:258: Starting balance: 6.28581605
2018-02-15 10:16:28,400 INFO     lbrynet.daemon.Daemon:261: Started lbrynet-daemon

......reflections.....
2018-02-15 10:18:56,292 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager 1 - 'Fear the Boom and Bust' - Keynes vs. Hayek Rap Battle.mp4 does not have a head blob
2018-02-15 10:18:57,308 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
2018-02-15 10:19:01,295 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager 1 - 'Fear the Boom and Bust' - Keynes vs. Hayek Rap Battle.mp4 does not have a head blob
2018-02-15 10:19:02,309 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
2018-02-15 10:19:06,296 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager 1 - 'Fear the Boom and Bust' - Keynes vs. Hayek Rap Battle.mp4 does not have a head blob
2018-02-15 10:19:07,311 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
2018-02-15 10:19:11,022 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager m0000005.mts does not have a head blob
2018-02-15 10:19:11,296 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager 1 - 'Fear the Boom and Bust' - Keynes vs. Hayek Rap Battle.mp4 does not have a head blob
2018-02-15 10:19:11,440 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager Titanfall_2_Theme.themepack does not have a head blob
2018-02-15 10:19:12,312 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
2018-02-15 10:19:16,298 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager 1 - 'Fear the Boom and Bust' - Keynes vs. Hayek Rap Battle.mp4 does not have a head blob
2018-02-15 10:19:17,312 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
2018-02-15 10:19:21,299 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager 1 - 'Fear the Boom and Bust' - Keynes vs. Hayek Rap Battle.mp4 does not have a head blob
2018-02-15 10:19:22,313 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
2018-02-15 10:19:26,299 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager 1 - 'Fear the Boom and Bust' - Keynes vs. Hayek Rap Battle.mp4 does not have a head blob
2018-02-15 10:19:27,315 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
2018-02-15 10:19:31,301 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager 1 - 'Fear the Boom and Bust' - Keynes vs. Hayek Rap Battle.mp4 does not have a head blob
2018-02-15 10:19:32,315 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
2018-02-15 10:19:36,302 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager 1 - 'Fear the Boom and Bust' - Keynes vs. Hayek Rap Battle.mp4 does not have a head blob
2018-02-15 10:19:37,316 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
2018-02-15 10:19:41,302 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager 1 - 'Fear the Boom and Bust' - Keynes vs. Hayek Rap Battle.mp4 does not have a head blob
2018-02-15 10:19:42,318 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
2018-02-15 10:19:44,114 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager Titanfall_2_Theme.themepack does not have a head blob
2018-02-15 10:19:46,303 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager 1 - 'Fear the Boom and Bust' - Keynes vs. Hayek Rap Battle.mp4 does not have a head blob
2018-02-15 10:19:47,319 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
2018-02-15 10:19:51,305 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager 1 - 'Fear the Boom and Bust' - Keynes vs. Hayek Rap Battle.mp4 does not have a head blob
2018-02-15 10:19:52,319 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
2018-02-15 10:19:56,306 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager 1 - 'Fear the Boom and Bust' - Keynes vs. Hayek Rap Battle.mp4 does not have a head blob
2018-02-15 10:19:57,321 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
2018-02-15 10:20:01,308 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager 1 - 'Fear the Boom and Bust' - Keynes vs. Hayek Rap Battle.mp4 does not have a head blob
2018-02-15 10:20:02,322 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
2018-02-15 10:20:03,183 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager m0000005.mts does not have a head blob
2018-02-15 10:20:06,309 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager 1 - 'Fear the Boom and Bust' - Keynes vs. Hayek Rap Battle.mp4 does not have a head blob
2018-02-15 10:20:07,322 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
2018-02-15 10:20:11,309 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager 1 - 'Fear the Boom and Bust' - Keynes vs. Hayek Rap Battle.mp4 does not have a head blob
2018-02-15 10:20:12,323 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
2018-02-15 10:20:16,311 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager 1 - 'Fear the Boom and Bust' - Keynes vs. Hayek Rap Battle.mp4 does not have a head blob
2018-02-15 10:20:17,325 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
2018-02-15 10:20:21,312 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager 1 - 'Fear the Boom and Bust' - Keynes vs. Hayek Rap Battle.mp4 does not have a head blob
2018-02-15 10:20:22,325 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
2018-02-15 10:20:23,276 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager Titanfall_2_Theme.themepack does not have a head blob
2018-02-15 10:20:26,312 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager 1 - 'Fear the Boom and Bust' - Keynes vs. Hayek Rap Battle.mp4 does not have a head blob
2018-02-15 10:20:27,326 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
2018-02-15 10:20:31,313 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager 1 - 'Fear the Boom and Bust' - Keynes vs. Hayek Rap Battle.mp4 does not have a head blob
2018-02-15 10:20:32,328 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
2018-02-15 10:20:36,315 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager 1 - 'Fear the Boom and Bust' - Keynes vs. Hayek Rap Battle.mp4 does not have a head blob
2018-02-15 10:20:37,328 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
2018-02-15 10:20:41,315 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager 1 - 'Fear the Boom and Bust' - Keynes vs. Hayek Rap Battle.mp4 does not have a head blob
2018-02-15 10:20:42,329 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
2018-02-15 10:20:46,316 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager 1 - 'Fear the Boom and Bust' - Keynes vs. Hayek Rap Battle.mp4 does not have a head blob
2018-02-15 10:20:47,331 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
2018-02-15 10:20:51,318 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager 1 - 'Fear the Boom and Bust' - Keynes vs. Hayek Rap Battle.mp4 does not have a head blob
2018-02-15 10:20:52,332 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
2018-02-15 10:20:56,319 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager 1 - 'Fear the Boom and Bust' - Keynes vs. Hayek Rap Battle.mp4 does not have a head blob
2018-02-15 10:20:57,332 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
2018-02-15 10:21:01,319 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager 1 - 'Fear the Boom and Bust' - Keynes vs. Hayek Rap Battle.mp4 does not have a head blob
2018-02-15 10:21:02,334 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
2018-02-15 10:21:02,993 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager m0000005.mts does not have a head blob
2018-02-15 10:21:06,321 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager 1 - 'Fear the Boom and Bust' - Keynes vs. Hayek Rap Battle.mp4 does not have a head blob
2018-02-15 10:21:07,335 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
2018-02-15 10:21:08,242 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager Titanfall_2_Theme.themepack does not have a head blob
2018-02-15 10:21:11,322 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager 1 - 'Fear the Boom and Bust' - Keynes vs. Hayek Rap Battle.mp4 does not have a head blob
2018-02-15 10:21:12,335 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
2018-02-15 10:21:16,322 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager 1 - 'Fear the Boom and Bust' - Keynes vs. Hayek Rap Battle.mp4 does not have a head blob
2018-02-15 10:21:17,336 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
2018-02-15 10:21:21,323 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager 1 - 'Fear the Boom and Bust' - Keynes vs. Hayek Rap Battle.mp4 does not have a head blob
2018-02-15 10:21:22,338 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
2018-02-15 10:21:26,325 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager 1 - 'Fear the Boom and Bust' - Keynes vs. Hayek Rap Battle.mp4 does not have a head blob
2018-02-15 10:21:27,338 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
2018-02-15 10:21:31,325 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager 1 - 'Fear the Boom and Bust' - Keynes vs. Hayek Rap Battle.mp4 does not have a head blob
2018-02-15 10:21:32,338 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
2018-02-15 10:21:36,326 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager 1 - 'Fear the Boom and Bust' - Keynes vs. Hayek Rap Battle.mp4 does not have a head blob
2018-02-15 10:21:37,339 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
2018-02-15 10:21:41,328 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager 1 - 'Fear the Boom and Bust' - Keynes vs. Hayek Rap Battle.mp4 does not have a head blob
2018-02-15 10:21:42,341 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
2018-02-15 10:21:46,328 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager 1 - 'Fear the Boom and Bust' - Keynes vs. Hayek Rap Battle.mp4 does not have a head blob
2018-02-15 10:21:47,342 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
2018-02-15 10:21:50,904 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager Titanfall_2_Theme.themepack does not have a head blob
2018-02-15 10:21:51,329 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager 1 - 'Fear the Boom and Bust' - Keynes vs. Hayek Rap Battle.mp4 does not have a head blob
2018-02-15 10:21:52,342 WARNING  lbrynet.core.client.ConnectionManager:186: Connection Manager lizard-vs-spider.mp4 does not have a head blob
```

### Expected behaviour
Fail to start once, notify user

### Actual behaviour
Spams over and over

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by lyoshenka** [comment]
i believe  this is fixed

**Comment by tzarebczan** [comment]
I'm not sure if @jackrobison tried to fix this particular issue, but he did attempt to clean up invalid streams in RC37. When I ran it, I got the below. He said he's looking into it. 

```
2018-02-22 11:39:06,578 INFO     lbrynet.file_manager.EncryptedFileManager:105: Trying to start 799 files
2018-02-22 11:39:06,579 INFO     lbrynet.file_manager.EncryptedFileManager:108: Started 0/799 files
2018-02-22 11:39:07,627 WARNING  lbrynet.file_manager.EncryptedFileManager:123: Stream for descriptor 59edac42451abeabc06ee734d8b26a60e02a299afeae1e3fe1d8e2ceaf381ac41a915bee74bb687444a9979823b5316c is invalid (Does not end with a zero-length blob.), cleaning it up
2018-02-22 11:39:10,318 WARNING  lbrynet.file_manager.EncryptedFileManager:123: Stream for descriptor 6c17493a0ff3cda2159cb512c4703808c23427351810690b1829304a6264b2e52a21a5f085d83b7122035d509f791caf is invalid (Does not end with a zero-length blob.), cleaning it up
2018-02-22 11:39:34,812 WARNING  lbrynet.database.storage:79: database was locked. rerunning <function runInteraction at 0x03711C30> with args (<lbrynet.database.storage.SqliteConnection instance at 0x04B27CB0>, <function get_and_update at 0x09AE5A70>), kwargs {}
2018-02-22 11:39:39,868 WARNING  lbrynet.database.storage:79: database was locked. rerunning <function runInteraction at 0x03711C30> with args (<lbrynet.database.storage.SqliteConnection instance at 0x04B27CB0>, <function get_and_update at 0x09AE5A70>), kwargs {}
2018-02-22 11:39:44,924 WARNING  lbrynet.database.storage:79: database was locked. rerunning <function runInteraction at 0x03711C30> with args (<lbrynet.database.storage.SqliteConnection instance at 0x04B27CB0>, <function get_and_update at 0x09AE5A70>), kwargs {}
2018-02-22 11:39:49,979 WARNING  lbrynet.database.storage:79: database was locked. rerunning <function runInteraction at 0x03711C30> with args (<lbrynet.database.storage.SqliteConnection instance at 0x04B27CB0>, <function get_and_update at 0x09AE5A70>), kwargs {}
2018-02-22 11:39:49,980 CRITICAL twisted:154: Unhandled error in Deferred:
2018-02-22 11:39:49,980 CRITICAL twisted:154: 
Traceback (most recent call last):
  File "site-packages\twisted\python\threadpool.py", line 246, in inContext
  File "site-packages\twisted\python\threadpool.py", line 262, in <lambda>
  File "site-packages\twisted\python\context.py", line 118, in callWithContext
  File "site-packages\twisted\python\context.py", line 81, in callWithContext
  File "site-packages\twisted\enterprise\adbapi.py", line 477, in _runInteraction
  File "site-packages\twisted\enterprise\adbapi.py", line 467, in _runInteraction
  File "site-packages\lbrynet\database\storage.py", line 268, in get_and_update
OperationalError: database is locked
2018-02-22 11:39:55,091 WARNING  lbrynet.file_manager.EncryptedFileManager:123: Stream for descriptor 57fdb5dbc26e84a6458bbd7990412c7b6895a909666c41dedfd25cbb38f3426e3ed66b82d2201be36e239324b0d01d94 is invalid (Does not end with a zero-length blob.), cleaning it up
2018-02-22 11:39:55,108 WARNING  lbrynet.file_manager.EncryptedFileManager:123: Stream for descriptor 285c351beb4f98264da44e02e70ef1b2112722513604ccde823918a81827d80aecc8b6157c694647d62edd41b9af2fa8 is invalid (Does not end with a zero-length blob.), cleaning it up
2018-02-22 11:40:01,471 WARNING  lbrynet.file_manager.EncryptedFileManager:123: Stream for descriptor 224aa1ef6446168de9fdf1a9fabc15cefbbea75c1d01ff9831a1b58aba6ad793795556d94b98e97a3cc8475df702e1b1 is invalid (Does not end with a zero-length blob.), cleaning it up
2018-02-22 11:40:03,102 WARNING  lbrynet.file_manager.EncryptedFileManager:123: Stream for descriptor 54b86ab68614d0aa014f18dbdd190b5a70c9b60fccc50c25cbdfe5422f18156dbd5693d31903c3782c8c7e4875028816 is invalid (Does not end with a zero-length blob.), cleaning it up
2018-02-22 11:40:04,049 WARNING  lbrynet.core.client.StreamProgressManager:158: Error outputting blob 2f87112c765f32baf8ec99b8379e850387a4596df832a7897377f998cf6f98f80413460a6a46766ba0081cf1a547cde6: Invalid padding bytes.
2018-02-22 11:40:34,769 WARNING  lbrynet.database.storage:79: database was locked. rerunning <function runInteraction at 0x03711C30> with args (<lbrynet.database.storage.SqliteConnection instance at 0x04B27CB0>, <function get_and_update at 0x048CC670>), kwargs {}
2018-02-22 11:40:39,825 WARNING  lbrynet.database.storage:79: database was locked. rerunning <function runInteraction at 0x03711C30> with args (<lbrynet.database.storage.SqliteConnection instance at 0x04B27CB0>, <function get_and_update at 0x048CC670>), kwargs {}
2018-02-22 11:40:44,069 WARNING  lbrynet.file_manager.EncryptedFileManager:123: Stream for descriptor 9b42adab4f9154e10ef2ec610f730c3a0d9e6d0be1bec772ac5334f345bc3d08467beb254fe9b2ac2965fc819341aa51 is invalid (Does not end with a zero-length blob.), cleaning it up
2018-02-22 11:41:27,500 WARNING  lbrynet.file_manager.EncryptedFileManager:123: Stream for descriptor 8445ccf3283acac0ff963b82fe310c03f3b257b65418944576f323644c2de6ff0f3d83afd10e707054bcd956d7a9dde9 is invalid (Does not end with a zero-length blob.), cleaning it up
2018-02-22 11:41:28,315 ERROR    lbrynet.daemon.DaemonControl:113: Failed to start lbrynet-daemon
Traceback (most recent call last):
  File "site-packages\lbrynet\daemon\DaemonControl.py", line 110, in start_server_and_listen
  File "site-packages\twisted\internet\defer.py", line 1297, in _inlineCallbacks
  File "site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator
  File "site-packages\lbrynet\daemon\DaemonServer.py", line 51, in start
  File "site-packages\twisted\internet\defer.py", line 1297, in _inlineCallbacks
  File "site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator
  File "site-packages\lbrynet\daemon\Daemon.py", line 256, in setup
  File "site-packages\twisted\internet\defer.py", line 1297, in _inlineCallbacks
  File "site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator
  File "site-packages\lbrynet\daemon\Daemon.py", line 529, in _setup_lbry_file_manager
  File "site-packages\twisted\internet\defer.py", line 1297, in _inlineCallbacks
  File "site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator
  File "site-packages\lbrynet\file_manager\EncryptedFileManager.py", line 47, in setup
  File "site-packages\twisted\internet\defer.py", line 1297, in _inlineCallbacks
  File "site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator
  File "site-packages\lbrynet\file_manager\EncryptedFileManager.py", line 125, in _start_lbry_files
  File "site-packages\twisted\internet\defer.py", line 1297, in _inlineCallbacks
  File "site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator
  File "site-packages\lbrynet\database\storage.py", line 343, in delete_stream
  File "site-packages\twisted\python\threadpool.py", line 246, in inContext
  File "site-packages\twisted\python\threadpool.py", line 262, in <lambda>
  File "site-packages\twisted\python\context.py", line 118, in callWithContext
  File "site-packages\twisted\python\context.py", line 81, in callWithContext
  File "site-packages\twisted\enterprise\adbapi.py", line 477, in _runInteraction
  File "site-packages\twisted\enterprise\adbapi.py", line 467, in _runInteraction
  File "site-packages\lbrynet\database\storage.py", line 342, in _delete_stream
InterfaceError: Error binding parameter 0 - probably unsupported type.
2018-02-22 11:41:28,319 INFO     lbrynet.daemon.DaemonServer:55: Stopping the reactor
2018-02-22 11:41:28,319 INFO     lbrynet.daemon.Daemon:419: Closing lbrynet session
2018-02-22 11:41:28,325 INFO     lbrynet.daemon.Daemon:420: Status at time of shutdown: loading_file_manager
2018-02-22 11:41:28,336 INFO     lbrynet.file_manager.EncryptedFileManager:154: Stopping 117 lbry files
2018-02-22 11:41:28,371 INFO     lbrynet.core.Session:174: Stopping session.
2018-02-22 11:41:28,371 INFO     lbrynet.core.BlobAvailability:35: Stopping blob availability tracker.
2018-02-22 11:41:28,375 INFO     lbrynet.core.RateLimiter:83: Stopping rate limiter.
2018-02-22 11:41:28,377 INFO     lbrynet.core.client.DHTPeerFinder:32: Stopping DHT peer finder.
2018-02-22 11:41:28,407 INFO     lbrynet.core.server.DHTHashAnnouncer:31: Stopping DHT hash announcer.
2018-02-22 11:41:28,407 INFO     lbrynet.core.Wallet:103: Stopping wallet.
2018-02-22 11:41:28,473 INFO     lbrynet.core.Wallet:889: Stopped wallet
2018-02-22 11:41:28,474 INFO     lbrynet.core.Wallet:892: Stopped connection to lbryum server
2018-02-22 11:41:28,474 INFO     lbrynet.core.Session:340: Unsetting upnp for session
2018-02-22 11:41:28,480 INFO     lbrynet.dht.protocol:445: Stopping DHT
2018-02-22 11:41:28,480 INFO     lbrynet.dht.protocol:461: DHT stopped

```

**Comment by tzarebczan** [comment]
This was fixed in RC1/RC2 (which have startup issues), but still broken in 0.19.0. Jack will be releasing an updated daemon with the fix for "InterfaceError: Error binding parameter 0 - probably unsupported type."

**Comment by tzarebczan** [comment]
Closing, PC which had stream cleanup issues is now working great on RC7.
