### ISSUE TITLE
stream_availability command tries to download blobs and errors out

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1150]
## The Issue
When running stream_availability on a uri, it tries to download the blobs from each host and errors out. 

lbrynet-cli stream_availability lbry://lock-on-flaming-cliffs-2-guns-only#0202f733bae03b6d598b7b337f5122981b13c995

```
2018-03-15 21:36:18,325 INFO     lbrynet.core.client.BlobRequester:414: Offered rate 0.000000/mb accepted by 188.243.4.139
2018-03-15 21:36:18,326 INFO     lbrynet.core.client.BlobRequester:487: Requesting blob 8799e85a12139b06674daf710f3defd55b2fb2c5b0091fe9555f718cddbaf2349c5acdaa7317762bd29f281b3f82d7ef from 188.243.4.139:3333
2018-03-15 21:36:21,003 INFO     lbrynet.core.client.ClientProtocol:185: Closing the connection to 188.243.4.139:3333 because the download of blob 8799e85a12139b06 was canceled
2018-03-15 21:36:21,632 INFO     lbrynet.core.client.BlobRequester:414: Offered rate 0.000000/mb accepted by 52.72.10.32
2018-03-15 21:36:21,634 INFO     lbrynet.core.client.BlobRequester:487: Requesting blob 8c72104a5681fd26e73e1981be504a6ea54fceed7bdb15db8cc85f9beaa02891980d741b2be57fb6c1d3f0c5720dce3c from 52.72.10.32:3333
2018-03-15 21:36:21,944 INFO     lbrynet.core.client.BlobRequester:563: Blob 8c72104a5681fd26 has been successfully downloaded from 52.72.10.32:3333
2018-03-15 21:36:21,950 WARNING  lbrynet.core.client.BlobRequester:294: An error occurred while downloading 8c72104a5681fd26e73e1981be504a6ea54fceed7bdb15db8cc85f9beaa02891980d741b2be57fb6c1d3f0c5720dce3c from 52.72.10.32:3333. Error: Traceback (most recent call last):
  File "site-packages\twisted\internet\defer.py", line 565, in _startRunCallbacks
    
  File "site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    
  File "site-packages\lbrynet\core\client\BlobRequester.py", line 568, in _download_succeeded
    
  File "site-packages\twisted\internet\defer.py", line 1445, in unwindGenerator
    
--- <exception caught here> ---
  File "site-packages\twisted\internet\defer.py", line 1299, in _inlineCallbacks
    
  File "site-packages\lbrynet\core\BlobManager.py", line 66, in blob_completed
    
exceptions.AttributeError: 'str' object has no attribute 'add_completed_blob'

2018-03-15 21:36:21,950 WARNING  lbrynet.core.client.ClientProtocol:188: The connection to 52.72.10.32:3333 is closing due to: [Failure instance: Traceback: <type 'exceptions.AttributeError'>: 'str' object has no attribute 'add_completed_blob'
site-packages\twisted\internet\defer.py:565:_startRunCallbacks
site-packages\twisted\internet\defer.py:651:_runCallbacks
site-packages\lbrynet\core\client\BlobRequester.py:568:_download_succeeded
site-packages\twisted\internet\defer.py:1445:unwindGenerator
--- <exception caught here> ---
site-packages\twisted\internet\defer.py:1299:_inlineCallbacks
site-packages\lbrynet\core\BlobManager.py:66:blob_completed
]
2018-03-15 21:36:21,951 WARNING  lbrynet.core.client.ClientProtocol:188: The connection to 52.72.10.32:3333 is closing due to: [Failure instance: Traceback: <type 'exceptions.AttributeError'>: 'str' object has no attribute 'add_completed_blob'
site-packages\twisted\internet\defer.py:565:_startRunCallbacks
site-packages\twisted\internet\defer.py:651:_runCallbacks
site-packages\lbrynet\core\client\BlobRequester.py:568:_download_succeeded
site-packages\twisted\internet\defer.py:1445:unwindGenerator
--- <exception caught here> ---
site-packages\twisted\internet\defer.py:1299:_inlineCallbacks
site-packages\lbrynet\core\BlobManager.py:66:blob_completed
]
2018-03-15 21:36:21,953 INFO     lbrynet.core.client.ClientProtocol:228: 'str' object has no attribute 'add_completed_blob'
2018-03-15 21:36:21,957 INFO     lbrynet.core.client.ClientProtocol:230: The connection to 52.72.10.32:3333 is closing due to an error: Traceback (most recent call last):
  File "site-packages\twisted\internet\defer.py", line 565, in _startRunCallbacks
    
  File "site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    
  File "site-packages\lbrynet\core\client\BlobRequester.py", line 568, in _download_succeeded
    
  File "site-packages\twisted\internet\defer.py", line 1445, in unwindGenerator
    
--- <exception caught here> ---
  File "site-packages\twisted\internet\defer.py", line 1299, in _inlineCallbacks
    
  File "site-packages\lbrynet\core\BlobManager.py", line 66, in blob_completed
    
exceptions.AttributeError: 'str' object has no attribute 'add_completed_blob'

2018-03-15 21:36:21,957 WARNING  lbrynet.core.client.ClientProtocol:237: Not asking for another request from 52.72.10.32:3333
2018-03-15 21:36:22,262 INFO     lbrynet.core.client.BlobRequester:414: Offered rate 0.000000/mb accepted by 47.187.66.76
2018-03-15 21:36:22,263 INFO     lbrynet.core.client.BlobRequester:487: Requesting blob 8c72104a5681fd26e73e1981be504a6ea54fceed7bdb15db8cc85f9beaa02891980d741b2be57fb6c1d3f0c5720dce3c from 47.187.66.76:3333
2018-03-15 21:36:22,394 INFO     lbrynet.core.client.BlobRequester:563: Blob 8c72104a5681fd26 has been successfully downloaded from 47.187.66.76:3333
2018-03-15 21:36:22,395 WARNING  lbrynet.core.client.BlobRequester:294: An error occurred while downloading 8c72104a5681fd26e73e1981be504a6ea54fceed7bdb15db8cc85f9beaa02891980d741b2be57fb6c1d3f0c5720dce3c from 47.187.66.76:3333. Error: Traceback (most recent call last):
  File "site-packages\twisted\internet\defer.py", line 565, in _startRunCallbacks
    
  File "site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    
  File "site-packages\lbrynet\core\client\BlobRequester.py", line 568, in _download_succeeded
    
  File "site-packages\twisted\internet\defer.py", line 1445, in unwindGenerator
    
--- <exception caught here> ---
  File "site-packages\twisted\internet\defer.py", line 1299, in _inlineCallbacks
    
  File "site-packages\lbrynet\core\BlobManager.py", line 66, in blob_completed
    
exceptions.AttributeError: 'str' object has no attribute 'add_completed_blob'

2018-03-15 21:36:22,397 WARNING  lbrynet.core.client.ClientProtocol:188: The connection to 47.187.66.76:3333 is closing due to: [Failure instance: Traceback: <type 'exceptions.AttributeError'>: 'str' object has no attribute 'add_completed_blob'
site-packages\twisted\internet\defer.py:565:_startRunCallbacks
site-packages\twisted\internet\defer.py:651:_runCallbacks
site-packages\lbrynet\core\client\BlobRequester.py:568:_download_succeeded
site-packages\twisted\internet\defer.py:1445:unwindGenerator
--- <exception caught here> ---
site-packages\twisted\internet\defer.py:1299:_inlineCallbacks
site-packages\lbrynet\core\BlobManager.py:66:blob_completed
]
2018-03-15 21:36:22,397 WARNING  lbrynet.core.client.ClientProtocol:188: The connection to 47.187.66.76:3333 is closing due to: [Failure instance: Traceback: <type 'exceptions.AttributeError'>: 'str' object has no attribute 'add_completed_blob'
site-packages\twisted\internet\defer.py:565:_startRunCallbacks
site-packages\twisted\internet\defer.py:651:_runCallbacks
site-packages\lbrynet\core\client\BlobRequester.py:568:_download_succeeded
site-packages\twisted\internet\defer.py:1445:unwindGenerator
--- <exception caught here> ---
site-packages\twisted\internet\defer.py:1299:_inlineCallbacks
site-packages\lbrynet\core\BlobManager.py:66:blob_completed
]
2018-03-15 21:36:22,397 INFO     lbrynet.core.client.ClientProtocol:228: 'str' object has no attribute 'add_completed_blob'
2018-03-15 21:36:22,398 INFO     lbrynet.core.client.ClientProtocol:230: The connection to 47.187.66.76:3333 is closing due to an error: Traceback (most recent call last):
  File "site-packages\twisted\internet\defer.py", line 565, in _startRunCallbacks
    
  File "site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    
  File "site-packages\lbrynet\core\client\BlobRequester.py", line 568, in _download_succeeded
    
  File "site-packages\twisted\internet\defer.py", line 1445, in unwindGenerator
    
--- <exception caught here> ---
  File "site-packages\twisted\internet\defer.py", line 1299, in _inlineCallbacks
    
  File "site-packages\lbrynet\core\BlobManager.py", line 66, in blob_completed
    
exceptions.AttributeError: 'str' object has no attribute 'add_completed_blob'

2018-03-15 21:36:22,398 WARNING  lbrynet.core.client.ClientProtocol:237: Not asking for another request from 47.187.66.76:3333
2018-03-15 21:36:22,398 INFO     lbrynet.core.client.BlobRequester:414: Offered rate 0.000000/mb accepted by 184.189.226.81
2018-03-15 21:36:22,398 INFO     lbrynet.core.client.BlobRequester:487: Requesting blob 8c72104a5681fd26e73e1981be504a6ea54fceed7bdb15db8cc85f9beaa02891980d741b2be57fb6c1d3f0c5720dce3c from 184.189.226.81:3333
2018-03-15 21:36:22,812 INFO     lbrynet.core.client.BlobRequester:563: Blob 8c72104a5681fd26 has been successfully downloaded from 184.189.226.81:3333
2018-03-15 21:36:22,812 WARNING  lbrynet.core.client.BlobRequester:294: An error occurred while downloading 8c72104a5681fd26e73e1981be504a6ea54fceed7bdb15db8cc85f9beaa02891980d741b2be57fb6c1d3f0c5720dce3c from 184.189.226.81:3333. Error: Traceback (most recent call last):
  File "site-packages\twisted\internet\defer.py", line 565, in _startRunCallbacks
    
  File "site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    
  File "site-packages\lbrynet\core\client\BlobRequester.py", line 568, in _download_succeeded
    
  File "site-packages\twisted\internet\defer.py", line 1445, in unwindGenerator
    
--- <exception caught here> ---
  File "site-packages\twisted\internet\defer.py", line 1299, in _inlineCallbacks
    
  File "site-packages\lbrynet\core\BlobManager.py", line 66, in blob_completed
    
exceptions.AttributeError: 'str' object has no attribute 'add_completed_blob'

2018-03-15 21:36:22,812 WARNING  lbrynet.core.client.ClientProtocol:188: The connection to 184.189.226.81:3333 is closing due to: [Failure instance: Traceback: <type 'exceptions.AttributeError'>: 'str' object has no attribute 'add_completed_blob'
site-packages\twisted\internet\defer.py:565:_startRunCallbacks
site-packages\twisted\internet\defer.py:651:_runCallbacks
site-packages\lbrynet\core\client\BlobRequester.py:568:_download_succeeded
site-packages\twisted\internet\defer.py:1445:unwindGenerator
--- <exception caught here> ---
site-packages\twisted\internet\defer.py:1299:_inlineCallbacks
site-packages\lbrynet\core\BlobManager.py:66:blob_completed
]
2018-03-15 21:36:22,813 WARNING  lbrynet.core.client.ClientProtocol:188: The connection to 184.189.226.81:3333 is closing due to: [Failure instance: Traceback: <type 'exceptions.AttributeError'>: 'str' object has no attribute 'add_completed_blob'
site-packages\twisted\internet\defer.py:565:_startRunCallbacks
site-packages\twisted\internet\defer.py:651:_runCallbacks
site-packages\lbrynet\core\client\BlobRequester.py:568:_download_succeeded
site-packages\twisted\internet\defer.py:1445:unwindGenerator
--- <exception caught here> ---
site-packages\twisted\internet\defer.py:1299:_inlineCallbacks
site-packages\lbrynet\core\BlobManager.py:66:blob_completed
]
2018-03-15 21:36:22,813 INFO     lbrynet.core.client.ClientProtocol:228: 'str' object has no attribute 'add_completed_blob'
2018-03-15 21:36:22,815 INFO     lbrynet.core.client.ClientProtocol:230: The connection to 184.189.226.81:3333 is closing due to an error: Traceback (most recent call last):
  File "site-packages\twisted\internet\defer.py", line 565, in _startRunCallbacks
    
  File "site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    
  File "site-packages\lbrynet\core\client\BlobRequester.py", line 568, in _download_succeeded
    
  File "site-packages\twisted\internet\defer.py", line 1445, in unwindGenerator
    
--- <exception caught here> ---
  File "site-packages\twisted\internet\defer.py", line 1299, in _inlineCallbacks
    
  File "site-packages\lbrynet\core\BlobManager.py", line 66, in blob_completed
    
exceptions.AttributeError: 'str' object has no attribute 'add_completed_blob'

2018-03-15 21:36:22,815 WARNING  lbrynet.core.client.ClientProtocol:237: Not asking for another request from 184.189.226.81:3333
2018-03-15 21:36:24,759 CRITICAL twisted:154: Unhandled error in Deferred:
2018-03-15 21:36:24,760 CRITICAL twisted:154: 
Traceback (most recent call last):
  File "site-packages\twisted\internet\defer.py", line 1297, in _inlineCallbacks
  File "site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator
  File "site-packages\lbrynet\core\SinglePeerDownloader.py", line 105, in download_temp_blob_from_peer
  File "site-packages\twisted\python\threadpool.py", line 246, in inContext
  File "site-packages\twisted\python\threadpool.py", line 262, in <lambda>
  File "site-packages\twisted\python\context.py", line 118, in callWithContext
  File "site-packages\twisted\python\context.py", line 81, in callWithContext
  File "shutil.py", line 266, in rmtree
  File "shutil.py", line 264, in rmtree
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\solodolo\\appdata\\local\\temp\\tmpjqclgs\\8c72104a5681fd26e73e1981be504a6ea54fceed7bdb15db8cc85f9beaa02891980d741b2be57fb6c1d3f0c5720dce3c'
2018-03-15 21:36:24,763 CRITICAL twisted:154: Unhandled error in Deferred:
2018-03-15 21:36:24,763 CRITICAL twisted:154: 
Traceback (most recent call last):
  File "site-packages\twisted\internet\defer.py", line 1297, in _inlineCallbacks
  File "site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator
  File "site-packages\lbrynet\core\SinglePeerDownloader.py", line 105, in download_temp_blob_from_peer
  File "site-packages\twisted\python\threadpool.py", line 246, in inContext
  File "site-packages\twisted\python\threadpool.py", line 262, in <lambda>
  File "site-packages\twisted\python\context.py", line 118, in callWithContext
  File "site-packages\twisted\python\context.py", line 81, in callWithContext
  File "shutil.py", line 266, in rmtree
  File "shutil.py", line 264, in rmtree
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\solodolo\\appdata\\local\\temp\\tmpdal5jc\\8c72104a5681fd26e73e1981be504a6ea54fceed7bdb15db8cc85f9beaa02891980d741b2be57fb6c1d3f0c5720dce3c'
2018-03-15 21:36:24,766 CRITICAL twisted:154: Unhandled error in Deferred:
2018-03-15 21:36:24,766 CRITICAL twisted:154: 
Traceback (most recent call last):
  File "site-packages\twisted\internet\defer.py", line 1297, in _inlineCallbacks
  File "site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator
  File "site-packages\lbrynet\core\SinglePeerDownloader.py", line 105, in download_temp_blob_from_peer
  File "site-packages\twisted\python\threadpool.py", line 246, in inContext
  File "site-packages\twisted\python\threadpool.py", line 262, in <lambda>
  File "site-packages\twisted\python\context.py", line 118, in callWithContext
  File "site-packages\twisted\python\context.py", line 81, in callWithContext
  File "shutil.py", line 266, in rmtree
  File "shutil.py", line 264, in rmtree
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\solodolo\\appdata\\local\\temp\\tmpzmtcaa\\8c72104a5681fd26e73e1981be504a6ea54fceed7bdb15db8cc85f9beaa02891980d741b2be57fb6c1d3f0c5720dce3c'

```

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## System Configuration

 

- LBRY Daemon version: 0.19.0
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by alyssaoc** [comment]
@tzarebczan will see if the output is valid, this no longer errors
