### ISSUE TITLE
stream_availability command fails to run

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1156]
## The Issue
Somewhere after 0.19.0, the stream availability command now fails to run. 

```
c:\Program Files\LBRY\resources\static\daemon>lbrynet-cli stream_availability lbry://lock-on-flaming-cliffs-2-guns-only#0202f733bae03b6d598b7b337f5122981b13c995
Traceback (most recent call last):
  File "lbrynet-cli-script.py", line 2, in <module>
  File "site-packages\lbrynet\daemon\DaemonCLI.py", line 86, in main
  File "site-packages\docopt.py", line 560, in docopt
  File "site-packages\docopt.py", line 373, in parse_pattern
  File "site-packages\docopt.py", line 381, in parse_expr
  File "site-packages\docopt.py", line 396, in parse_seq
  File "site-packages\docopt.py", line 413, in parse_atom
  File "site-packages\docopt.py", line 381, in parse_expr
  File "site-packages\docopt.py", line 396, in parse_seq
  File "site-packages\docopt.py", line 413, in parse_atom
  File "site-packages\docopt.py", line 387, in parse_expr
  File "site-packages\docopt.py", line 396, in parse_seq
  File "site-packages\docopt.py", line 421, in parse_atom
  File "site-packages\docopt.py", line 312, in parse_long
docopt.DocoptLanguageError: --search_timeout is not a unique prefix: --search_timeout, --search_timeout?
Failed to execute script lbrynet-cli-script
```

Previous to this, it would cause these errors in the log: https://github.com/lbryio/lbry/issues/1150

### Steps to reproduce
1. Run lbrynet-cli stream_availability lbry://lock-on-flaming-cliffs-2-guns-only
2. Notice error

### Expected behaviour
Return results

### Actual behaviour
fails to run

## System Configuration

 

- LBRY Daemon version: 0.19.1
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by hackrush01** [comment]
Closed from #1157
