### ISSUE TITLE
db migration fails from 0.18x to 0.20rc9

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1196]
## The Issue
When trying to run 0.20rc9 after running 0.18/0.18.2, the db migrator fails. We may have old returning users who are still on 0.18.x and will need to upgrade directly to 0.20. If upgrading to 0.19.x in between the two, it works fine. But if you try to run 0.19.1 after attempting 0.20rc9, it fails with the same error.

```
018-05-09 11:35:21,040 INFO     lbrynet.daemon.Daemon:274: Platform: {"lbrynet_version": "0.20.0rc9", "platform": "Windows-10-10.0.15063", "os_system": "Windows", "python_version": "2.7.14", "os_release": "10", "lbryum_version": "3.2.1", "ip": "47.17.162.103", "lbryschema_version": "0.0.15", "processor": "Intel64 Family 6 Model 60 Stepping 3, GenuineIntel", "build": "rc"}
2018-05-09 11:35:21,046 INFO     lbrynet.daemon.Daemon:477: Loading databases
2018-05-09 11:35:21,049 INFO     lbrynet.daemon.Daemon:505: Upgrading your databases (revision 4 to 7)
2018-05-09 11:35:21,051 INFO     lbrynet.database.migrator.migrate4to5:9: Doing the migration
2018-05-09 11:35:21,062 INFO     lbrynet.database.migrator.migrate4to5:11: Migration succeeded
2018-05-09 11:35:21,085 ERROR    lbrynet.daemon.DaemonControl:109: Failed to start lbrynet-daemon
Traceback (most recent call last):
  File "site-packages\lbrynet\daemon\DaemonControl.py", line 106, in start_server_and_listen
  File "site-packages\twisted\internet\defer.py", line 1297, in _inlineCallbacks
  File "site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator
  File "site-packages\lbrynet\daemon\DaemonServer.py", line 52, in start
  File "site-packages\twisted\internet\defer.py", line 1297, in _inlineCallbacks
  File "site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator
  File "site-packages\lbrynet\daemon\Daemon.py", line 240, in setup
  File "site-packages\twisted\internet\defer.py", line 1297, in _inlineCallbacks
  File "site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator
  File "site-packages\lbrynet\daemon\Daemon.py", line 507, in _check_db_migration
  File "site-packages\twisted\python\threadpool.py", line 246, in inContext
  File "site-packages\twisted\python\threadpool.py", line 262, in <lambda>
  File "site-packages\twisted\python\context.py", line 118, in callWithContext
  File "site-packages\twisted\python\context.py", line 81, in callWithContext
  File "site-packages\lbrynet\database\migrator\dbmigrator.py", line 22, in migrate_db
  File "site-packages\lbrynet\database\migrator\migrate5to6.py", line 249, in do_migration
  File "site-packages\lbrynet\database\migrator\migrate5to6.py", line 19, in _wrapper
  File "site-packages\lbrynet\database\migrator\migrate5to6.py", line 155, in _make_db
  File "site-packages\lbrynet\database\migrator\migrate5to6.py", line 19, in _wrapper
  File "site-packages\lbrynet\database\migrator\migrate5to6.py", line 98, in _populate_blobs
OperationalError: table blob has 7 columns but 5 values were supplied

```
### Steps to reproduce
1. Run 0.18.2 daemon
2. Kill daemon, run 0.20rc9 daemon
3. Notice db error

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tzarebczan** [comment]
Confirmed this is still happening when upgrading to RC11.

@jackrobison , the issue @nikooo777 saw on the youtube sync server might be different because he said upgrading to 19.x before trying 0.20 doesn't fix the problem.
