### ISSUE TITLE
Daemon Error: 'claim' when using stream_availability on invalid URI

### ISSUE THREAD

**Issue by tiger5226** [lbryio/lbry#1210]
Received the following error when checking stream availability for the claim `d48338daa499cbffdc389924f5ce464fcc00e8a2`.

```
2018-05-19 21:36:01,338 WARNING  lbrynet.daemon.auth.server:211: error processing api request: 'claim'
traceback:   File "site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    
  File "site-packages/lbrynet/daemon/Daemon.py", line 3272, in jsonrpc_stream_availability
    
exceptions.KeyError: 'claim'
```

This was using 20rc9

**Comment by tzarebczan** [comment]
@tiger5226 what was the claim URI? Stream availability takes the uri, not claim id. When I looked up that claim_id, I get unknown. The error could definitely be better if you did pass an invalid uri / claimid

**Comment by tiger5226** [comment]
`No-Patrick#d48338daa499cbffdc389924f5ce464fcc00e8a2`

**Comment by tzarebczan** [comment]
This is what I'm seeing for this api call on an invalid URI - the message could be better:
```
lbrynet-cli stream_availability No-Patrick#d48338daa499cbffdc389924f5ce464fcc00e8a2
ERROR: 'claim'
```

**Comment by alyssaoc** [comment]
@tiger5226 Is this still happening?

**Comment by tiger5226** [comment]
I don't have the code I was using to produce that anymore. Looks like @tzarebczan was able to reproduce it with the `lbrynet-cli`. I just ran it with the version I have 

```
MacBook-Pro:~ Mark$ ./lbrynet-cli stream_availability No-Patrick#d48338daa499cbffdc389924f5ce464fcc00e8a2
Traceback (most recent call last):
  File "lbrynet-cli-script.py", line 2, in <module>
  File "site-packages/lbrynet/daemon/DaemonCLI.py", line 111, in main
KeyError: 'code'
Failed to execute script lbrynet-cli-script
MacBook-Pro:~ Mark$ ./lbrynet-cli version
{
  "build": "rc",
  "lbrynet_version": "0.20.0rc9",
  "lbryschema_version": "0.0.15",
  "lbryum_version": "3.2.1",
  "os_release": "17.4.0",
  "os_system": "Darwin",
  "platform": "Darwin-17.4.0-x86_64-i386-64bit",
  "processor": "i386",
  "python_version": "2.7.13"
}
MacBook-Pro:~ Mark$ 
```

**Comment by eukreign** [comment]
The `stream_availability` command has been removed.
