### ISSUE TITLE
Failure to upgrade old version of lbrynet

### ISSUE THREAD

**Issue by nikooo777** [lbryio/lbry#1235]
## The Issue

I started windows and I very rarely do that so I had a very old version of LBRY.
I tried upgrading and besides having to deactivate the antivirus, i'm failing to start lbrynet.

### Steps to reproduce
1. Be on a very old version.
2. Upgrade
3. start lbrynet manually

### Expected behaviour
it starts and migrates the db/configs

### Actual behaviour
```
C:\Program Files\LBRY\resources\static\daemon>lbrynet-daemon.exe
Traceback (most recent call last):
  File "lbrynet-daemon-script.py", line 2, in <module>
  File "site-packages\lbrynet\daemon\DaemonControl.py", line 61, in start
  File "site-packages\lbrynet\conf.py", line 532, in load_conf_file_settings
  File "site-packages\lbrynet\conf.py", line 508, in _convert_conf_file_lists
  File "site-packages\lbrynet\conf.py", line 167, in server_list
  File "site-packages\lbrynet\conf.py", line 162, in server_port
AttributeError: 'list' object has no attribute 'split'
Failed to execute script lbrynet-daemon-script
```

## System Configuration

my config file (daemon_settings.yml):
```
allowed_origin: ''
api_host: localhost
api_port: 5279
cache_time: 150
data_dir: C:\Users\Niko\AppData\Roaming\lbrynet
data_rate: 0.0001
delete_blobs_on_remove: true
dht_node_port: 4444
download_directory: C:\Users\Niko\Downloads
download_timeout: 30
is_generous_host: true
known_dht_nodes:
- [lbrynet1.lbry.io, 4444]
- [lbrynet2.lbry.io, 4444]
- [lbrynet3.lbry.io, 4444]
lbryum_wallet_dir: C:\Users\Niko\AppData\Roaming\lbryum
max_connections_per_stream: 5
max_key_fee: {amount: 10, currency: LBC}
min_info_rate: 0.02
min_valuable_hash_rate: 0.05
min_valuable_info_rate: 0.05
peer_port: 3333
pointtrader_server: http://127.0.0.1:2424
reflector_port: 5566
reflector_servers:
- [reflector.lbry.io, 5566]
run_reflector_server: false
sd_download_timeout: 3
share_usage_data: true
use_auth_http: false
use_upnp: true
wallet: lbryum
```

my db_revision: 4

## Anything Else
starting the app fails like shown in screenshot

## Screenshots
https://scrn.storni.info/LBRY_2018-06-08_01-52-40.png

**Comment by shyba** [comment]
Reproduced. Its fixed by removing `reflector_servers` and `known_dht_nodes`

**Comment by tzarebczan** [comment]
Even though a user may have an incorrect configuration setting, the daemon should handle this scenario better.
