### ISSUE TITLE
error handling request - Invalid token

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1248]
## The Issue
Both @shyba and I ran into this recently on startup. @jackrobison believes it's related to cache timeout conditions. 

```
2018-06-14 00:54:58,513 INFO     lbrynet.daemon.Daemon:261: Started lbrynet-daemon
2018-06-14 00:55:03,503 INFO     lbrynet.dht.node:247: Attempting to join the DHT network, 8 contacts known so far
2018-06-14 00:55:14,098 INFO     lbrynet.dht.node:247: Attempting to join the DHT network, 11 contacts known so far
2018-06-14 00:55:20,553 ERROR    lbrynet.dht.protocol:436: error handling request for 34.239.118.206:4444 store
Traceback (most recent call last):
  File "site-packages\lbrynet\dht\protocol.py", line 432, in _handleRPC
  File "site-packages\lbrynet\dht\node.py", line 521, in store
  File "site-packages\lbrynet\dht\node.py", line 356, in verify_token
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
2018-06-14 00:55:23,108 INFO     lbrynet.core.Session:231: Joined the dht
2018-06-14 00:56:22,644 ERROR    lbrynet.dht.protocol:436: error handling request for 34.239.118.206:4444 store
Traceback (most recent call last):
  File "site-packages\lbrynet\dht\protocol.py", line 432, in _handleRPC
  File "site-packages\lbrynet\dht\node.py", line 522, in store
ValueError: Invalid token
2018-06-14 00:56:38,658 ERROR    lbrynet.dht.protocol:436: error handling request for 34.239.118.206:4444 store
Traceback (most recent call last):
  File "site-packages\lbrynet\dht\protocol.py", line 432, in _handleRPC
  File "site-packages\lbrynet\dht\node.py", line 522, in store
ValueError: Invalid token
2018-06-14 00:56:59,221 ERROR    lbrynet.dht.protocol:436: error handling request for 34.239.118.206:4444 store
Traceback (most recent call last):
  File "site-packages\lbrynet\dht\protocol.py", line 432, in _handleRPC
  File "site-packages\lbrynet\dht\node.py", line 522, in store
ValueError: Invalid token
```

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by jackrobison** [comment]
This error is an actual error and is fixed by https://github.com/lbryio/lbry/commit/e6df378e9e28dff63291f402aa9196dd0ecd5cbf

```
2018-06-14 00:55:20,553 ERROR    lbrynet.dht.protocol:436: error handling request for 34.239.118.206:4444 store
Traceback (most recent call last):
  File "site-packages\lbrynet\dht\protocol.py", line 432, in _handleRPC
  File "site-packages\lbrynet\dht\node.py", line 521, in store
  File "site-packages\lbrynet\dht\node.py", line 356, in verify_token
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

This one isn't really an error, it probably shouldn't be logged as a traceback. This one can happen if you've been an active dht node and you restart and nodes who contacted you before the restart attempt to `store` to you using the now invalided cached token.

```
2018-06-14 00:56:59,221 ERROR    lbrynet.dht.protocol:436: error handling request for 34.239.118.206:4444 store
Traceback (most recent call last):
  File "site-packages\lbrynet\dht\protocol.py", line 432, in _handleRPC
  File "site-packages\lbrynet\dht\node.py", line 522, in store
ValueError: Invalid token
```
