### ISSUE TITLE
0.21RC4 errors + not setting UPnP redirects

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1341]
## The Issue
See below for log. I don't see the UPnP mappings being created, and the TCP port is not open according to canyouseeme.org. Also don't see anything trying to to tear them down on shutdown. 

```
2018-08-06 09:19:44,405 INFO     lbrynet.daemon.DaemonControl:84: Starting lbrynet-daemon from command line
2018-08-06 09:19:45,246 INFO     lbrynet.daemon.auth.factory:36: Using non-authenticated API
2018-08-06 09:19:45,247 INFO     lbrynet.daemon.auth.server:223: lbrynet API listening on TCP localhost:5279
2018-08-06 09:19:45,247 INFO     lbrynet.daemon.Daemon:235: Starting lbrynet-daemon
2018-08-06 09:19:45,332 INFO     lbrynet.daemon.Daemon:236: Platform: {"lbrynet_version": "0.21.0rc4", "platform": "Windows-10-10.0.15063", "os_system": "Windows", "python_version": "2.7.15", "os_release": "10", "lbryum_version": "3.2.3", "ip": "47.17.162.103", "lbryschema_version": "0.0.16", "processor": "Intel64 Family 6 Model 60 Stepping 3, GenuineIntel", "build": "rc"}
2018-08-06 09:19:45,480 INFO     lbrynet.daemon.Components:127: Loading databases
2018-08-06 09:19:45,482 INFO     lbrynet.database.storage:174: connecting to database: c:\lbrynew\lbrynet.sqlite
2018-08-06 09:19:45,482 INFO     lbrynet.daemon.ExchangeRateManager:217: Starting exchange rate manager
2018-08-06 09:19:45,513 INFO     lbrynet.core.RateLimiter:72: Starting rate limiter.
2018-08-06 09:19:45,746 INFO     lbrynet.daemon.Components:258: lbryumx2.lbry.io:50001 height: 415450, local height: 415450
2018-08-06 09:19:46,513 INFO     lbrynet.daemon.Components:681: set up redirects using txupnp
2018-08-06 09:19:46,515-upnp.py:32->upnp is not available: no devices found
2018-08-06 09:19:46,515 WARNING  txupnp.upnp:32: upnp is not available: no devices found
2018-08-06 09:19:46,515-upnp.py:32->upnp is not available: no devices found
2018-08-06 09:19:46,515 WARNING  txupnp.upnp:32: upnp is not available: no devices found
2018-08-06 09:19:46,632 INFO     lbrynet.dht.protocol:202: DHT listening on UDP 47.17.162.103:4444
2018-08-06 09:19:46,634 INFO     lbrynet.daemon.Components:411: Started the dht
2018-08-06 09:19:46,634 INFO     lbrynet.core.Wallet:92: Starting wallet.
2018-08-06 09:19:46,744 INFO     lbrynet.core.Wallet:880: Loading the wallet
2018-08-06 09:19:48,836 WARNING  lbrynet.core.Wallet:963: Your wallet is excessively large (3052 addresses), please follow instructions here: https://github.com/lbryio/lbry/issues/437 to reduce your wallet size
Unhandled error in Deferred:
2018-08-06 09:19:48,846 CRITICAL twisted:154: Unhandled error in Deferred:

2018-08-06 09:19:48,846 CRITICAL twisted:154:
Traceback (most recent call last):
  File "site-packages\twisted\internet\defer.py", line 1297, in _inlineCallbacks
  File "site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator
  File "site-packages\txupnp\upnp.py", line 159, in get_next_mapping
  File "site-packages\twisted\python\threadpool.py", line 246, in inContext
  File "site-packages\twisted\python\threadpool.py", line 262, in <lambda>
  File "site-packages\twisted\python\context.py", line 118, in callWithContext
  File "site-packages\twisted\python\context.py", line 81, in callWithContext
TypeError: argument 3 must be string, not int
Unhandled error in Deferred:
2018-08-06 09:19:48,848 CRITICAL twisted:154: Unhandled error in Deferred:

2018-08-06 09:19:48,848 CRITICAL twisted:154:
Traceback (most recent call last):
  File "site-packages\twisted\internet\defer.py", line 1297, in _inlineCallbacks
  File "site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator
  File "site-packages\txupnp\upnp.py", line 159, in get_next_mapping
  File "site-packages\twisted\python\threadpool.py", line 246, in inContext
  File "site-packages\twisted\python\threadpool.py", line 262, in <lambda>
  File "site-packages\twisted\python\context.py", line 118, in callWithContext
  File "site-packages\twisted\python\context.py", line 81, in callWithContext
TypeError: argument 3 must be string, not int
2018-08-06 09:19:48,878 INFO     lbrynet.dht.node:249: Attempting to join the DHT network, 0 contacts known so far
2018-08-06 09:19:52,700 INFO     lbrynet.core.Wallet:978: Local Height: 415450, remote height: 415450, behind: 0
2018-08-06 09:19:52,700 INFO     lbrynet.core.Wallet:986: Wallet Loaded
2018-08-06 09:19:52,700 INFO     lbrynet.core.Wallet:903: Subscribing to addresses
2018-08-06 09:19:52,901 INFO     lbrynet.core.Wallet:905: Synchronized wallet
2018-08-06 09:19:52,907 INFO     lbrynet.core.Wallet:907: Set up lbryum command runner
2018-08-06 09:19:52,924 ERROR    lbrynet.daemon.Component:62: Error setting up peer_protocol_server
Traceback (most recent call last):
  File "site-packages\lbrynet\daemon\Component.py", line 56, in _setup
KeyError: 'TCP'
Unhandled error in Deferred:
2018-08-06 09:19:52,934 CRITICAL twisted:154: Unhandled error in Deferred:

2018-08-06 09:19:52,934 CRITICAL twisted:154:
Traceback (most recent call last):
  File "site-packages\twisted\internet\defer.py", line 1297, in _inlineCallbacks
  File "site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator
  File "site-packages\lbrynet\daemon\Component.py", line 63, in _setup
KeyError: 'TCP'
2018-08-06 09:19:52,936 INFO     lbrynet.daemon.Components:549: Starting the file manager
2018-08-06 09:19:52,940 INFO     lbrynet.file_manager.EncryptedFileManager:125: Starting 5 files
2018-08-06 09:19:52,940 INFO     lbrynet.file_manager.EncryptedFileManager:130: Started 5 lbry files
2018-08-06 09:19:52,940 INFO     lbrynet.file_manager.EncryptedFileManager:49: Started file manager
2018-08-06 09:19:52,940 INFO     lbrynet.daemon.Components:553: Done setting up file manager
2018-08-06 09:19:52,940 INFO     lbrynet.daemon.Daemon:238: Started lbrynet-daemon
2018-08-06 09:19:58,479 INFO     lbrynet.dht.node:249: Attempting to join the DHT network, 8 contacts known so far
2018-08-06 09:20:07,823 INFO     lbrynet.dht.node:249: Attempting to join the DHT network, 13 contacts known so far
2018-08-06 09:20:17,171 INFO     lbrynet.daemon.Components:410: Joined the dht
2018-08-06 09:23:50,413 INFO     lbrynet.file_manager.EncryptedFileManager:151: Stopping 5 lbry files
2018-08-06 09:23:50,414 INFO     lbrynet.file_manager.EncryptedFileManager:255: Stopped encrypted file manager
2018-08-06 09:23:50,414 INFO     lbrynet.core.Wallet:104: Stopping wallet.
2018-08-06 09:23:50,483 INFO     lbrynet.core.Wallet:932: Stopped wallet
2018-08-06 09:23:50,484 INFO     lbrynet.core.Wallet:935: Stopped connection to lbryum server
2018-08-06 09:23:50,484 INFO     lbrynet.dht.protocol:493: Stopping DHT
2018-08-06 09:23:50,484 INFO     lbrynet.dht.protocol:496: DHT stopped
2018-08-06 09:23:50,691 INFO     lbrynet.daemon.ExchangeRateManager:222: Stopping exchange rate manager
2018-08-06 09:23:50,693 INFO     lbrynet.core.RateLimiter:83: Stopping rate limiter.
```

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by nikooo777** [comment]
mine: 

```
[niko:~/work2/repositories/txupnp] [upnp] master ± txupnp-cli list_mappings
2018-08-06 11:42:42,514-scpd.py:88->error ([<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>]) sending POST to http://192.168.0.1:49153/upnp/control/WANIPConn1
headers: OrderedDict([('SOAPAction', 'urn:schemas-upnp-org:service:WANIPConnection:1#GetExternalIPAddress'), ('Host', '239.255.255.250:49153'), ('Content-Type', 'text/xml'), ('Content-Length', 283)])
body:
<?xml version="1.0"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:GetExternalIPAddress xmlns:u="urn:schemas-upnp-org:service:WANIPConnection:1"></u:GetExternalIPAddress></s:Body></s:Envelope>

error: [Failure instance: Traceback: <class 'txupnp.fault.UPnPError'>: [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>]
/home/niko/.virtualenvs/upnp/local/lib/python2.7/site-packages/twisted/internet/defer.py:501:errback
/home/niko/.virtualenvs/upnp/local/lib/python2.7/site-packages/twisted/internet/defer.py:568:_startRunCallbacks
/home/niko/.virtualenvs/upnp/local/lib/python2.7/site-packages/twisted/internet/defer.py:654:_runCallbacks
/home/niko/.virtualenvs/upnp/local/lib/python2.7/site-packages/twisted/internet/defer.py:1475:gotResult
--- <exception caught here> ---
/home/niko/.virtualenvs/upnp/local/lib/python2.7/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/home/niko/.virtualenvs/upnp/local/lib/python2.7/site-packages/twisted/python/failure.py:491:throwExceptionIntoGenerator
/home/niko/work2/repositories/txupnp/txupnp/cli.py:73:run_command
/home/niko/.virtualenvs/upnp/local/lib/python2.7/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/home/niko/.virtualenvs/upnp/local/lib/python2.7/site-packages/twisted/python/failure.py:491:throwExceptionIntoGenerator
/home/niko/work2/repositories/txupnp/txupnp/cli.py:24:list_mappings
/home/niko/.virtualenvs/upnp/local/lib/python2.7/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/home/niko/.virtualenvs/upnp/local/lib/python2.7/site-packages/twisted/python/failure.py:491:throwExceptionIntoGenerator
/home/niko/work2/repositories/txupnp/txupnp/scpd.py:113:__call__
/home/niko/.virtualenvs/upnp/local/lib/python2.7/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/home/niko/.virtualenvs/upnp/local/lib/python2.7/site-packages/twisted/python/failure.py:491:throwExceptionIntoGenerator
/home/niko/work2/repositories/txupnp/txupnp/scpd.py:89:send_upnp_soap
]

```

**Comment by tzarebczan** [comment]
@nikooo777 can you see if 0.21 rc4 reverts to miniupnpc for you and that upnp ports are mapped?

**Comment by nikooo777** [comment]
I can only test this next weekend as I'm no longer under my home AP :/

**Comment by tzarebczan** [comment]
Fixed in 1349
