### ISSUE TITLE
transaction_show api fails with decode error

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1343]
## The Issue
2 examples:
C:\Users\xxxx\Desktop\latest daemon>lbrynet-cli transaction_show 43a0691e46986fd375007221f42c98e24e11e856c1708ac13ed5533c1f5f58f3
ERROR: 'utf8' codec can't decode byte 0x93 in position 5: invalid start byte

C:\Users\xxxx\Desktop\latest daemon>lbrynet-cli transaction_show 315a43c974e16d2c6849692c0362d76b6adb7cbb12180ecc707c05e1a12687ea
ERROR: 'utf8' codec can't decode byte 0x86 in position 19: invalid start byte

Log:
```
2018-08-06 14:03:26,351 ERROR    lbrynet.daemon.auth.server:488: Failed to render API response: {'inputs': [{'signatures': ['30440220206f6f370098b58f50eb97834090504e15e281eeb3e58ca42f76ea2561a0257202201b0221c467c23f48fbd511de4062f41ea0867bcf72be3eeade9788d3986e65b0'], 'prevout_hash': '5a31670ed58f386e31f8f1066d900524024aec8659034d555b2f617a247dfd2d', 'scriptSig': '4730440220206f6f370098b58f50eb97834090504e15e281eeb3e58ca42f76ea2561a0257202201b0221c467c23f48fbd511de4062f41ea0867bcf72be3eeade9788d3986e65b0012102751876478023684b039920dbab148a08ce2749d8b3cda91d908e8722278cbd20', 'sequence': 4294967295L, 'x_pubkeys': ['02751876478023684b039920dbab148a08ce2749d8b3cda91d908e8722278cbd20'], 'address': 'bNmiAsjATRtrhPxB6cpv7c6hP354M4eJLv', 'is_coinbase': False, 'num_sig': 1, 'pubkeys': ['02751876478023684b039920dbab148a08ce2749d8b3cda91d908e8722278cbd20'], 'prevout_n': 1}], 'lockTime': 0, 'version': 1, 'outputs': [{'prevout_n': 0, 'scriptPubKey': 'b5165a6579637573416273747261637443686573735365744df801080110011a9303080112bc02080410011a1a5a65796375732720416273747261637420436865737320536574224543686573732073657420492064657369676e656420666f7220504f562d5261792c20696e73706972656420696e20547375746f6d75204869676f27732064657369676e732e2a00323c437265617469766520436f6d6d6f6e73204174747269627574696f6e2d4e6f6e436f6d6d65726369616c20342e3020496e7465726e6174696f6e616c38004a5568747470733a2f2f737065652e63682f663536636264613735643737316333306461643261646236316638373234656565653863643738632f70496c6e4e706569496449764f4e30356d577739323836592e4a504752005a3868747470733a2f2f6372656174697665636f6d6d6f6e732e6f72672f6c6963656e7365732f62792d6e632f342e302f6c6567616c636f64651a50080110011a3061fb77f328699b8a796ffee913de49b364ab62e7e9e4a58b70774f0be9a23db76e7bad93e9126d0e6c0862d7b8b6d7ac22186170706c69636174696f6e2f6f637465742d73747265616d2a5c080110031a405d3762afaed434ec6142fba4be7b3d07fe85219140c85b46c27290a45c669e42cfa37ea465fdb3946922637abf62474fb612ed851802ac90bb60b34323e916b62214859f223bcbe048503e62bb8f3d39da5066f322866d7576a914adf445a7a7a4b65c45c45dee5c39714132568daa88ac', 'type': 9, 'value': 100000000, 'address': (('ZeycusAbstractChessSet', '\x08\x01\x10\x01\x1a\x93\x03\x08\x01\x12\xbc\x02\x08\x04\x10\x01\x1a\x1aZeycus\' Abstract Chess Set"EChess set I designed for POV-Ray, inspired in Tsutomu Higo\'s designs.*\x002<Creative Commons Attribution-NonCommercial 4.0 International8\x00JUhttps://spee.ch/f56cbda75d771c30dad2adb61f8724eeee8cd78c/pIlnNpeiIdIvON05mWw9286Y.JPGR\x00Z8https://creativecommons.org/licenses/by-nc/4.0/legalcode\x1aP\x08\x01\x10\x01\x1a0a\xfbw\xf3(i\x9b\x8ayo\xfe\xe9\x13\xdeI\xb3d\xabb\xe7\xe9\xe4\xa5\x8bpwO\x0b\xe9\xa2=\xb7n{\xad\x93\xe9\x12m\x0el\x08b\xd7\xb8\xb6\xd7\xac"\x18application/octet-stream*\\\x08\x01\x10\x03\x1a@]7b\xaf\xae\xd44\xecaB\xfb\xa4\xbe{=\x07\xfe\x85!\x91@\xc8[F\xc2r\x90\xa4\\f\x9eB\xcf\xa3~\xa4e\xfd\xb3\x94i"cz\xbfbGO\xb6\x12\xed\x85\x18\x02\xac\x90\xbb`\xb3C#\xe9\x16\xb6"\x14\x85\x9f";\xcb\xe0HP>b\xbb\x8f=9\xdaPf\xf3"\x86'), 'bUb4Djri4MB1isSUUsgpS2ndiyPNigrhCL')}, {'prevout_n': 1, 'scriptPubKey': '76a914056df7958f594c62b2c20073b653e544537507eb88ac', 'type': 1, 'value': 2079945900, 'address': 'bDDyoqfBjS26GThS8pMfT8PuqujnyeRymr'}]}
Traceback (most recent call last):
  File "site-packages\lbrynet\daemon\auth\server.py", line 483, in _callback_render
  File "site-packages\lbrynet\daemon\auth\server.py", line 114, in jsonrpc_dumps_pretty
  File "json\__init__.py", line 251, in dumps
  File "json\encoder.py", line 209, in encode
  File "json\encoder.py", line 434, in _iterencode
  File "json\encoder.py", line 408, in _iterencode_dict
  File "json\encoder.py", line 408, in _iterencode_dict
  File "json\encoder.py", line 332, in _iterencode_list
  File "json\encoder.py", line 408, in _iterencode_dict
  File "json\encoder.py", line 332, in _iterencode_list
  File "json\encoder.py", line 313, in _iterencode_list
UnicodeDecodeError: 'utf8' codec can't decode byte 0x93 in position 5: invalid start byte
2018-08-06 14:03:26,364 WARNING  lbrynet.daemon.auth.server:211: error processing api request: 'utf8' codec can't decode byte 0x93 in position 5: invalid start byte
traceback: 
2018-08-06 14:04:18,816 ERROR    lbrynet.daemon.auth.server:488: Failed to render API response: {'inputs': [{'signatures': ['3045022100bdfad49a3f89eb7fc5b0c130ae8df4fc9bd8ca3e177f149721bc16d2c8e0828b02202bc961431c6428398261694fcbd2ef148ad26bec6fee270252c79b38307deca3'], 'prevout_hash': '17c5d0c9cb4780b17dd3a5a5724c82e96f9de6b19dceff8ac3da4382fa155cb3', 'scriptSig': '483045022100bdfad49a3f89eb7fc5b0c130ae8df4fc9bd8ca3e177f149721bc16d2c8e0828b02202bc961431c6428398261694fcbd2ef148ad26bec6fee270252c79b38307deca301210333e7a6157ed0d443dfe36d6f2bacc46df49813d091ef39ba455ea311cefe853e', 'sequence': 4294967295L, 'x_pubkeys': ['0333e7a6157ed0d443dfe36d6f2bacc46df49813d091ef39ba455ea311cefe853e'], 'address': 'bJX2iiB6GDEwxyesW5SvFKwL6pWuxL4N1v', 'is_coinbase': False, 'num_sig': 1, 'pubkeys': ['0333e7a6157ed0d443dfe36d6f2bacc46df49813d091ef39ba455ea311cefe853e'], 'prevout_n': 0}], 'lockTime': 0, 'version': 1, 'outputs': [{'prevout_n': 0, 'scriptPubKey': 'b507407a65796375734c6408011002225e0801100322583056301006072a8648ce3d020106052b8104000a034200044ec4d891e018bb55d62fd76b844762b037299b7442c627d7035e731530fd72602eaf6c9a3362ed4c9d273669c2ba52a5be2763880ba987736bd2a635c88cb9bf6d7576a914d39e7b76f8b49f80d7efa06f0bb6772ee64ee98c88ac', 'type': 9, 'value': 300000000, 'address': (('@zeycus', '\x08\x01\x10\x02"^\x08\x01\x10\x03"X0V0\x10\x06\x07*\x86H\xce=\x02\x01\x06\x05+\x81\x04\x00\n\x03B\x00\x04N\xc4\xd8\x91\xe0\x18\xbbU\xd6/\xd7k\x84Gb\xb07)\x9btB\xc6\'\xd7\x03^s\x150\xfdr`.\xafl\x9a3b\xedL\x9d\'6i\xc2\xbaR\xa5\xbe\'c\x88\x0b\xa9\x87sk\xd2\xa65\xc8\x8c\xb9\xbf'), 'bY2D8FQGNAWWhiLHXpZF2zDBreokxbfC4J')}, {'prevout_n': 1, 'scriptPubKey': '76a9149e8f0ae241f5631cda2f5a5ef9f5b2e0538567cc88ac', 'type': 1, 'value': 2198600000L, 'address': 'bTBepJpoLET2BGAquCSgwTjsD1V3Fvznsh'}]}
Traceback (most recent call last):
  File "site-packages\lbrynet\daemon\auth\server.py", line 483, in _callback_render
  File "site-packages\lbrynet\daemon\auth\server.py", line 114, in jsonrpc_dumps_pretty
  File "json\__init__.py", line 251, in dumps
  File "json\encoder.py", line 209, in encode
  File "json\encoder.py", line 434, in _iterencode
  File "json\encoder.py", line 408, in _iterencode_dict
  File "json\encoder.py", line 408, in _iterencode_dict
  File "json\encoder.py", line 332, in _iterencode_list
  File "json\encoder.py", line 408, in _iterencode_dict
  File "json\encoder.py", line 332, in _iterencode_list
  File "json\encoder.py", line 313, in _iterencode_list
UnicodeDecodeError: 'utf8' codec can't decode byte 0x86 in position 19: invalid start byte
2018-08-06 14:04:18,831 WARNING  lbrynet.daemon.auth.server:211: error processing api request: 'utf8' codec can't decode byte 0x86 in position 19: invalid start byte
traceback: 

```
## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tzarebczan** [comment]
This is still an issue, @shyba aware.

**Comment by eukreign** [comment]
PR for this merged ^
