### ISSUE TITLE
stream_availability errs

### ISSUE THREAD

**Issue by alyssaoc** [lbryio/lbry#1415]

**Comment by tzarebczan** [comment]
Related: https://github.com/lbryio/lbry/issues/1387

**Comment by tzarebczan** [comment]
```
{
  "code": -32500,
  "data": [
    "  File \"twisted\\internet\\defer.py\", line 654, in _runCallbacks",
    "    ",
    "  File \"lbrynet\\daemon\\auth\\server.py\", line 94, in trap",
    "    ",
    "  File \"twisted\\python\\failure.py\", line 439, in trap",
    "    ",
    "  File \"twisted\\python\\failure.py\", line 467, in raiseException",
    "    ",
    "  File \"twisted\\internet\\defer.py\", line 1416, in _inlineCallbacks",
    "    ",
    "  File \"twisted\\python\\failure.py\", line 491, in throwExceptionIntoGenerator",
    "    ",
    "  File \"lbrynet\\daemon\\auth\\server.py\", line 155, in _inner",
    "    ",
    "  File \"twisted\\internet\\defer.py\", line 1418, in _inlineCallbacks",
    "    ",
    "  File \"lbrynet\\daemon\\Daemon.py\", line 3214, in jsonrpc_stream_availability",
    "    ",
    "builtins.KeyError: 'mantekka-ascend'"
  ],
  "message": "'mantekka-ascend'"
```

**Comment by eukreign** [comment]
will be fixed in #1704

**Comment by tzarebczan** [comment]
Reoping to make this this is fixed:
```Traceback (most recent call last):
  File "site-packages\aiohttp\web_protocol.py", line 418, in start
  File "site-packages\aiohttp\web_app.py", line 458, in _handle
  File "lbrynet\extras\daemon\Daemon.py", line 507, in handle_old_jsonrpc
  File "lbrynet\extras\daemon\Daemon.py", line 3513, in jsonrpc_stream_availability
KeyError: 'one'```

**Comment by jackrobison** [comment]
`stream_availability` has been dropped
