### ISSUE TITLE
Torba wallet fails to load on fresh install (missing files/directory)

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbry#1430]
## The Issue

Torba wallet fails to load on a fresh run through binary  (no previous installation) 

### Steps to reproduce
1. Downloaded binary from latest master (http://build.lbry.io/daemon/build-7013_commit-ee5be5a_branch-master/linux/). Used a machine with no previous lbry installation

### Expected behaviour
Wallet should load 

### Actual behaviour
Wallet does not load (startup_status for wallet is false, cannot access wallet commands)

I get this error message:

```
2018-09-05 17:03:58,167 ERROR    lbrynet.daemon.Component:61: Error setting up blockchain_headers
Traceback (most recent call last):
  File "lbrynet/daemon/Component.py", line 55, in _setup
FileNotFoundError: [Errno 2] No such file or directory: '/home/treantprotector/.local/share/lbry/lbryum/lbc_mainnet'
```

and than 

```
2018-09-05 17:03:59,395 ERROR    lbrynet.daemon.Component:61: Error setting up wallet
Traceback (most recent call last):
  File "site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
  File "site-packages/txupnp/ssdp.py", line 146, in m_search
  File "site-packages/twisted/internet/defer.py", line 1362, in returnValue
twisted.internet.defer._DefGen_Return: []
```

I created this folder manually "/home/treantprotector/.local/share/lbry/lbryum" and I restarted the daemon. This made the previous errors go away but than I got this new error which made the loading of the wallet fail:

```

Traceback (most recent call last):
 File "lbrynet/daemon/Component.py", line 55, in _setup
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEITkqfhg/torba/words/english.txt'
```

## System Configuration

- LBRY Daemon version: master
- LBRY App version: none
- LBRY Installation ID:
- Operating system: Ubuntu 16.04

**Comment by eukreign** [comment]
fixed in torba
