### ISSUE TITLE
0.30 - error handling request -  b'store'

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1446]
## The Issue
Seeing a bunch of these b'store' errors while running the new daemon. Happening repeatedly for some nodes, but there's quite a few uniques too. @shyba/@jack any ideas? 

2018-09-14 22:48:23,526 ERROR    lbrynet.dht.protocol:444: error handling request for 85.17.24.157:52367 b'store'
Traceback (most recent call last):
  File "lbrynet\dht\protocol.py", line 440, in _handleRPC
  File "lbrynet\dht\node.py", line 509, in store
ValueError: Invalid token
2018-09-18 03:56:34,535 ERROR    lbrynet.dht.protocol:444: error handling request for 12.25.9.2:4444 b'store'
Traceback (most recent call last):
  File "lbrynet\dht\protocol.py", line 440, in _handleRPC
  File "lbrynet\dht\node.py", line 509, in store
ValueError: Invalid token
2018-09-18 03:56:36,948 ERROR    lbrynet.dht.protocol:444: error handling request for 35.153.147.111:4444 b'store'
Traceback (most recent call last):
  File "lbrynet\dht\protocol.py", line 440, in _handleRPC
  File "lbrynet\dht\node.py", line 509, in store
ValueError: Invalid token
2018-09-18 04:01:05,846 ERROR    lbrynet.dht.protocol:444: error handling request for 86.120.20.153:4444 b'store'
Traceback (most recent call last):
  File "lbrynet\dht\protocol.py", line 440, in _handleRPC
  File "lbrynet\dht\node.py", line 509, in store
ValueError: Invalid token
2018-09-18 04:01:06,912 ERROR    lbrynet.dht.protocol:444: error handling request for 90.191.13.70:1029 b'store'
Traceback (most recent call last):
  File "lbrynet\dht\protocol.py", line 440, in _handleRPC
  File "lbrynet\dht\node.py", line 509, in store
ValueError: Invalid token
2018-09-18 04:01:49,293 ERROR    lbrynet.dht.protocol:444: error handling request for 54.209.131.62:4444 b'store'
Traceback (most recent call last):
  File "lbrynet\dht\protocol.py", line 440, in _handleRPC
  File "lbrynet\dht\node.py", line 509, in store
ValueError: Invalid token
2018-09-18 04:51:29,024 ERROR    lbrynet.dht.protocol:444: error handling request for 188.243.4.139:4444 b'store'
Traceback (most recent call last):
  File "lbrynet\dht\protocol.py", line 440, in _handleRPC
  File "lbrynet\dht\node.py", line 509, in store
ValueError: Invalid token
2018-09-18 04:52:52,823 ERROR    lbrynet.dht.protocol:444: error handling request for 54.173.171.189:4444 b'store'
Traceback (most recent call last):
  File "lbrynet\dht\protocol.py", line 440, in _handleRPC
  File "lbrynet\dht\node.py", line 509, in store
ValueError: Invalid token
2018-09-18 07:06:13,412 ERROR    lbrynet.dht.protocol:444: error handling request for 117.2.83.143:4444 b'store'
Traceback (most recent call last):
  File "lbrynet\dht\protocol.py", line 440, in _handleRPC
  File "lbrynet\dht\node.py", line 509, in store
ValueError: Invalid token
2018-09-18 08:06:30,265 ERROR    lbrynet.dht.protocol:444: error handling request for 24.247.49.33:49152 b'store'
Traceback (most recent call last):
  File "lbrynet\dht\protocol.py", line 440, in _handleRPC
  File "lbrynet\dht\node.py", line 509, in store
ValueError: Invalid token
2018-09-18 10:36:25,985 ERROR    lbrynet.dht.protocol:444: error handling request for 162.193.206.224:1024 b'store'
Traceback (most recent call last):
  File "lbrynet\dht\protocol.py", line 440, in _handleRPC
  File "lbrynet\dht\node.py", line 509, in store
ValueError: Invalid token
2018-09-18 10:51:03,377 ERROR    lbrynet.dht.protocol:444: error handling request for 73.131.107.27:4444 b'store'
Traceback (most recent call last):
  File "lbrynet\dht\protocol.py", line 440, in _handleRPC
  File "lbrynet\dht\node.py", line 509, in store
ValueError: Invalid token
2018-09-18 10:58:07,874 ERROR    lbrynet.dht.protocol:444: error handling request for 62.248.20.144:4444 b'store'
Traceback (most recent call last):
  File "lbrynet\dht\protocol.py", line 440, in _handleRPC
  File "lbrynet\dht\node.py", line 509, in store
ValueError: Invalid token

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tzarebczan** [comment]
spee.ch is also reporting my node with a similar error:
```
2018-09-19 12:43:52,492 ERROR    lbrynet.dht.protocol:272: DHT RECV REMOTE EXCEPTION FROM 47.17.162.103:62166: b'Invalid token'
2018-09-19 12:43:52,493 ERROR    lbrynet.dht.node:319: Unexpected error while storing blob_hash b'223f788d8231bdd8a9959afa31a212e775d42194f339d2a4822af884da182f1ed6aa4d271e12a4d27572631372741e0c' at <lbrynet.dht.contact._Contact object; IP address: 47.17.162.xxx, UDP port: 62166>: b'Invalid token'
2018-09-19 12:43:52,825 ERROR    lbrynet.dht.protocol:272: DHT RECV REMOTE EXCEPTION FROM 47.17.162.103:4444: b'Invalid token'
2018-09-19 12:43:52,825 ERROR    lbrynet.dht.node:319: Unexpected error while storing blob_hash b'223f788d8231bdd8a9959afa31a212e775d42194f339d2a4822af884da182f1ed6aa4d271e12a4d27572631372741e0c' at <lbrynet.dht.contact._Contact object; IP address: 47.17.162.xxx, UDP port: 4444>: b'Invalid token'
2018-09-19 12:43:55,180 ERROR    lbrynet.dht.protocol:272: DHT RECV REMOTE EXCEPTION FROM 47.17.162.103:62166: b'Invalid token'
2018-09-19 12:43:55,181 ERROR    lbrynet.dht.node:319: Unexpected error while storing blob_hash b'27f465874914fe44331ef38b16d81ec1906ef62502e83a5bbf8ac8c29f079e567890a766df494c530faa389c19c166fb' at <lbrynet.dht.contact._Contact object; IP address: 47.17.162.xxx, UDP port: 62166>: b'Invalid token'
2018-09-19 12:43:55,270 ERROR    lbrynet.dht.protocol:272: DHT RECV REMOTE EXCEPTION FROM 47.17.162.103:4444: b'Invalid token'
2018-09-19 12:43:55,270 ERROR    lbrynet.dht.node:319: Unexpected error while storing blob_hash b'27f465874914fe44331ef38b16d81ec1906ef62502e83a5bbf8ac8c29f079e567890a766df494c530faa389c19c166fb' at <lbrynet.dht.contact._Contact object; IP address: 47.17.162.xxx, UDP port: 4444>: b'Invalid token'
2018-09-19 12:43:55,276 ERROR    lbrynet.dht.protocol:272: DHT RECV REMOTE EXCEPTION FROM 47.17.162.103:62590: b'Invalid token'
2018-09-19 12:43:55,277 ERROR    lbrynet.dht.node:319: Unexpected error while storing blob_hash b'27f465874914fe44331ef38b16d81ec1906ef62502e83a5bbf8ac8c29f079e567890a766df494c530faa389c19c166fb' at <lbrynet.dht.contact._Contact object; IP address: 47.17.162.xxx, UDP port: 62590>: b'Invalid token'
```

**Comment by tzarebczan** [comment]
A recent run: 
https://gist.github.com/tzarebczan/2b850dc3d1a22ac1ec43e8cbc2650934

Still not sure if these are causing any issues, hard to tell from my perspective.

**Comment by alyssaoc** [comment]
@tzarebczan please close if we can

**Comment by tzarebczan** [comment]
Going to keep this open until more nodes are running 0.30 so we can tell if there's an improvement.

**Comment by tzarebczan** [comment]
@shyba saw a bunch recently on my node:

```
Traceback (most recent call last):
  File "lbrynet\dht\protocol.py", line 421, in _handleRPC
  File "lbrynet\dht\node.py", line 498, in store
ValueError: Invalid token
2018-11-06 07:40:48,766 ERROR    lbrynet.dht.protocol:425: error handling request for 34.226.30.189:60212 b'store'
Traceback (most recent call last):
  File "lbrynet\dht\protocol.py", line 421, in _handleRPC
  File "lbrynet\dht\node.py", line 498, in store
ValueError: Invalid token
2018-11-06 07:40:56,247 ERROR    lbrynet.dht.protocol:425: error handling request for 54.209.131.62:61056 b'store'
Traceback (most recent call last):
  File "lbrynet\dht\protocol.py", line 421, in _handleRPC
  File "lbrynet\dht\node.py", line 498, in store
ValueError: Invalid token
2018-11-06 07:40:56,856 ERROR    lbrynet.dht.protocol:425: error handling request for 35.153.147.111:61066 b'store'
Traceback (most recent call last):
  File "lbrynet\dht\protocol.py", line 421, in _handleRPC
  File "lbrynet\dht\node.py", line 498, in store
ValueError: Invalid token
2018-11-06 07:41:00,039 ERROR    lbrynet.dht.protocol:425: error handling request for 54.209.131.62:61056 b'store'
Traceback (most recent call last):
  File "lbrynet\dht\protocol.py", line 421, in _handleRPC
  File "lbrynet\dht\node.py", line 498, in store
ValueError: Invalid token
2018-11-06 07:41:10,004 ERROR    lbrynet.dht.protocol:425: error handling request for 54.209.131.62:61056 b'store'
Traceback (most recent call last):
  File "lbrynet\dht\protocol.py", line 421, in _handleRPC
  File "lbrynet\dht\node.py", line 498, in store
ValueError: Invalid token
2018-11-06 07:41:24,314 ERROR    lbrynet.dht.protocol:425: error handling request for 54.209.131.62:61056 b'store'
Traceback (most recent call last):
  File "lbrynet\dht\protocol.py", line 421, in _handleRPC
  File "lbrynet\dht\node.py", line 498, in store
ValueError: Invalid token
2018-11-06 07:41:24,575 ERROR    lbrynet.dht.protocol:425: error handling request for 35.153.147.111:61066 b'store'
Traceback (most recent call last):
  File "lbrynet\dht\protocol.py", line 421, in _handleRPC
  File "lbrynet\dht\node.py", line 498, in store
ValueError: Invalid token
2018-11-06 07:41:28,718 ERROR    lbrynet.dht.protocol:425: error handling request for 54.209.131.62:4444 b'store'
Traceback (most recent call last):
  File "lbrynet\dht\protocol.py", line 421, in _handleRPC
  File "lbrynet\dht\node.py", line 498, in store
ValueError: Invalid token
2018-11-06 07:41:40,962 ERROR    lbrynet.dht.protocol:425: error handling request for 35.153.147.111:61066 b'store'
Traceback (most recent call last):
  File "lbrynet\dht\protocol.py", line 421, in _handleRPC
  File "lbrynet\dht\node.py", line 498, in store
ValueError: Invalid token
2018-11-06 07:41:59,408 ERROR    lbrynet.dht.protocol:425: error handling request for 35.153.147.111:61066 b'store'
Traceback (most recent call last):
  File "lbrynet\dht\protocol.py", line 421, in _handleRPC
  File "lbrynet\dht\node.py", line 498, in store
ValueError: Invalid token
2018-11-06 07:42:04,116 ERROR    lbrynet.dht.protocol:425: error handling request for 35.153.147.111:61066 b'store'
Traceback (most recent call last):
  File "lbrynet\dht\protocol.py", line 421, in _handleRPC
  File "lbrynet\dht\node.py", line 498, in store
ValueError: Invalid token
2018-11-06 07:42:06,540 ERROR    lbrynet.dht.protocol:425: error handling request for 35.153.147.111:61066 b'store'
Traceback (most recent call last):
  File "lbrynet\dht\protocol.py", line 421, in _handleRPC
  File "lbrynet\dht\node.py", line 498, in store
ValueError: Invalid token
```
