### ISSUE TITLE
0.30 - Fails to copy blockchain headers if they exist, status not running

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1457]
## The Issue
Was going between 0.21.2 and 0.30 and noticed that the daemon won't fully start (is_running = false) if the headers file exists in lbryum and lbc_mainnet. 

```
2018-09-19 12:22:56,465 INFO     lbrynet.daemon.Daemon:264: Platform: {"processor": "Intel64 Family 6 Model 158 Stepping 9, GenuineIntel", "python_version": "3.6.4", "platform": "Windows-10-10.0.17134", "os_release": "10", "os_system": "Windows", "lbrynet_version": "0.30.0a", "lbryschema_version": "0.0.16", "build": "dev", "ip": "47.17.162.103"}
2018-09-19 12:22:56,513 WARNING  lbrynet.daemon.Components:296: Moving old headers from C:\Users\SoloDolo\AppData\Roaming\lbryum\blockchain_headers to C:\Users\SoloDolo\AppData\Roaming\lbryum\lbc_mainnet\headers.
2018-09-19 12:22:56,515 ERROR    lbrynet.daemon.Component:61: Error setting up blockchain_headers
Traceback (most recent call last):
  File "lbrynet\daemon\Component.py", line 55, in _setup
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\SoloDolo\\AppData\\Roaming\\lbryum\\blockchain_headers' -> 'C:\\Users\\SoloDolo\\AppData\\Roaming\\lbryum\\lbc_mainnet\\headers'
2018-09-19 12:22:56,543 INFO     lbrynet.daemon.Components:128: Loading databases
2018-09-19 12:22:56,559 INFO     lbrynet.database.storage:177: connecting to database: C:\Users\xxx\AppData\Roaming\lbrynet\lbrynet.sqlite
2018-09-19 12:22:56,587 INFO     lbrynet.daemon.ExchangeRateManager:212: Starting exchange rate manager
2018-09-19 12:22:56,674 INFO     lbrynet.core.RateLimiter:70: Starting rate limiter.
2018-09-19 12:22:57,680 WARNING  lbrynet.daemon.Components:696: upnp discovery failed:
failed to get version from git
2018-09-19 12:22:57,979 INFO     lbrynet.dht.protocol:208: DHT listening on UDP 4446 (ext port 4446)
2018-09-19 12:22:57,980 INFO     lbrynet.daemon.Components:426: Started the dht
2018-09-19 12:22:57,986 INFO     lbrynet.daemon.Components:339: Starting torba wallet
2018-09-19 12:22:58,301 INFO     torba.basedatabase:50: connecting to database: C:\Users\SoloDolo\AppData\Roaming\lbryum\lbc_mainnet\blockchain.db
2018-09-19 12:22:58,325 INFO     lbrynet.dht.node:239: Attempting to join the DHT network, 0 contacts known so far
2018-09-19 12:22:58,352 WARNING  torba.basenetwork:59: Error setting up socket: module 'socket' has no attribute 'TCP_KEEPIDLE'
2018-09-19 12:22:58,376 INFO     torba.basenetwork:151: Successfully connected to SPV wallet server: tcp:lbryumx1.lbry.io:50001
2018-09-19 12:22:58,401 INFO     torba.baseledger:99: lbc_mainnet: added BlockHeightEvent(height=439361, change=2) header blocks, final height 439361
Unhandled error in Deferred:
2018-09-19 12:22:58,565 CRITICAL twisted:154: Unhandled error in Deferred:

2018-09-19 12:22:58,582 CRITICAL twisted:154:
Traceback (most recent call last):
  File "twisted\internet\defer.py", line 1416, in _inlineCallbacks
  File "twisted\python\failure.py", line 491, in throwExceptionIntoGenerator
  File "lbrynet\daemon\Component.py", line 62, in _setup
  File "lbrynet\daemon\Component.py", line 55, in _setup
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\xxx\\AppData\\Roaming\\lbryum\\blockchain_headers' -> 'C:\\Users\\xxx\\AppData\\Roaming\\lbryum\\lbc_mainnet\\headers'

```
## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by alyssaoc** [comment]
not fixing at this time
