### ISSUE TITLE
exceptions.TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by whitslack** [lbryio/lbry#16]
This occurred while leaving the lbrynet-console idle.

```
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/usr/lib64/python2.7/site-packages/twisted/internet/posixbase.py", line 611, in _doReadOrWrite
    why = selectable.doRead()
--- <exception caught here> ---
  File "/usr/lib64/python2.7/site-packages/twisted/internet/udp.py", line 248, in doRead
    self.protocol.datagramReceived(data, addr)
  File "/usr/lib64/python2.7/site-packages/lbrynet/dht/protocol.py", line 114, in datagramReceived
    message = self._translator.fromPrimitive(msgPrimitive)
  File "/usr/lib64/python2.7/site-packages/lbrynet/dht/msgformat.py", line 46, in fromPrimitive
    msgType = msgPrimitive[self.headerType]
exceptions.TypeError: 'NoneType' object has no attribute '__getitem__'
```

This is commit f5b556c6cbbc26e3489b4b91df580fc0ede97684.

**Comment by whitslack** [comment]
This happened again at commit a882bdb08c26145b4fb322f6e195090fdf57c645.

```
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/usr/lib64/python2.7/site-packages/twisted/internet/posixbase.py", line 611, in _doReadOrWrite
    why = selectable.doRead()
--- <exception caught here> ---
  File "/usr/lib64/python2.7/site-packages/twisted/internet/udp.py", line 248, in doRead
    self.protocol.datagramReceived(data, addr)
  File "/usr/lib64/python2.7/site-packages/lbrynet/dht/protocol.py", line 114, in datagramReceived
    message = self._translator.fromPrimitive(msgPrimitive)
  File "/usr/lib64/python2.7/site-packages/lbrynet/dht/msgformat.py", line 46, in fromPrimitive
    msgType = msgPrimitive[self.headerType]
exceptions.TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by whitslack** [comment]
Still happens at commit 2670279b0d6f94bf25ef34fb654d18c2b3578033.

```
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/usr/lib64/python2.7/site-packages/twisted/internet/posixbase.py", line 611, in _doReadOrWrite
    why = selectable.doRead()
--- <exception caught here> ---
  File "/usr/lib64/python2.7/site-packages/twisted/internet/udp.py", line 248, in doRead
    self.protocol.datagramReceived(data, addr)
  File "/usr/lib64/python2.7/site-packages/lbrynet/dht/protocol.py", line 114, in datagramReceived
    message = self._translator.fromPrimitive(msgPrimitive)
  File "/usr/lib64/python2.7/site-packages/lbrynet/dht/msgformat.py", line 46, in fromPrimitive
    msgType = msgPrimitive[self.headerType]
exceptions.TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by lyoshenka** [comment]
i believe this is fixed
