### ISSUE TITLE
Dameon error in app - Hangs app at starting up

### ISSUE THREAD

**Issue by tiger5226** [lbryio/lbry#1603]
version 0.30.0 / master branch of the app

```
Daemon: 2018-11-05 13:02:48,021 CRITICAL twisted:154: 
  Traceback (most recent call last):
    File "twisted/internet/defer.py", line 1416, in _inlineCallbacks
    File "twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    File "lbrynet/file_manager/EncryptedFileDownloader.py", line 129, in _start
    File "twisted/internet/defer.py", line 654, in _runCallbacks
    File "lbrynet/lbry_file/client/EncryptedFileDownloader.py", line 48, in <lambda>
    File "lbrynet/cryptstream/client/CryptStreamDownloader.py", line 140, in _start
    File "lbrynet/cryptstream/client/CryptStreamDownloader.py", line 155, in _get_download_manager
  AttributeError: 'NoneType' object has no attribute 'get_info_exchanger'

```

**Comment by eukreign** [comment]
Without some more info or context I can't reproduce it.

**Comment by tiger5226** [comment]
I manually deleted the lbrynet binary and the daemon.zip file to force it to download it again. Below are the logs now: 

```
┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:02:48,017 CRITICAL twisted:154: Unhandled error in Deferred:

┗ ----------------------------
┏ Electron -------------------

  Daemon:

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:02:48,021 CRITICAL twisted:154: 
  Traceback (most recent call last):
    File "twisted/internet/defer.py", line 1416, in _inlineCallbacks
    File "twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    File "lbrynet/file_manager/EncryptedFileDownloader.py", line 129, in _start
    File "twisted/internet/defer.py", line 654, in _runCallbacks
    File "lbrynet/lbry_file/client/EncryptedFileDownloader.py", line 48, in <lambda>
    File "lbrynet/cryptstream/client/CryptStreamDownloader.py", line 140, in _start
    File "lbrynet/cryptstream/client/CryptStreamDownloader.py", line 155, in _get_download_manager
  AttributeError: 'NoneType' object has no attribute 'get_info_exchanger'

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:06:26,730 WARNING  aioupnp.gateway:186: found gateway UNKNOWN GATEWAY at b'http://192.168.1.1:1990/WFADevice.xml', but it does not implement required soap commands: ['AddPortMapping', 'DeletePortMapping', 'GetExternalIPAddress']

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:06:26,736 WARNING  aioupnp.gateway:186: found gateway UNKNOWN GATEWAY at b'http://192.168.1.1:1990/WFADevice.xml', but it does not implement required soap commands: ['AddPortMapping', 'DeletePortMapping', 'GetExternalIPAddress']

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:06:41,801 WARNING  lbrynet.daemon.Components:711: upnp discovery failed: M-SEARCH for 192.168.1.1:1900 timed out

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:09:17,349 ERROR    asyncio:1266: Task exception was never retrieved
  future: <Task finished coro=<Gateway._discover_gateway() done, defined at aioupnp/gateway.py:158> exception=UPnPError('M-SEARCH for 192.168.1.1:1900 timed out',)>
  Traceback (most recent call last):
    File "aioupnp/gateway.py", line 171, in _discover_gateway
    File "asyncio/tasks.py", line 358, in wait_for
    File "aioupnp/protocols/ssdp.py", line 173, in fuzzy_m_search
    File "aioupnp/protocols/ssdp.py", line 166, in _fuzzy_m_search
  aioupnp.fault.UPnPError: M-SEARCH for 192.168.1.1:1900 timed out

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:12:26,728 WARNING  aioupnp.gateway:186: found gateway UNKNOWN GATEWAY at b'http://192.168.1.1:1990/WFADevice.xml', but it does not implement required soap commands: ['AddPortMapping', 'DeletePortMapping', 'GetExternalIPAddress']

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:12:26,735 WARNING  aioupnp.gateway:186: found gateway UNKNOWN GATEWAY at b'http://192.168.1.1:1990/WFADevice.xml', but it does not implement required soap commands: ['AddPortMapping', 'DeletePortMapping', 'GetExternalIPAddress']

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:12:41,799 WARNING  lbrynet.daemon.Components:711: upnp discovery failed: M-SEARCH for 192.168.1.1:1900 timed out

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:12:44,083 ERROR    asyncio:1266: Task exception was never retrieved
  future: <Task finished coro=<Gateway._discover_gateway() done, defined at aioupnp/gateway.py:158> exception=UPnPError('M-SEARCH for 192.168.1.1:1900 timed out',)>
  Traceback (most recent call last):
    File "aioupnp/gateway.py", line 171, in _discover_gateway
    File "asyncio/tasks.py", line 358, in wait_for
    File "aioupnp/protocols/ssdp.py", line 173, in fuzzy_m_search
    File "aioupnp/protocols/ssdp.py", line 166, in _fuzzy_m_search
  aioupnp.fault.UPnPError: M-SEARCH for 192.168.1.1:1900 timed out

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:18:26,732 WARNING  aioupnp.gateway:186: found gateway UNKNOWN GATEWAY at b'http://192.168.1.1:1990/WFADevice.xml', but it does not implement required soap commands: ['AddPortMapping', 'DeletePortMapping', 'GetExternalIPAddress']

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:18:26,738 WARNING  aioupnp.gateway:186: found gateway UNKNOWN GATEWAY at b'http://192.168.1.1:1990/WFADevice.xml', but it does not implement required soap commands: ['AddPortMapping', 'DeletePortMapping', 'GetExternalIPAddress']

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:18:41,787 WARNING  lbrynet.daemon.Components:711: upnp discovery failed: M-SEARCH for 192.168.1.1:1900 timed out

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:23:30,332 INFO     lbrynet.daemon.Daemon:832: Get version info: {"processor": "i386", "python_version": "3.6.5", "platform": "Darwin-17.4.0-x86_64-i386-64bit", "os_release": "17.4.0", "os_system": "Darwin", "lbrynet_version": "0.30.0", "lbryschema_version": "0.0.16", "build": "release", "ip": "73.215.186.214"}

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:23:30,566 INFO     lbrynet.daemon.Daemon:832: Get version info: {"processor": "i386", "python_version": "3.6.5", "platform": "Darwin-17.4.0-x86_64-i386-64bit", "os_release": "17.4.0", "os_system": "Darwin", "lbrynet_version": "0.30.0", "lbryschema_version": "0.0.16", "build": "release", "ip": "73.215.186.214"}

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:23:45,442 INFO     lbrynet.daemon.Daemon:832: Get version info: {"processor": "i386", "python_version": "3.6.5", "platform": "Darwin-17.4.0-x86_64-i386-64bit", "os_release": "17.4.0", "os_system": "Darwin", "lbrynet_version": "0.30.0", "lbryschema_version": "0.0.16", "build": "release", "ip": "73.215.186.214"}

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:23:45,664 INFO     lbrynet.daemon.Daemon:832: Get version info: {"processor": "i386", "python_version": "3.6.5", "platform": "Darwin-17.4.0-x86_64-i386-64bit", "os_release": "17.4.0", "os_system": "Darwin", "lbrynet_version": "0.30.0", "lbryschema_version": "0.0.16", "build": "release", "ip": "73.215.186.214"}

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:24:26,728 WARNING  aioupnp.gateway:186: found gateway UNKNOWN GATEWAY at b'http://192.168.1.1:1990/WFADevice.xml', but it does not implement required soap commands: ['AddPortMapping', 'DeletePortMapping', 'GetExternalIPAddress']

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:24:26,733 WARNING  aioupnp.gateway:186: found gateway UNKNOWN GATEWAY at b'http://192.168.1.1:1990/WFADevice.xml', but it does not implement required soap commands: ['AddPortMapping', 'DeletePortMapping', 'GetExternalIPAddress']

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:24:41,802 WARNING  lbrynet.daemon.Components:711: upnp discovery failed: M-SEARCH for 192.168.1.1:1900 timed out

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:24:43,687 ERROR    asyncio:1266: Task exception was never retrieved
  future: <Task finished coro=<Gateway._discover_gateway() done, defined at aioupnp/gateway.py:158> exception=UPnPError('M-SEARCH for 192.168.1.1:1900 timed out',)>
  Traceback (most recent call last):
    File "aioupnp/gateway.py", line 171, in _discover_gateway
    File "asyncio/tasks.py", line 358, in wait_for
    File "aioupnp/protocols/ssdp.py", line 173, in fuzzy_m_search
    File "aioupnp/protocols/ssdp.py", line 166, in _fuzzy_m_search
  aioupnp.fault.UPnPError: M-SEARCH for 192.168.1.1:1900 timed out

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:25:23,151 ERROR    asyncio:1266: Task exception was never retrieved
  future: <Task finished coro=<Gateway._discover_gateway() done, defined at aioupnp/gateway.py:158> exception=UPnPError('M-SEARCH for 192.168.1.1:1900 timed out',)>
  Traceback (most recent call last):
    File "aioupnp/gateway.py", line 171, in _discover_gateway
    File "asyncio/tasks.py", line 358, in wait_for
    File "aioupnp/protocols/ssdp.py", line 173, in fuzzy_m_search
    File "aioupnp/protocols/ssdp.py", line 166, in _fuzzy_m_search
  aioupnp.fault.UPnPError: M-SEARCH for 192.168.1.1:1900 timed out

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:30:26,731 WARNING  aioupnp.gateway:186: found gateway UNKNOWN GATEWAY at b'http://192.168.1.1:1990/WFADevice.xml', but it does not implement required soap commands: ['AddPortMapping', 'DeletePortMapping', 'GetExternalIPAddress']

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:30:26,738 WARNING  aioupnp.gateway:186: found gateway UNKNOWN GATEWAY at b'http://192.168.1.1:1990/WFADevice.xml', but it does not implement required soap commands: ['AddPortMapping', 'DeletePortMapping', 'GetExternalIPAddress']

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:30:41,801 WARNING  lbrynet.daemon.Components:711: upnp discovery failed: M-SEARCH for 192.168.1.1:1900 timed out

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:33:36,442 ERROR    asyncio:1266: Task exception was never retrieved
  future: <Task finished coro=<Gateway._discover_gateway() done, defined at aioupnp/gateway.py:158> exception=UPnPError('M-SEARCH for 192.168.1.1:1900 timed out',)>
  Traceback (most recent call last):
    File "aioupnp/gateway.py", line 171, in _discover_gateway
    File "asyncio/tasks.py", line 358, in wait_for
    File "aioupnp/protocols/ssdp.py", line 173, in fuzzy_m_search
    File "aioupnp/protocols/ssdp.py", line 166, in _fuzzy_m_search
  aioupnp.fault.UPnPError: M-SEARCH for 192.168.1.1:1900 timed out

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:36:26,729 WARNING  aioupnp.gateway:186: found gateway UNKNOWN GATEWAY at b'http://192.168.1.1:1990/WFADevice.xml', but it does not implement required soap commands: ['AddPortMapping', 'DeletePortMapping', 'GetExternalIPAddress']

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:36:26,733 WARNING  aioupnp.gateway:186: found gateway UNKNOWN GATEWAY at b'http://192.168.1.1:1990/WFADevice.xml', but it does not implement required soap commands: ['AddPortMapping', 'DeletePortMapping', 'GetExternalIPAddress']

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:36:41,784 WARNING  lbrynet.daemon.Components:711: upnp discovery failed: M-SEARCH for 192.168.1.1:1900 timed out

┗ ----------------------------
^C
MacBook-Pro:lbry-desktop Mark$ yarn dev
yarn run v1.12.1
$ electron-webpack dev
┏ Main -----------------------

  Hash: 8dfd53653c3a4320e4dd
  Version: webpack 3.12.0
  Time: 659ms
    Asset    Size  Chunks             Chunk Names
  main.js  130 kB       0  [emitted]  main
     [0] multi ./node_modules/electron-webpack/out/electron-main-hmr/main-hmr ./src/main/index.js 40 bytes {0} [built]
  [./node_modules/devtron/api.js] ./node_modules/devtron/api.js 1.26 kB {0} [built]
  [./node_modules/electron-webpack/out/electron-main-hmr/main-hmr.js] ./node_modules/electron-webpack/out/electron-main-hmr/main-hmr.js 559 bytes {0} [built]
  [./package.json] ./package.json 3.73 kB {0} [built]
  [./src/main/Daemon.js] ./src/main/Daemon.js 1.21 kB {0} [built]
  [./src/main/createTray.js] ./src/main/createTray.js 858 bytes {0} [built]
  [./src/main/createWindow.js] ./src/main/createWindow.js 3.92 kB {0} [built]
  [./src/main/index.js] ./src/main/index.js 10.2 kB {0} [built]
  [electron] external "electron" 42 bytes {0} [not cacheable]
  [electron-devtools-installer] external "electron-devtools-installer" 42 bytes {0} [not cacheable]
  [electron-is-dev] external "electron-is-dev" 42 bytes {0} [not cacheable]
  [electron-updater] external "electron-updater" 42 bytes {0} [not cacheable]
  [electron-webpack/out/electron-main-hmr/HmrClient] external "electron-webpack/out/electron-main-hmr/HmrClient" 42 bytes {0} [not cacheable]
  [find-process] external "find-process" 42 bytes {0} [not cacheable]
  [https] external "https" 42 bytes {0} [not cacheable]
      + 8 hidden modules

┗ ----------------------------
┏ Renderer -------------------

  Content not from webpack is served from /Users/Mark/WebstormProjects/lbry-desktop/static, /Users/Mark/WebstormProjects/lbry-desktop/dist/renderer-dll

┗ ----------------------------
┏ Renderer -------------------

  Hash: a7e19ec58b5ceff8677e
  Version: webpack 3.12.0
  Time: 24559ms
                            Asset       Size  Chunks                    Chunk Names
            fonts/400--inter.woff     199 kB          [emitted]         
           fonts/400--inter.woff2     148 kB          [emitted]         
           fonts/400i--inter.woff     208 kB          [emitted]         
          fonts/400i--inter.woff2     156 kB          [emitted]         
            fonts/500--inter.woff     210 kB          [emitted]         
           fonts/500--inter.woff2     157 kB          [emitted]         
           fonts/500i--inter.woff     218 kB          [emitted]         
          fonts/500i--inter.woff2     164 kB          [emitted]         
            fonts/600--inter.woff     211 kB          [emitted]         
           fonts/600--inter.woff2     159 kB          [emitted]         
           fonts/600i--inter.woff     218 kB          [emitted]         
          fonts/600i--inter.woff2     164 kB          [emitted]         
            fonts/700--inter.woff     213 kB          [emitted]         
           fonts/700--inter.woff2     160 kB          [emitted]         
           fonts/700i--inter.woff     220 kB          [emitted]         
          fonts/700i--inter.woff2     165 kB          [emitted]         
            fonts/800--inter.woff     217 kB          [emitted]         
           fonts/800--inter.woff2     163 kB          [emitted]         
           fonts/800i--inter.woff     224 kB          [emitted]         
          fonts/800i--inter.woff2     168 kB          [emitted]         
            fonts/900--inter.woff     214 kB          [emitted]         
           fonts/900--inter.woff2     161 kB          [emitted]         
           fonts/900i--inter.woff     220 kB          [emitted]         
          fonts/900i--inter.woff2     165 kB          [emitted]         
      fonts/variable--inter.woff2     269 kB          [emitted]  [big]  
  imgs/stripe-background--img.png    23.2 kB          [emitted]         
                      renderer.js    7.41 MB       0  [emitted]  [big]  renderer
                       styles.css    69.4 kB       0  [emitted]         renderer
                       index.html  427 bytes          [emitted]         
     [0] multi (webpack)-dev-server/client?http://localhost:62961 webpack/hot/dev-server ./src/renderer/index.js 52 bytes {0} [built]
  [./node_modules/loglevel/lib/loglevel.js] ./node_modules/loglevel/lib/loglevel.js 8.66 kB {0} [built]
  [./node_modules/strip-ansi/index.js] ./node_modules/strip-ansi/index.js 161 bytes {0} [built]
  [./node_modules/webpack-dev-server/client/index.js?http://localhost:62961] (webpack)-dev-server/client?http://localhost:62961 7.93 kB {0} [built]
  [./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.67 kB {0} [built]
  [./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.08 kB {0} [built]
  [./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.59 kB {0} [built]
  [./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 89 bytes {0} [built]
  [./node_modules/webpack/hot/log.js] (webpack)/hot/log.js 1.01 kB {0} [built]
  [./package.json] ./package.json 3.73 kB {0} [built]
  [./src/renderer/analytics.js] ./src/renderer/analytics.js 1.83 kB {0} [built]
  [./src/renderer/app.js] ./src/renderer/app.js 1.53 kB {0} [built]
  [./src/renderer/constants/action_types.js] ./src/renderer/constants/action_types.js 14.7 kB {0} [built]
  [./src/renderer/index.js] ./src/renderer/index.js 8.08 kB {0} [built]
  [./src/renderer/redux/actions/app.js] ./src/renderer/redux/actions/app.js 11.7 kB {0} [built]
      + 453 hidden modules
  Child html-webpack-plugin for "index.html":
       1 asset
      [./node_modules/html-loader/index.js?minimize=false!../../../../__virtual__/renderer-index.html] ./node_modules/html-loader?minimize=false!/__virtual__/renderer-index.html 374 bytes {0} [built]
  Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/simplemde/dist/simplemde.min.css:
      [./node_modules/css-loader/index.js!./node_modules/simplemde/dist/simplemde.min.css] ./node_modules/css-loader!./node_modules/simplemde/dist/simplemde.min.css 11.1 kB {0} [built]
      [./node_modules/css-loader/lib/css-base.js] ./node_modules/css-loader/lib/css-base.js 2.28 kB {0} [built]
  Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/sass-loader/lib/loader.js!src/renderer/scss/all.scss:
       26 assets
      [./node_modules/css-loader/index.js!./node_modules/sass-loader/lib/loader.js!./src/renderer/scss/all.scss] ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/renderer/scss/all.scss 61.1 kB {0} [built]
      [./node_modules/css-loader/lib/css-base.js] ./node_modules/css-loader/lib/css-base.js 2.28 kB {0} [built]
      [./node_modules/css-loader/lib/url/escape.js] ./node_modules/css-loader/lib/url/escape.js 466 bytes {0} [built]
      [./static/font/inter/400.woff] ./static/font/inter/400.woff 67 bytes {0} [built]
      [./static/font/inter/400.woff2] ./static/font/inter/400.woff2 68 bytes {0} [built]
      [./static/font/inter/400i.woff] ./static/font

┗ ----------------------------
┏ Renderer -------------------

  /inter/400i.woff 68 bytes {0} [built]
      [./static/font/inter/400i.woff2] ./static/font/inter/400i.woff2 69 bytes {0} [built]
      [./static/font/inter/500.woff] ./static/font/inter/500.woff 67 bytes {0} [built]
      [./static/font/inter/500.woff2] ./static/font/inter/500.woff2 68 bytes {0} [built]
      [./static/font/inter/500i.woff] ./static/font/inter/500i.woff 68 bytes {0} [built]
      [./static/font/inter/500i.woff2] ./static/font/inter/500i.woff2 69 bytes {0} [built]
      [./static/font/inter/600.woff] ./static/font/inter/600.woff 67 bytes {0} [built]
      [./static/font/inter/600.woff2] ./static/font/inter/600.woff2 68 bytes {0} [built]
      [./static/font/inter/600i.woff] ./static/font/inter/600i.woff 68 bytes {0} [built]
      [./static/font/inter/600i.woff2] ./static/font/inter/600i.woff2 69 bytes {0} [built]
          + 15 hidden modules

┗ ----------------------------
┏ Renderer -------------------

  Initial scan complete. Ready for changes

┗ ----------------------------
┏ Electron -------------------

  Debugger listening on ws://127.0.0.1:5858/2ecb6b8b-561a-47f8-be11-0ac78b44e9f7
  For help see https://nodejs.org/en/docs/inspector

┗ ----------------------------
┏ Electron -------------------

  Installing Devtron from node_modules/devtron

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:38:04,501 INFO     lbrynet.daemon.DaemonControl:67: Starting lbrynet-daemon from command line

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:38:05,383 INFO     lbrynet.daemon.auth.factory:48: Using non-authenticated API

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:38:05,383 INFO     lbrynet.daemon.auth.server:223: Not using SSL

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:38:05,388 INFO     lbrynet.daemon.auth.server:227: lbrynet API listening on TCP localhost:5279

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:38:05,389 INFO     lbrynet.daemon.Daemon:279: Starting lbrynet-daemon

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:38:05,496 INFO     lbrynet.daemon.Daemon:280: Platform: {"processor": "i386", "python_version": "3.6.5", "platform": "Darwin-17.4.0-x86_64-i386-64bit", "os_release": "17.4.0", "os_system": "Darwin", "lbrynet_version": "0.30.0", "lbryschema_version": "0.0.16", "build": "release", "ip": "73.215.186.214"}

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:38:05,562 INFO     lbrynet.daemon.Components:134: Loading databases

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:38:05,563 INFO     lbrynet.database.storage:176: connecting to database: /Users/Mark/Library/Application Support/LBRY/lbrynet.sqlite

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:38:05,564 INFO     lbrynet.daemon.ExchangeRateManager:212: Starting exchange rate manager

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:38:05,617 INFO     lbrynet.core.RateLimiter:70: Starting rate limiter.

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:38:06,052 WARNING  aioupnp.gateway:186: found gateway UNKNOWN GATEWAY at b'http://192.168.1.1:1990/WFADevice.xml', but it does not implement required soap commands: ['AddPortMapping', 'DeletePortMapping', 'GetExternalIPAddress']

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:38:06,068 WARNING  aioupnp.gateway:186: found gateway UNKNOWN GATEWAY at b'http://192.168.1.1:1990/WFADevice.xml', but it does not implement required soap commands: ['AddPortMapping', 'DeletePortMapping', 'GetExternalIPAddress']

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:38:06,300 INFO     lbrynet.daemon.Daemon:832: Get version info: {"processor": "i386", "python_version": "3.6.5", "platform": "Darwin-17.4.0-x86_64-i386-64bit", "os_release": "17.4.0", "os_system": "Darwin", "lbrynet_version": "0.30.0", "lbryschema_version": "0.0.16", "build": "release", "ip": "73.215.186.214"}

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:38:06,543 INFO     lbrynet.daemon.Daemon:832: Get version info: {"processor": "i386", "python_version": "3.6.5", "platform": "Darwin-17.4.0-x86_64-i386-64bit", "os_release": "17.4.0", "os_system": "Darwin", "lbrynet_version": "0.30.0", "lbryschema_version": "0.0.16", "build": "release", "ip": "73.215.186.214"}

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:38:07,788 INFO     torba.basenetwork:62: Successfully connected to SPV wallet server: lbryumx1.lbry.io:50001

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:38:08,199 INFO     lbrynet.daemon.Components:269: remote height: 464767, local height: 464755

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:38:21,147 WARNING  lbrynet.daemon.Components:711: upnp discovery failed: M-SEARCH for 192.168.1.1:1900 timed out

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:38:21,151 ERROR    lbrynet.daemon.Components:781: failed to setup upnp

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:38:21,176 INFO     lbrynet.dht.protocol:189: DHT listening on UDP 4444 (ext port 4444)

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:38:21,181 INFO     lbrynet.daemon.Components:440: Started the dht

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:38:21,183 INFO     lbrynet.daemon.Components:353: Starting torba wallet

┗ ----------------------------
┏ Electron -------------------

  Daemon: Unhandled error in Deferred:

┗ ----------------------------
┏ Electron -------------------

  Daemon:

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:38:21,280 CRITICAL twisted:154: Unhandled error in Deferred:

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:38:21,280 CRITICAL twisted:154: 
  Traceback (most recent call last):
    File "twisted/internet/defer.py", line 1416, in _inlineCallbacks
    File "twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
  StopIteration
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "twisted/internet/defer.py", line 1418, in _inlineCallbacks
    File "lbrynet/core/log_support.py", line 33, in _emit
    File "treq/api.py", line 33, in post
    File "treq/client.py", line 130, in post
    File "treq/client.py", line 207, in request
  TypeError: ('Could not adapt', '{"loggerName": "lbrynet.daemon.Components", "asciTime": "2018-11-05 13:38:21,151", "fileName": "Components.py", "functionName": "start", "levelNo": 40, "lineNo": 781, "levelName": "ERROR", "message": "failed to setup upnp", "level": 40, "installation_id": "6RnbZfWSDW37FngTBaCdmRApiKo4eLJjRYQUt9y3r29YnM31bw58j5kPxbYjDEzJoE", "session_id": "2gKNaE9V1cJLuuEL9H7sisP1Ab73kS3FBWoZcBg3Zzq5hxLdDP2EurtqQnpVu1Y1bZ"}', <InterfaceClass twisted.web.iweb.IBodyProducer>)

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:38:21,284 INFO     torba.basedatabase:164: connecting to database: /Users/Mark/.lbryum/lbc_mainnet/blockchain.db

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:38:21,335 INFO     lbrynet.dht.node:239: Attempting to join the DHT network, 0 contacts known so far

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:38:32,672 INFO     torba.basenetwork:62: Successfully connected to SPV wallet server: lbryumx1.lbry.io:50001

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:38:32,673 INFO     torba.baseledger:215: Subscribing and updating accounts.

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:38:33,104 INFO     torba.baseledger:101: lbc_mainnet: added BlockHeightEvent(height=464767, change=12) header blocks, final height 464767

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:38:33,934 ERROR    lbrynet.daemon.Component:61: Error setting up wallet
  Traceback (most recent call last):
    File "lbrynet/daemon/Component.py", line 55, in _setup
    File "twisted/internet/defer.py", line 1416, in _inlineCallbacks
    File "twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    File "lbrynet/daemon/Components.py", line 358, in start
    File "twisted/internet/defer.py", line 824, in adapt
    File "torba/basemanager.py", line 73, in start
    File "lbrynet/wallet/ledger.py", line 77, in start
    File "torba/baseledger.py", line 211, in start
    File "torba/baseledger.py", line 218, in join_network
    File "torba/baseledger.py", line 305, in update_accounts
    File "torba/baseledger.py", line 312, in update_account
    File "torba/baseledger.py", line 379, in subscribe_history
    File "torba/baseledger.py", line 345, in update_history
    File "torba/basedatabase.py", line 419, in get_transaction
    File "torba/basedatabase.py", line 368, in get_transactions
    File "torba/basedatabase.py", line 359, in select_transactions
    File "concurrent/futures/thread.py", line 56, in run
    File "torba/basedatabase.py", line 45, in __fetchall
  sqlite3.OperationalError: no such column: position

┗ ----------------------------
┏ Electron -------------------

  Daemon: Unhandled error in Deferred:

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:38:33,937 CRITICAL twisted:154: Unhandled error in Deferred:

┗ ----------------------------
┏ Electron -------------------

  Daemon: 2018-11-05 13:38:33,938 CRITICAL twisted:154: 
  sqlite3.OperationalError: no such column: position
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "twisted/internet/defer.py", line 1418, in _inlineCallbacks
    File "lbrynet/core/log_support.py", line 33, in _emit
    File "treq/api.py", line 33, in post
    File "treq/client.py", line 130, in post
    File "treq/client.py", line 207, in request
  TypeError: ('Could not adapt', '{"loggerName": "lbrynet.daemon.Component", "asciTime": "2018-11-05 13:38:33,934", "fileName": "Component.py", "functionName": "_setup", "levelNo": 40, "lineNo": 61, "levelName": "ERROR", "message": "Error setting up wallet", "level": 40, "installation_id": "6RnbZfWSDW37FngTBaCdmRApiKo4eLJjRYQUt9y3r29YnM31bw58j5kPxbYjDEzJoE", "session_id": "2gKNaE9V1cJLuuEL9H7sisP1Ab73kS3FBWoZcBg3Zzq5hxLdDP2EurtqQnpVu1Y1bZ", "exc_info": "Traceback (most recent call last):\\n  File \\"lbrynet/daemon/Component.py\\", line 55, in _setup\\n  File \\"twisted/internet/defer.py\\", line 1416, in _inlineCallbacks\\n  File \\"twisted/python/failure.py\\", line 491, in throwExceptionIntoGenerator\\n  File \\"lbrynet/daemon/Components.py\\", line 358, in start\\n  File \\"twisted/internet/defer.py\\", line 824, in adapt\\n  File \\"torba/basemanager.py\\", line 73, in start\\n  File \\"lbrynet/wallet/ledger.py\\", line 77, in start\\n  File \\"torba/baseledger.py\\", line 211, in start\\n  File \\"torba/baseledger.py\\", line 218, in join_network\\n  File \\"torba/baseledger.py\\", line 305, in update_accounts\\n  File \\"torba/baseledger.py\\", line 312, in update_account\\n  File \\"torba/baseledger.py\\", line 379, in subscribe_history\\n  File \\"torba/baseledger.py\\", line 345, in update_history\\n  File \\"torba/basedatabase.py\\", line 419, in get_transaction\\n  File \\"torba/basedatabase.py\\", line 368, in get_transactions\\n  File \\"torba/basedatabase.py\\", line 359, in select_transactions\\n  File \\"concurrent/futures/thread.py\\", line 56, in run\\n  File \\"torba/basedatabase.py\\", line 45, in __fetchall\\nsqlite3.OperationalError: no such column: position"}', <InterfaceClass twisted.web.iweb.IBodyProducer>)

```

**Comment by tiger5226** [comment]
this is from having an older blockchain.db file. Once that is removed, it allows the app to start up. 

@eukreign - Not sure if this should be addressed in the daemon or not as a normal user would not know to do this.

**Comment by eukreign** [comment]
Glad your issue was solved by just deleting `blockchain.db`! Normal users wouldn't have run the unreleased version of the daemon so this isn't a problem for them; for going between released versions we have a migration path.
