### ISSUE TITLE
Downloading from http mirror fails

### ISSUE THREAD

**Issue by nikooo777** [lbryio/lbry#1614]
## The Issue

Downloading from the http mirror fails

### Steps to reproduce
1. Start the daemon
2. Download something that is available
3. ...

### Expected behaviour
The daemon downloads the blobs from the http mirror

### Actual behaviour
Blobs fail to download:\
```
2018-11-07 15:08:31,148 ERROR    lbrynet.p2p.HTTPBlobDownloader:145: Mirror failed downloading
Traceback (most recent call last):
  File "lbrynet/p2p/HTTPBlobDownloader.py", line 127, in _download_blob
TypeError: object of type 'bool' has no len()
```

## System Configuration

```
{
  "id": null,
  "jsonrpc": "2.0",
  "result": {
    "build": "qa",
    "desktop": "Unknown",
    "distro": {
      "codename": "stretch",
      "id": "debian",
      "like": "",
      "version": "9",
      "version_parts": {
        "build_number": "",
        "major": "9",
        "minor": ""
      }
    },
    "ip": "***.***.194.134",
    "lbrynet_version": "0.30.1rc1",
    "lbryschema_version": "0.0.16",
    "os_release": "4.9.33-mod-std-ipv6-64",
    "os_system": "Linux",
    "platform": "Linux-4.9.33-mod-std-ipv6-64-x86_64-with-debian-9.5",
    "processor": "",
    "python_version": "3.6.7"
  }
}
```

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by nikooo777** [comment]
this is still happening btw.

```
2018-12-28 13:49:19,052 ERROR    lbrynet.p2p.HTTPBlobDownloader:146: Mirror failed downloading
Traceback (most recent call last):
  File "lbrynet/p2p/HTTPBlobDownloader.py", line 128, in _download_blob
TypeError: object of type 'bool' has no len()
```

```
{
  "id": null,
  "jsonrpc": "2.0",
  "result": {
    "build": "release",
    "desktop": "Unknown",
    "distro": {
      "codename": "stretch",
      "id": "debian",
      "like": "",
      "version": "9",
      "version_parts": {
        "build_number": "",
        "major": "9",
        "minor": ""
      }
    },
    "lbrynet_version": "0.30.3",
    "lbryschema_version": "0.0.16",
    "os_release": "4.9.33-mod-std-ipv6-64",
    "os_system": "Linux",
    "platform": "Linux-4.9.33-mod-std-ipv6-64-x86_64-with-debian-9.5",
    "processor": "",
    "python_version": "3.7.1"
  }
}
```
