### ISSUE TITLE
Improve timeout when spv server fails to connect

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1631]
## The Issue
With lbryumx1 down, the daemon starts up, tries to connect but the timeout takes a while before switching over to lbryumx2. 

```
2018-11-12 09:35:38,535 INFO     lbrynet.daemon.Components:724: got external ip: 73.60.45.79
2018-11-12 09:37:47,196 ERROR    torba.basenetwork:67: Connecting to lbryumx1.lbry.io:50001 raised an exception:
Traceback (most recent call last):
  File "site-packages/torba/basenetwork.py", line 60, in start
  File "site-packages/aiorpcx/session.py", line 421, in create_connection
  File "asyncio/base_events.py", line 777, in create_connection
  File "asyncio/base_events.py", line 764, in create_connection
  File "asyncio/selector_events.py", line 451, in sock_connect
  File "asyncio/selector_events.py", line 481, in _sock_connect_cb
TimeoutError: [Errno 110] Connect call failed ('18.207.15.66', 50001)
2018-11-12 09:37:51,331 INFO     torba.basenetwork:62: Successfully connected to SPV wallet server: lbryumx2.lbry.io:50001
2018-11-12 09:37:51,498 INFO     lbrynet.daemon.Components:270: remote height: 468482, local height: 467098
```

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by eukreign** [comment]
@shyba was this fixed?

**Comment by tzarebczan** [comment]
Fixed and tested in https://github.com/lbryio/torba/pull/68
