### ISSUE TITLE
"too many SQL variables" when sending large transactions

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1720]
## The Issue
We've run into this in other scenarios on Windows, but now it happens when sending a large transaction (many inputs). 
```
2018-12-18 00:20:30,023 ERROR    root:506: Failed to create transaction:
Traceback (most recent call last):
  File "torba\client\basetransaction.py", line 468, in create
  File "torba\client\baseledger.py", line 220, in get_spendable_utxos
  File "torba\client\basedatabase.py", line 327, in reserve_outputs
  File "concurrent\futures\thread.py", line 57, in run
  File "torba\client\basedatabase.py", line 57, in __run_transaction
  File "torba\client\basedatabase.py", line 49, in <lambda>
sqlite3.OperationalError: too many SQL variables
2018-12-18 00:20:30,028 WARNING  lbrynet.extras.daemon.auth.server:325: error processing api request: too many SQL variables
traceback:   File "twisted\internet\defer.py", line 654, in _runCallbacks
    
  File "lbrynet\extras\daemon\auth\server.py", line 96, in trap
    
  File "twisted\python\failure.py", line 439, in trap
    
  File "twisted\python\failure.py", line 467, in raiseException
    
  File "twisted\internet\defer.py", line 824, in adapt
    
  File "lbrynet\extras\daemon\Daemon.py", line 1095, in jsonrpc_wallet_send
    
  File "lbrynet\extras\wallet\manager.py", line 239, in send_amount_to_address
    
  File "torba\client\basetransaction.py", line 508, in create
    
  File "torba\client\basetransaction.py", line 468, in create
    
  File "torba\client\baseledger.py", line 220, in get_spendable_utxos
    
  File "torba\client\basedatabase.py", line 327, in reserve_outputs
    
  File "concurrent\futures\thread.py", line 57, in run
    
  File "torba\client\basedatabase.py", line 57, in __run_transaction
    
  File "torba\client\basedatabase.py", line 49, in <lambda>
    
sqlite3.OperationalError: too many SQL variables
```

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by eukreign** [comment]
@shyba was this solved in the wallet?
