### ISSUE TITLE
IOError("unknown blob length") / 'NoneType' object has no attribute 'get_length'

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1771]
## The Issue
Seems to happen when requesting from peers on my own network:
```
2019-01-15 00:18:34,140 INFO     lbrynet.peer:253: download blob from 24.184.108.248:3333
Fatal error: protocol.data_received() call failed.
protocol: <lbrynet.blob_exchange.client.BlobExchangeClientProtocol object at 0x06E672B0>
transport: <_SelectorSocketTransport fd=6880 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "c:\users\thoma\appdata\local\programs\python\python37-32\lib\asyncio\selector_events.py", line 824, in _read_ready__data_received
    self._protocol.data_received(data)
  File "c:\users\thoma\lbry\lbrynet\blob_exchange\client.py", line 61, in data_received
    return self.handle_data_received(data)
  File "c:\users\thoma\lbry\lbrynet\blob_exchange\client.py", line 51, in handle_data_received
    self.writer.write(response.blob_data)
  File "c:\users\thoma\lbry\lbrynet\blob\writer.py", line 41, in write
    raise IOError("unknown blob length")
OSError: unknown blob length
2019-01-15 00:18:34,141 INFO     lbrynet.blob_exchange.client:162: connection lost to c72ec927 @ 24.184.108.248 udp:56452/tcp:3333 (reason: unknown blob length)
```

```Fatal error: protocol.data_received() call failed.
protocol: <lbrynet.blob_exchange.client.BlobExchangeClientProtocol object at 0x08F5F750>
transport: <_SelectorSocketTransport fd=5164 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\selector_events.py", line 824, in _read_ready__data_received
    self._protocol.data_received(data)
  File "c:\users\thoma\lbry\lbrynet\blob_exchange\client.py", line 61, in data_received
    return self.handle_data_received(data)
  File "c:\users\thoma\lbry\lbrynet\blob_exchange\client.py", line 51, in handle_data_received
    self.writer.write(response.blob_data)
  File "c:\users\thoma\lbry\lbrynet\blob\writer.py", line 41, in write
    raise IOError("unknown blob length")
OSError: unknown blob length
Fatal error: protocol.data_received() call failed.
protocol: <lbrynet.blob_exchange.client.BlobExchangeClientProtocol object at 0x08F5F750>
transport: <_SelectorSocketTransport fd=4852 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\selector_events.py", line 824, in _read_ready__data_received
    self._protocol.data_received(data)
  File "c:\users\thoma\lbry\lbrynet\blob_exchange\client.py", line 55, in data_received
    expected_length = self.blob.get_length()
AttributeError: 'NoneType' object has no attribute 'get_length'
2/110 - 1.246556282043457 comedians-canaries-and-coalmines#17334147b0100f6892f60015893cd8ae1df8c9ab
```

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Also: NoneType' object has no attribute 'blob_hash

```11/110 - 6.104256868362427 top-5-worst-anime-of-2018#b0dc564e7749dc9b75f4bf6a4107f6d40aed4760
Task exception was never retrieved
future: <Task finished coro=<StreamDownloader._request_blob() done, defined at c:\users\thoma\lbry\lbrynet\stream\downloader.py:98> exception=AttributeError("'NoneType' object has no attribute 'blob_hash'") created at c:\users\thoma\lbry\lbrynet\stream\downloader.py:130>
source_traceback: Object created at (most recent call last):
  File "scripts\time_to_first_byte.py", line 171, in <module>
    asyncio.run(main())
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 555, in run_until_complete
    self.run_forever()
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 523, in run_forever
    self._run_once()
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 1750, in _run_once
    handle._run()
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "c:\users\thoma\lbry\lbrynet\stream\downloader.py", line 264, in _download
    await self.assemble_decrypted_stream(self.output_dir, self.output_file_name)
  File "c:\users\thoma\lbry\lbrynet\stream\assembler.py", line 85, in assemble_decrypted_stream
    blob = await self.get_blob(blob_info.blob_hash, blob_info.length)
  File "c:\users\thoma\lbry\lbrynet\stream\downloader.py", line 163, in get_blob
    await self._update_current_blob(blob)
  File "c:\users\thoma\lbry\lbrynet\stream\downloader.py", line 96, in _update_current_blob
    self._update_requests()
  File "c:\users\thoma\lbry\lbrynet\stream\downloader.py", line 130, in _update_requests
    task = self.loop.create_task(self._request_blob(peer))
Traceback (most recent call last):
  File "c:\users\thoma\lbry\lbrynet\blob_exchange\client.py", line 67, in _download_blob
    response: BlobResponse = await asyncio.wait_for(self._response_fut, self.peer_timeout, loop=self.loop)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\tasks.py", line 412, in wait_for
    return fut.result()
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\thoma\lbry\lbrynet\stream\downloader.py", line 108, in _request_blob
    peer.address, peer.tcp_port, self.peer_connect_timeout)
  File "c:\users\thoma\lbry\lbrynet\blob_exchange\client.py", line 179, in request_blob
    success = await protocol.download_blob(blob)
  File "c:\users\thoma\lbry\lbrynet\blob_exchange\client.py", line 134, in download_blob
    return await self._download_blob()
  File "c:\users\thoma\lbry\lbrynet\blob_exchange\client.py", line 102, in _download_blob
    msg = f"download {self.blob.blob_hash[:8]} from {self.peer_address} cancelled"
AttributeError: 'NoneType' object has no attribute 'blob_hash'
Fatal error: protocol.data_received() call failed.
handle_traceback: Handle created at (most recent call last):
  File "scripts\time_to_first_byte.py", line 171, in <module>
    asyncio.run(main())
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 555, in run_until_complete
    self.run_forever()
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 523, in run_forever
    self._run_once()
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 1750, in _run_once
    handle._run()
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\selector_events.py", line 716, in _add_reader
    self._loop._add_reader(fd, callback, *args)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\selector_events.py", line 260, in _add_reader
    handle = events.Handle(callback, args, self, None)
protocol: <lbrynet.blob_exchange.client.BlobExchangeClientProtocol object at 0x0E9D7CF0>
transport: <_SelectorSocketTransport fd=1780 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\selector_events.py", line 824, in _read_ready__data_received
    self._protocol.data_received(data)
  File "c:\users\thoma\lbry\lbrynet\blob_exchange\client.py", line 52, in data_received
    expected_length = self.blob.get_length()
AttributeError: 'NoneType' object has no attribute 'get_length'```

**Comment by tzarebczan** [comment]
this is fixed in https://github.com/lbryio/lbry/commit/6207dac67b5716fbbec9905a71eea3f4ca6d7c6a
