### ISSUE TITLE
concurrent.futures._base.TimeoutError 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1779]
## The Issue
When starting up the latest async branch:
```
2019-01-16 17:39:45,686 WARNING  lbrynet.dht.protocol.protocol:203: 3.122.90.177:4444 replied, but after we cancelled the request attempt
Task exception was never retrieved
future: <Task finished coro=<Peer.ping() done, defined at c:\users\thoma\lbry\lbrynet\peer.py:194> exception=TimeoutError()>
Traceback (most recent call last):
  File "c:\users\thoma\lbry\lbrynet\peer.py", line 196, in ping
    return await self._send_kademlia_rpc(RequestDatagram.make_ping(self.peer_manager.dht_protocol.node_id))
  File "c:\users\thoma\lbry\lbrynet\peer.py", line 186, in _send_kademlia_rpc
    raise err
  File "c:\users\thoma\lbry\lbrynet\peer.py", line 176, in _send_kademlia_rpc
    result = await asyncio.wait_for(response_fut, conf.settings['node_rpc_timeout'], loop=self.loop)
  File "c:\users\thoma\appdata\local\programs\python\python37-32\lib\asyncio\tasks.py", line 419, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
Task exception was never retrieved
future: <Task finished coro=<Peer.ping() done, defined at c:\users\thoma\lbry\lbrynet\peer.py:194> exception=TimeoutError()>
Traceback (most recent call last):
  File "c:\users\thoma\lbry\lbrynet\peer.py", line 196, in ping
    return await self._send_kademlia_rpc(RequestDatagram.make_ping(self.peer_manager.dht_protocol.node_id))
  File "c:\users\thoma\lbry\lbrynet\peer.py", line 186, in _send_kademlia_rpc
    raise err
  File "c:\users\thoma\lbry\lbrynet\peer.py", line 176, in _send_kademlia_rpc
    result = await asyncio.wait_for(response_fut, conf.settings['node_rpc_timeout'], loop=self.loop)
  File "c:\users\thoma\appdata\local\programs\python\python37-32\lib\asyncio\tasks.py", line 419, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
Task exception was never retrieved
future: <Task finished coro=<Peer.ping() done, defined at c:\users\thoma\lbry\lbrynet\peer.py:194> exception=TimeoutError()>
Traceback (most recent call last):
  File "c:\users\thoma\lbry\lbrynet\peer.py", line 196, in ping
    return await self._send_kademlia_rpc(RequestDatagram.make_ping(self.peer_manager.dht_protocol.node_id))
  File "c:\users\thoma\lbry\lbrynet\peer.py", line 186, in _send_kademlia_rpc
    raise err
  File "c:\users\thoma\lbry\lbrynet\peer.py", line 176, in _send_kademlia_rpc
    result = await asyncio.wait_for(response_fut, conf.settings['node_rpc_timeout'], loop=self.loop)
  File "c:\users\thoma\appdata\local\programs\python\python37-32\lib\asyncio\tasks.py", line 419, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
```

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Doesn't seem to be occurring anymore, closing...
