### ISSUE TITLE
asyncio.base_futures.InvalidStateError: invalid state

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1782]
## The Issue
```Fatal error: protocol.data_received() call failed.
handle_traceback: Handle created at (most recent call last):
  File "scripts\time_to_first_byte.py", line 171, in <module>
    asyncio.run(main())
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 555, in run_until_complete
    self.run_forever()
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 523, in run_forever
    self._run_once()
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 1750, in _run_once
    handle._run()
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\selector_events.py", line 716, in _add_reader
    self._loop._add_reader(fd, callback, *args)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\selector_events.py", line 260, in _add_reader
    handle = events.Handle(callback, args, self, None)
protocol: <lbrynet.blob_exchange.client.BlobExchangeClientProtocol object at 0x0FBD5A30>
transport: <_SelectorSocketTransport fd=2748 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\selector_events.py", line 824, in _read_ready__data_received
    self._protocol.data_received(data)
  File "c:\users\thoma\lbry\lbrynet\blob_exchange\client.py", line 55, in data_received
    self.handle_data_received(data[:len(data) + self._blob_bytes_received - expected_length])
  File "c:\users\thoma\lbry\lbrynet\blob_exchange\client.py", line 45, in handle_data_received
    self._response_fut.set_result(response)
asyncio.base_futures.InvalidStateError: invalid state
```

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Fixed in https://github.com/lbryio/lbry/commit/6207dac67b5716fbbec9905a71eea3f4ca6d7c6a
