### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1783]
## The Issue

```Task exception was never retrieved
future: <Task finished coro=<MarketFeed._update_price() done, defined at c:\users\thoma\lbry\lbrynet\extras\daemon\exchange_rate_manager.py:77> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)') created at C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\tasks.py:321>
source_traceback: Object created at (most recent call last):
  File "scripts\time_to_first_byte.py", line 171, in <module>
    asyncio.run(main())
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 555, in run_until_complete
    self.run_forever()
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 523, in run_forever
    self._run_once()
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 1750, in _run_once
    handle._run()
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "c:\users\thoma\lbry\lbrynet\extras\daemon\ComponentManager.py", line 126, in _setup
    await component._setup()
  File "c:\users\thoma\lbry\lbrynet\extras\daemon\Component.py", line 54, in _setup
    result = await self.start()
  File "c:\users\thoma\lbry\lbrynet\extras\daemon\Components.py", line 657, in start
    self.exchange_rate_manager.start()
  File "c:\users\thoma\lbry\lbrynet\extras\daemon\exchange_rate_manager.py", line 213, in start
    feed.start()
  File "c:\users\thoma\lbry\lbrynet\extras\daemon\exchange_rate_manager.py", line 88, in start
    self._task = asyncio.create_task(self._update_price())
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\tasks.py", line 321, in create_task
    return loop.create_task(coro)
Traceback (most recent call last):
  File "c:\users\thoma\lbry\lbrynet\extras\daemon\exchange_rate_manager.py", line 81, in _update_price
    self._save_price(self._subtract_fee(self._handle_response(response)))
  File "c:\users\thoma\lbry\lbrynet\extras\daemon\exchange_rate_manager.py", line 132, in _handle_response
    json_response = json.loads(response)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Not happening anymore.
