### ISSUE TITLE
Error when running from source/pre-installed torba

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1899]
## The Issue
See the below when running from source. If you build torba from source, then it works. @shyba may know the fix here. 
```2019-02-09 13:05:54,997 ERROR    lbrynet.extras.daemon.Component:61: Error setting up stream_manager
Traceback (most recent call last):
  File "c:\users\thoma\documents\lbry\lbrynet\extras\daemon\Component.py", line 55, in _setup
    result = await self.start()
  File "c:\users\thoma\documents\lbry\lbrynet\extras\daemon\Components.py", line 458, in start
    await self.stream_manager.start()
  File "c:\users\thoma\documents\lbry\lbrynet\stream\stream_manager.py", line 188, in start
    await self.load_streams_from_database()
  File "c:\users\thoma\documents\lbry\lbrynet\stream\stream_manager.py", line 148, in load_streams_from_database
    log.info("Initializing %i files", len(file_infos))
TypeError: object of type 'NoneType' has no len()
Task exception was never retrieved
future: <Task finished coro=<Component._setup() done, defined at c:\users\thoma\documents\lbry\lbrynet\extras\daemon\Component.py:53> exception=TypeError("object of type 'NoneType' has no len()")>
Traceback (most recent call last):
  File "c:\users\thoma\documents\lbry\lbrynet\extras\daemon\Component.py", line 62, in _setup
    raise err
  File "c:\users\thoma\documents\lbry\lbrynet\extras\daemon\Component.py", line 55, in _setup
    result = await self.start()
  File "c:\users\thoma\documents\lbry\lbrynet\extras\daemon\Components.py", line 458, in start
    await self.stream_manager.start()
  File "c:\users\thoma\documents\lbry\lbrynet\stream\stream_manager.py", line 188, in start
    await self.load_streams_from_database()
  File "c:\users\thoma\documents\lbry\lbrynet\stream\stream_manager.py", line 148, in load_streams_from_database
    log.info("Initializing %i files", len(file_infos))
TypeError: object of type 'NoneType' has no len()```


## System Configuration

<!-- For the app, this info is in the About section at the bottom of the Help page. 
     You can include a screenshot instead of typing it out --> 

<!-- For the daemon, run:
     curl 'http://localhost:5279' --data '{"method":"version"}'
     and include the full output -->

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:


## Anything Else
<!-- Include anything else that does not fit into the above sections -->


## Screenshots
<!-- If a screenshot would help explain the bug, please include one or two here -->



## Internal Use

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
I'm told this is fixed, carry on!
