### ISSUE TITLE
exceptions.ValueError: could not convert string to float

### ISSUE THREAD

**Issue by whitslack** [lbryio/lbry#19]
This occurred while lbrynet-console was idle. (I think Python's logging infrastructure failed to spit out the exception cleanly due to some embedded rubbish, but you can probably still make sense of it if you squint.)

`Unable to format event {'log_namespace': u'log_legacy', 'log_time': 1457076355.002242, 'log_system': 'KademliaProtocol (UDP)', 'log_level': <LogLevel=critical>, 'system': 'KademliaProtocol (UDP)', 'isError': 1, 'failure': <twisted.python.failure.Failure <type 'exceptions.ValueError'>>, 'time': 1457076355.002242, 'log_text': 'Unhandled Error\nTraceback (most recent call last):\n  File "/usr/lib64/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext\n    return context.call({ILogContext: newCtx}, func, *args, **kw)\n  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext\n    return self.currentContext().callWithContext(ctx, func, *args, **kw)\n  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext\n    return func(*args,**kw)\n  File "/usr/lib64/python2.7/site-packages/twisted/internet/posixbase.py", line 611, in _doReadOrWrite\n    why = selectable.doRead()\n--- <exception caught here> ---\n  File "/usr/lib64/python2.7/site-packages/twisted/internet/udp.py", line 248, in doRead\n    self.protocol.datagramReceived(data, addr)\n  File "/usr/lib64/python2.7/site-packages/lbrynet/dht/protocol.py", line 109, in datagramReceived\n    msgPrimitive = self._encoder.decode(datagram)\n  File "/usr/lib64/python2.7/site-packages/lbrynet/dht/encoding.py", line 102, in decode\n    return self._decodeRecursive(data)[0]\n  File "/usr/lib64/python2.7/site-packages/lbrynet/dht/encoding.py", line 131, in _decodeRecursive\n    return (float(data[startIndex+1:endPos]), endPos+1)\nexceptions.ValueError: could not convert string to float: \xea\xed\xa5dm\x01x\xd4M\x9d\xd5\x86\x8c\xa0w#\x10\x89\x97\x9f\xe7^^\x1dwt\n', 'log_format': u'{log_text}', 'message': (), 'why': None}: 'ascii' codec can't decode byte 0xea in position 1306: ordinal not in range(128)`

This was commit f5b556c6cbbc26e3489b4b91df580fc0ede97684.

**Comment by whitslack** [comment]
Got another one of them, this time on commit b4c528f6b58439c2bcd942ba1bae1df70946f7bd:

`Unable to format event {'log_namespace': u'log_legacy', 'log_time': 1457452807.730342, 'log_system': 'KademliaProtocol (UDP)', 'log_level': <LogLevel=critical>, 'system': 'KademliaProtocol (UDP)', 'isError': 1, 'failure': <twisted.python.failure.Failure <type 'exceptions.ValueError'>>, 'time': 1457452807.730342, 'log_text': 'Unhandled Error\nTraceback (most recent call last):\n  File "/usr/lib64/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext\n    return context.call({ILogContext: newCtx}, func, *args, **kw)\n  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext\n    return self.currentContext().callWithContext(ctx, func, *args, **kw)\n  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext\n    return func(*args,**kw)\n  File "/usr/lib64/python2.7/site-packages/twisted/internet/posixbase.py", line 611, in _doReadOrWrite\n    why = selectable.doRead()\n--- <exception caught here> ---\n  File "/usr/lib64/python2.7/site-packages/twisted/internet/udp.py", line 248, in doRead\n    self.protocol.datagramReceived(data, addr)\n  File "/usr/lib64/python2.7/site-packages/lbrynet/dht/protocol.py", line 109, in datagramReceived\n    msgPrimitive = self._encoder.decode(datagram)\n  File "/usr/lib64/python2.7/site-packages/lbrynet/dht/encoding.py", line 102, in decode\n    return self._decodeRecursive(data)[0]\n  File "/usr/lib64/python2.7/site-packages/lbrynet/dht/encoding.py", line 131, in _decodeRecursive\n    return (float(data[startIndex+1:endPos]), endPos+1)\nexceptions.ValueError: could not convert string to float: \x89\xf8\xd2\xf5%\xe2\x11F\xff]\x80\x89\x15\xef\x9d\xb4\x0b\xff\xdb\x9bu\x9b\xf6\x15*\xb9\n', 'log_format': u'{log_text}', 'message': (), 'why': None}: 'ascii' codec can't decode byte 0x89 in position 1306: ordinal not in range(128)`
