### ISSUE TITLE
Download fails: ValueError: too many file descriptors in select()

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1927]
## The Issue
Happened during a TTFB run:
```
019-02-16 09:52:55,955 INFO     lbrynet.blob_exchange.client:126: downloaded 74a9672d from 35.153.147.111:3333
2019-02-16 09:52:55,965 INFO     lbrynet.stream.downloader:49: added head blob to search
2019-02-16 09:52:55,967 INFO     lbrynet.stream.stream_manager:302: got descriptor 74a9672d5224672d2aac06cb6904e5a70dc0b094ac70623435760645b11f14aba42fc7e476563257036623bf84bf9ff9 for how-to-make-muons
Traceback (most recent call last):
  File "c:\users\thoma\documents\lbry\lbrynet\extras\cli.py", line 277, in main
    loop.run_until_complete(daemon.stop_event.wait())
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 539, in run_forever
    self._run_once()
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 1739, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
ValueError: too many file descriptors in select()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\thoma\Documents\lbry\venv-lbry\Scripts\lbrynet-script.py", line 11, in <module>
    load_entry_point('lbrynet', 'console_scripts', 'lbrynet')()
  File "c:\users\thoma\documents\lbry\lbrynet\extras\cli.py", line 281, in main
    loop.run_until_complete(daemon.stop())
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 539, in run_forever
    self._run_once()
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 1739, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
ValueError: too many file descriptors in select()
```

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
This has not happened since, knocking down the priority. This may have to be handled in the connection manager https://github.com/lbryio/lbry/issues/1910

**Comment by tzarebczan** [comment]
Duplicate of https://github.com/lbryio/lbry/issues/2145
