### ISSUE TITLE
Appcrash on first startup

### ISSUE THREAD

**Issue by dvdvideo1234** [lbryio/lbry#1970]
## The Issue
The app crashes on a fresh install APPCRASH

### Steps to reproduce
1. Install the app through the site
2. Start the app

### Expected behavior

App to actually launch ;)

### Actual behavior

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\DVD>cd C:\Program Files\LBRY

C:\Program Files\LBRY>LBRY.exe

C:\Program Files\LBRY>
Starting SDK
Sandbox listening on port 5278.
Daemon: [5804] Failed to execute script cli

Daemon: Traceback (most recent call last):
  File "lbrynet\extras\cli.py", line 312, in <module>
  File "lbrynet\extras\cli.py", line 231, in main
  File "lbrynet\conf.py", line 404, in create_from_arguments
  File "lbrynet\conf.py", line 549, in __init__
  File "lbrynet\conf.py", line 561, in set_default_paths
  File "lbrynet\conf.py", line 574, in get_windows_directories
  File "lbrynet\winpaths.py", line 152, in get_path
lbrynet.winpaths.PathNotFoundException

## System Configuration
- LBRY Daemon version: N/A
- LBRY App version: N/A
- LBRY Installation ID: N/A
- Operating system: Windows 7 Ultimate x64

## Anything Else
![image](https://user-images.githubusercontent.com/9112662/53686286-d782b180-3d2d-11e9-81e3-0781e172b6c4.png)

### Definition of Done
- [x]  Tested against acceptance criteria
- [x] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Sorry to hear about the trouble. Which os are you on?

Did the app work before? Check your daemon_settings.yml file (same folder as logs) to check for invalid directories. 

Otherwise check out https://lbry.io/faq/startup-troubleshooting for common issues. Email us at help@lbry.io if you continue to have issues.

**Comment by tzarebczan** [comment]
@dvdvideo1234 see this comment from a user who had the same issue: `Problem solved! I patched my win win all new fixes and net frameworks and now working all! I think this have been some kind od net framework bug. Thank you all for effort! `

**Comment by dvdvideo1234** [comment]
@tzarebczan At least tell me:

1. What did he install to make it work? 
2. Is there additional SW dependencies which the app needs?

**Comment by dvdvideo1234** [comment]
It seems that it is actually a path problem

`File "lbrynet\winpaths.py", line 152, in get_path
lbrynet.winpaths.PathNotFoundException`

**Comment by tzarebczan** [comment]
There are not normally any additional dependencies...this sounds like a problem local to your system and dot net installation. I'd make sure your windows update is all caught up and reinstall net framework packages.

**Comment by dvdvideo1234** [comment]
Hmm, I do not seem to have the `daemon_settings.yml` in the install directory or in the entire `C` drive.
Do you happen to know the location of this file? My dot net framework is the latest installed. I also have Win7 SP1. My `.NET` currently installed is `4.0`

![image](https://user-images.githubusercontent.com/9112662/53826667-ce8a1e00-3f81-11e9-8543-15281ed3e748.png)

**Comment by dvdvideo1234** [comment]
Actually, I got the install package from the website.
https://lbry.io/get?src=PB

**Comment by dvdvideo1234** [comment]
Hmm, it seems I need to install `lbrynet` and `lbryum`. I do not have both directories present. I do seem to have these folders missing, which is strange to be done by `*.EXE` installation. Uninstalling for now. Until maybe I attempt to try the latest version and compile it or whatever ;)

**Comment by dvdvideo1234** [comment]
@tzarebczan

Could you please point me at least to the issue related to the following :

`Problem solved! I patched my win win all new fixes and net frameworks and now working all! I think this have been some kind od net framework bug. Thank you all for effort!`

**Comment by tzarebczan** [comment]
That was from a user on discord from a while. Also try installing https://www.microsoft.com/en-us/download/confirmation.aspx?id=49093&fbclid=IwAR2Gl1Qay34-_NnHpOSZm0VqMC9CQFish4vYXf4AQQ01cnJeE9ZDHdmInv0

**Comment by tzarebczan** [comment]
You don't have to 'install' those directories...they are created automatically if everything is working as it should.

**Comment by dvdvideo1234** [comment]
I will provide you with feedback this evening

**Comment by dvdvideo1234** [comment]
Well, that's unexpected..
![image](https://user-images.githubusercontent.com/9112662/53908119-5beb7200-4057-11e9-9bc4-9df627cf50e5.png)

**Comment by dvdvideo1234** [comment]
I don't think that this can be closed just like that. This error has to be investigated.

**Comment by tzarebczan** [comment]
@dvdvideo1234, unfortunately, this is a local issue with your installation and not a problem with our software. We use a standard python LBRY to find the local path (winpaths). I've run this successfully on Windows 7. I'd recommend reinstalling net framework packages for Win 7 and maybe checking your environmental variables PATH to make sure there are no syntax errors.

**Comment by dvdvideo1234** [comment]
I will provide you the value of my `PATH` variable.

**Comment by tzarebczan** [comment]
@dvdvideo1234 I was finally able to reproduce this, at least with one user.  His problem was that he moved his Windows Downloads folder to another location and our code didn't like that. Can you try to see if moving that back fixes for you too? 

We need to handle https://github.com/lbryio/lbry/blob/ea4444edbea63f490fb3215a65ec13effb3ad17f/lbrynet/conf.py#L570 / https://github.com/lbryio/lbry/blob/ea4444edbea63f490fb3215a65ec13effb3ad17f/lbrynet/conf.py#L582 better in case it hits an exception. We could default to something like `c:\LBRY\Downloads\` in that case.

**Comment by dvdvideo1234** [comment]
No, sorry. The OS drive is intended for OS and I have dedicated drives in that manner, every one of my `C:/` drive library ( pictures, music, documents, etc. ) folders are moved to drive `P:/`. And my windows `%TEMP%` and  `%TMP%` folders are moved to my [RamDrive](http://www.asrock.com/feature/XFast/XFastRAM/index.asp) for optimizing the SSD array write cycles count on drive `K:/`. In my opinion, an application should not care where is the actual folder located. I'd probably use [`std::getenv`](https://en.cppreference.com/w/cpp/utility/program/getenv) if in that manner, though this app is written in python and you must find something similar.

**Comment by tzarebczan** [comment]
Yep, it's a bug and we'll get it fixed. Not a common scenario for most users. 

Can we show you some [appreciation](https://LBRY.com/faq/appreciation) for raising the issue?

**Comment by dvdvideo1234** [comment]
@tzarebczan Yeah, feel free to do so ;) Contribution is what drives the open source community.

**Comment by dvdvideo1234** [comment]
For example, if you have registry access you can read them from here. This is my Office machine:
![image](https://user-images.githubusercontent.com/9112662/56038519-d5ebd680-5d3a-11e9-9e95-10bf0a72b142.png)

**Comment by dvdvideo1234** [comment]
Something like [that](https://stackoverflow.com/questions/5227107/python-code-to-read-registry) maybe ...
