### ISSUE TITLE
wallet server certificate / signing issues?

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#2007]
## The Issue
I'm running from 0.35.0 master branch, and see the following. It does work on victor's server. 
```2019-03-30 03:47:34,731 INFO     lbrynet.wallet.resolve:185: fetching certificate to check claim signature
2019-03-30 03:47:34,734 WARNING  lbrynet.wallet.resolve:188: Certificate e3468b7853608f45923b5c2b6abac159fc788576 not found
2019-03-30 03:47:34,735 WARNING  lbrynet.wallet.resolve:413: lbry://five#7d066008b06b34d203349e385182b6354bee7d5b has an invalid signature
```

On victor's server, there are other issues with permanent urls being incorrect (showing invalid claim ids) and his server erroring on newly signed claims:
```2019-03-30 04:15:29,416 INFO     lbrynet.wallet.resolve:185: fetching certificate to check claim signature
2019-03-30 04:15:29,434 ERROR    lbrynet.wallet.ledger:72: 'txid'
Traceback (most recent call last):
  File "c:\users\thoma\documents\lbry\lbrynet\wallet\ledger.py", line 70, in resolve
    return await resolver._handle_resolutions(resolutions, uris, page, page_size)
  File "c:\users\thoma\documents\lbry\lbrynet\wallet\resolve.py", line 33, in _handle_resolutions
    await self._handle_resolve_uri_response(uri, resolution, page, page_size)
  File "c:\users\thoma\documents\lbry\lbrynet\wallet\resolve.py", line 103, in _handle_resolve_uri_response
    raw)
  File "c:\users\thoma\documents\lbry\lbrynet\wallet\resolve.py", line 189, in parse_and_validate_claim_result
    cert_tx = await self.network.get_transaction(certificate['txid']) if certificate else None
KeyError: 'txid'
```

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by alyssaoc** [comment]
closing merged on 4/4
