### ISSUE TITLE
Recover/resync after wallet database corruption

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#2017]
## The Issue
A user ran into a database issue on mobile..this was after everything seemed to be working seemingly fine with new blocks being added. We should recover better from this problem. In this case, the database file had to be deleted and resynced. 

```2019-03-31 22:17:29,408 INFO     torba.client.baseledger:133: lbc_mainnet: added BlockHeightEvent(height=543671, change=1) header blocks, final height 543671
2019-03-31 22:21:51,141 INFO     torba.client.baseledger:133: lbc_mainnet: added BlockHeightEvent(height=543672, change=1) header blocks, final height 543672
2019-03-31 22:23:11,568 INFO     torba.client.baseledger:133: lbc_mainnet: added BlockHeightEvent(height=543673, change=1) header blocks, final height 543673
2019-03-31 22:23:30,726 INFO     torba.client.baseledger:133: lbc_mainnet: added BlockHeightEvent(height=543674, change=1) header blocks, final height 543674
2019-03-31 22:24:42,108 INFO     torba.client.baseledger:133: lbc_mainnet: added BlockHeightEvent(height=543675, change=1) header blocks, final height 543675
2019-03-31 22:26:29,184 INFO     torba.client.baseledger:133: lbc_mainnet: added BlockHeightEvent(height=543676, change=1) header blocks, final height 543676
2019-03-31 22:28:34,875 INFO     torba.client.baseledger:133: lbc_mainnet: added BlockHeightEvent(height=543677, change=1) header blocks, final height 543677
2019-03-31 22:30:21,440 ERROR    lbrynet.extras.daemon.Daemon:496: error handling api request
Traceback (most recent call last):
  File "/data/user/0/io.lbry.browser/files/app/crystax_python/site-packages/lbrynet/extras/daemon/Daemon.py", line 490, in _process_rpc_call
    result = await result
  File "/data/user/0/io.lbry.browser/files/app/crystax_python/site-packages/lbrynet/extras/daemon/Daemon.py", line 921, in jsonrpc_account_balance
    dewies = await account.get_balance(confirmations=confirmations)
  File "/data/user/0/io.lbry.browser/files/app/crystax_python/site-packages/torba/client/basedatabase.py", line 481, in get_balance
    balance = await self.select_txos('SUM(amount)', **constraints)
  File "/data/user/0/io.lbry.browser/files/app/crystax_python/site-packages/torba/client/basedatabase.py", line 438, in select_txos
    " JOIN tx USING (txid)".format(cols), **constraints
  File "/data/user/0/io.lbry.browser/files/app/crystax_python/stdlib.zip/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/data/user/0/io.lbry.browser/files/app/crystax_python/site-packages/torba/client/basedatabase.py", line 48, in __fetchall
    return conn.execute(*args, **kwargs).fetchall()
sqlite3.OperationalError: disk I/O error
2019-03-31 22:30:24,912 INFO     lbrynet.extras.daemon.Daemon:727: Get version info: {"processor": "", "python_version": "3.7.1", "platform": "Android 6.0 (API 23)", "os_release": "3.18.19+", "os_system": "Linux", "lbrynet_version": "0.32.4", "lbryschema_version": "0.0.16", "build": "release", "distro": {"id": "", "version": "", "version_parts": {"major": "", "minor": "", "build_number": ""}, "like": "", "codename": ""}, "desktop": "Unknown"}
2019-03-31 22:30:26,200 WARNING  lbrynet.extras.daemon.Daemon:482: Extraneous parameters for resolve command: uris
2019-03-31 22:30:39,702 WARNING  lbrynet.extras.daemon.Daemon:482: Extraneous parameters for resolve command: uris
2019-03-31 22:30:39,796 ERROR    lbrynet.extras.daemon.Daemon:496: error handling api request
Traceback (most recent call last):
  File "/data/user/0/io.lbry.browser/files/app/crystax_python/site-packages/lbrynet/extras/daemon/Daemon.py", line 490, in _process_rpc_call
    result = await result
  File "/data/user/0/io.lbry.browser/files/app/crystax_python/site-packages/lbrynet/extras/daemon/Daemon.py", line 921, in jsonrpc_account_balance
    dewies = await account.get_balance(confirmations=confirmations)
  File "/data/user/0/io.lbry.browser/files/app/crystax_python/site-packages/torba/client/basedatabase.py", line 481, in get_balance
    balance = await self.select_txos('SUM(amount)', **constraints)
  File "/data/user/0/io.lbry.browser/files/app/crystax_python/site-packages/torba/client/basedatabase.py", line 438, in select_txos
    " JOIN tx USING (txid)".format(cols), **constraints
  File "/data/user/0/io.lbry.browser/files/app/crystax_python/stdlib.zip/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/data/user/0/io.lbry.browser/files/app/crystax_python/site-packages/torba/client/basedatabase.py", line 48, in __fetchall
    return conn.execute(*args, **kwargs).fetchall()
sqlite3.OperationalError: disk I/O error
2019-03-31 22:30:53,036 ERROR    lbrynet.extras.daemon.Daemon:496: error handling api request
Traceback (most recent call last):
  File "/data/user/0/io.lbry.browser/files/app/crystax_python/site-packages/lbrynet/extras/daemon/Daemon.py", line 490, in _process_rpc_call
    result = await result
  File "/data/user/0/io.lbry.browser/files/app/crystax_python/site-packages/lbrynet/extras/daemon/Daemon.py", line 921, in jsonrpc_account_balance
    dewies = await account.get_balance(confirmations=confirmations)
  File "/data/user/0/io.lbry.browser/files/app/crystax_python/site-packages/torba/client/basedatabase.py", line 481, in get_balance
    balance = await self.select_txos('SUM(amount)', **constraints)
  File "/data/user/0/io.lbry.browser/files/app/crystax_python/site-packages/torba/client/basedatabase.py", line 438, in select_txos
    " JOIN tx USING (txid)".format(cols), **constraints
  File "/data/user/0/io.lbry.browser/files/app/crystax_python/stdlib.zip/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/data/user/0/io.lbry.browser/files/app/crystax_python/site-packages/torba/client/basedatabase.py", line 48, in __fetchall
    return conn.execute(*args, **kwargs).fetchall()
sqlite3.OperationalError: disk I/O error```


## System Configuration

<!-- For the app, this info is in the About section at the bottom of the Help page. 
     You can include a screenshot instead of typing it out --> 

<!-- For the daemon, run:
     curl 'http://localhost:5279' --data '{"method":"version"}'
     and include the full output -->

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:


## Anything Else
<!-- Include anything else that does not fit into the above sections -->


## Screenshots
<!-- If a screenshot would help explain the bug, please include one or two here -->



## Internal Use

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
A large creator recently ran into this. The SDK should detect it and recover automatically by resyncing the blockchain.db:

```20-07-29 08:16:14,601 INFO     lbry.wallet.ledger:343: Subscribing and updating accounts.
2020-07-29 08:16:14,602 INFO     lbry.wallet.ledger:452: Subscribe to 3 accounts
2020-07-29 08:16:14,604 ERROR    lbry.wallet.database:218: Error running transaction:
Traceback (most recent call last):
  File "lbry/wallet/database.py", line 214, in __run_transaction
  File "lbry/wallet/database.py", line 167, in <lambda>
sqlite3.DatabaseError: database disk image is malformed
2020-07-29 08:16:14,605 WARNING  lbry.wallet.database:220: rolled back
2020-07-29 08:16:14,669 INFO     lbry.wallet.network:363: connected to spv18.lbry.com:50001
2020-07-29 08:16:14,695 INFO     lbry.wallet.network:363: connected to spv14.lbry.com:50001
2020-07-29 08:16:14,740 INFO     lbry.wallet.network:363: connected to spv15.lbry.com:50001
2020-07-29 08:16:15,045 INFO     lbry.wallet.ledger:152: lbc_mainnet: added BlockHeightEvent(height=805048, change=2001) header blocks, final height 805048
2020-07-29 08:16:15,046 INFO     lbry.wallet.ledger:482: subscribed to 1/1 addresses on 216.19.244.55:50001
2020-07-29 08:16:15,046 INFO     lbry.wallet.ledger:485: finished subscribing to 1 addresses on 216.19.244.55:50001
2020-07-29 08:16:15,047 INFO     lbry.wallet.ledger:482: subscribed to 1/1 addresses on 216.19.244.55:50001
2020-07-29 08:16:15,047 INFO     lbry.wallet.ledger:485: finished subscribing to 1 addresses on 216.19.244.55:50001
2020-07-29 08:16:16,024 INFO     lbry.wallet.ledger:152: lbc_mainnet: added BlockHeightEvent(height=805195, change=147) header blocks, final height 805195
2020-07-29 08:16:16,025 INFO     lbry.wallet.network:363: connected to spv17.lbry.com:50001
2020-07-29 08:16:16,172 ERROR    lbry.wallet.database:218: Error running transaction:
Traceback (most recent call last):
  File "lbry/wallet/database.py", line 214, in __run_transaction
  File "lbry/wallet/database.py", line 748, in __many
sqlite3.DatabaseError: database disk image is malformed
2020-07-29 08:16:16,172 WARNING  lbry.wallet.database:220: rolled back
2020-07-29 08:16:16,333 INFO     lbry.wallet.network:363: connected to spv13.lbry.com:50001
2020-07-29 08:16:16,333 ERROR    lbry.wallet.database:218: Error running transaction:
Traceback (most recent call last):
  File "lbry/wallet/database.py", line 214, in __run_transaction
  File "lbry/wallet/database.py", line 167, in <lambda>
sqlite3.DatabaseError: database disk image is malformed
2020-07-29 08:16:16,334 WARNING  lbry.wallet.database:220: rolled back
2020-07-29 08:16:16,334 ERROR    lbry.extras.daemon.component:62: Error setting up wallet
Traceback (most recent call last):
  File "lbry/extras/daemon/component.py", line 55, in _setup
  File "lbry/extras/daemon/components.py", line 166, in start
  File "lbry/wallet/manager.py", line 80, in start
  File "lbry/wallet/ledger.py", line 335, in start
  File "lbry/wallet/account.py", line 556, in save_max_gap
  File "lbry/wallet/account.py", line 464, in get_max_gap
  File "lbry/wallet/account.py", line 140, in get_max_gap
  File "lbry/wallet/database.py", line 1123, in get_addresses
  File "lbry/wallet/database.py", line 1116, in select_addresses
  File "lbry/wallet/database.py", line 172, in execute_fetchall
  File "lbry/wallet/database.py", line 167, in _execute_fetch
  File "lbry/wallet/database.py", line 201, in run
  File "concurrent/futures/thread.py", line 57, in run
  File "lbry/wallet/database.py", line 201, in <lambda>
  File "lbry/wallet/database.py", line 214, in __run_transaction
  File "lbry/wallet/database.py", line 167, in <lambda>
sqlite3.DatabaseError: database disk image is malformed```
