### ISSUE TITLE
Error sending 'b'findValue' to own ip/port

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#2136]
## The Issue
```2019-05-16 14:34:49,143 WARNING  lbrynet.dht.protocol.protocol:518: Error sending 'b'findValue'' to 24.184.108.248:4400
Args: [b'L0Yi\xd0\nMk\x1d\xa3\xbc\x96\xf8j\x93\x9b\x91b^\x9fE\x7f\x04e\xb0\xd9\xf7\\\x1fT\xc0X\xbc\x97\xb0zy\xfe~\xc8y\x86\x92z\xde\x1e\xd0\x08', {b'protocolVersion': 1}]
Raised: <class 'AssertionError'>(('012bd010', '012bd010'))
2019-05-16 14:34:49,144 WARNING  lbrynet.dht.protocol.protocol:518: Error sending 'b'findValue'' to 24.184.108.248:4400
Args: [b'H\xed\xd1\xec\x85>\r+\xaa\xee\x9c\xb4\xa9\xee\n6\x14V\x8b\x88SsO\xc0~\xa8s\x80\xf8&\xb9\xe1C\xff\xc1HA\xc5%\xc7\xe7F\tL\x17\xe2\xac\x9c', {b'protocolVersion': 1}]
Raised: <class 'AssertionError'>(('012bd010', '012bd010'))
2019-05-16 14:34:49,144 ERROR    lbrynet.dht.protocol.protocol:653: Unexpected error while storing blob_hash
Traceback (most recent call last):
  File "c:\users\thoma\documents\lbry\lbrynet\dht\protocol\protocol.py", line 640, in store_to_peer
    return await __store()
  File "c:\users\thoma\documents\lbry\lbrynet\dht\protocol\protocol.py", line 633, in __store
    res = await self.get_rpc_peer(peer).store(hash_value)
  File "c:\users\thoma\documents\lbry\lbrynet\dht\protocol\protocol.py", line 151, in store
    find_value_resp = await self.find_value(blob_hash)
  File "c:\users\thoma\documents\lbry\lbrynet\dht\protocol\protocol.py", line 180, in find_value
    self.peer, RequestDatagram.make_find_value(self.protocol.node_id, key)
  File "c:\users\thoma\documents\lbry\lbrynet\dht\protocol\protocol.py", line 553, in send_request
    response = await asyncio.wait_for(response_fut, self.rpc_timeout)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\tasks.py", line 416, in wait_for
    return fut.result()
lbrynet.dht.error.RemoteException: <class 'AssertionError'>(('012bd010', '012bd010'))
2019-05-16 14:34:49,148 ERROR    lbrynet.dht.protocol.protocol:653: Unexpected error while storing blob_hash
Traceback (most recent call last):
  File "c:\users\thoma\documents\lbry\lbrynet\dht\protocol\protocol.py", line 640, in store_to_peer
    return await __store()
  File "c:\users\thoma\documents\lbry\lbrynet\dht\protocol\protocol.py", line 633, in __store
    res = await self.get_rpc_peer(peer).store(hash_value)
  File "c:\users\thoma\documents\lbry\lbrynet\dht\protocol\protocol.py", line 151, in store
    find_value_resp = await self.find_value(blob_hash)
  File "c:\users\thoma\documents\lbry\lbrynet\dht\protocol\protocol.py", line 180, in find_value
    self.peer, RequestDatagram.make_find_value(self.protocol.node_id, key)
  File "c:\users\thoma\documents\lbry\lbrynet\dht\protocol\protocol.py", line 553, in send_request
    response = await asyncio.wait_for(response_fut, self.rpc_timeout)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\tasks.py", line 416, in wait_for
    return fut.result()
lbrynet.dht.error.RemoteException: <class 'AssertionError'>(('012bd010', '012bd010'))```

## System Configuration

<!-- For the app, this info is in the About section at the bottom of the Help page. 
     You can include a screenshot instead of typing it out --> 

<!-- For the daemon, run:
     curl 'http://localhost:5279' --data '{"method":"version"}'
     and include the full output -->

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:


## Anything Else
<!-- Include anything else that does not fit into the above sections -->


## Screenshots
<!-- If a screenshot would help explain the bug, please include one or two here -->



## Internal Use

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Here's another similar one, but from my LAN port (192.168.0.1)

```
2019-09-03 09:47:22,079 WARNING  lbry.dht.protocol.protocol:473: error raised handling b'findValue' request from 192.168.0.1:4400 - <class 'AssertionError'>(('9a67f7bc', '9a67f7bc'))
2019-09-03 09:47:22,079 WARNING  lbry.dht.protocol.protocol:530: Error sending 'b'findValue'' to 24.184.108.248:4400
Args: [b'\x08\x1d\x12@\x8cRu\x9e\x0f\xa6L\x89L\xc2<\xf0c-g\x08\x90c\xf6\xf0u-\x1d\x7f\x19\xdb\x9e\xb0 ExL<\\\x11\xca\xdc\xc2:\x05T\x90\xe2\x8f', {b'p': 0, b'protocolVersion': 1}]
Raised: <class 'AssertionError'>(('9a67f7bc', '9a67f7bc'))
2019-09-03 09:47:22,080 ERROR    lbry.dht.protocol.protocol:668: Unexpected error while storing blob_hash
Traceback (most recent call last):
  File "c:\users\thoma\documents\lbry\lbry\lbry\dht\protocol\protocol.py", line 655, in store_to_peer
    return await __store()
  File "c:\users\thoma\documents\lbry\lbry\lbry\dht\protocol\protocol.py", line 648, in __store
    res = await self.get_rpc_peer(peer).store(hash_value)
  File "c:\users\thoma\documents\lbry\lbry\lbry\dht\protocol\protocol.py", line 162, in store
    find_value_resp = await self.find_value(blob_hash)
  File "c:\users\thoma\documents\lbry\lbry\lbry\dht\protocol\protocol.py", line 191, in find_value
    self.peer, RequestDatagram.make_find_value(self.protocol.node_id, key, page=page)
  File "c:\users\thoma\documents\lbry\lbry\lbry\dht\protocol\protocol.py", line 565, in send_request
    response = await asyncio.wait_for(response_fut, self.rpc_timeout)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\asyncio\tasks.py", line 416, in wait_for
    return fut.result()
lbry.dht.error.RemoteException: <class 'AssertionError'>(('9a67f7bc', '9a67f7bc'))
```

**Comment by tzarebczan** [comment]
Ping also: 
```2019-09-03 13:48:51,482 WARNING  lbry.dht.protocol.protocol:473: error raised handling b'ping' request from 192.168.0.1:4444 - <class 'AssertionError'>(('aead754b', 'aead754b'))
2019-09-03 13:48:51,488 WARNING  lbry.dht.protocol.protocol:530: Error sending 'b'ping'' to 24.184.108.248:4444
Args: [{b'protocolVersion': 1}]
Raised: <class 'AssertionError'>(('aead754b', 'aead754b'))
Task exception was never retrieved
future: <Task finished coro=<Node._value_producer.<locals>.ping() done, defined at lbry\dht\node.py:211> exception=RemoteException("<class 'AssertionError'>(('aead754b', 'aead754b'))")>
Traceback (most recent call last):
  File "lbry\dht\node.py", line 213, in ping
  File "lbry\dht\protocol\protocol.py", line 147, in ping
  File "lbry\dht\protocol\protocol.py", line 565, in send_request
  File "asyncio\tasks.py", line 442, in wait_for
lbry.dht.error.RemoteException: <class 'AssertionError'>(('aead754b', 'aead754b'))```
