### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#2137]
## The Issue
Similar error, 2 different scenarios. The first may have been related network saturation. The 2nd is prefaced by ```struct.error: unpack requires a buffer of 4 bytes``` which I've seen happen locally only once or twice, without any particular issues that I could tell. Not sure why it's trying to find a "get" attribute during a claim search call. 

```
2019-05-16 15:14:35,679 INFO     lbrynet.dht.blob_announcer:51: announced 5 blobs
2019-05-16 15:15:04,419 INFO     torba.client.baseledger:133: lbc_mainnet: added BlockHeightEvent(height=568534, change=1) header blocks, final height 568534
2019-05-16 15:15:21,629 INFO     lbrynet.blob_exchange.client:137: downloaded 4af012f8 from 18.213.255.15:5567
2019-05-16 15:15:21,652 INFO     lbrynet.stream.managed_stream:358: write blob 8/76
2019-05-16 15:15:28,815 INFO     torba.client.baseledger:133: lbc_mainnet: added BlockHeightEvent(height=568535, change=1) header blocks, final height 568535
2019-05-16 15:16:24,383 ERROR    lbrynet.wallet.resolve:42: 
Traceback (most recent call last):
  File "lbrynet/wallet/resolve.py", line 38, in resolve
  File "lbrynet/wallet/resolve.py", line 67, in _handle_resolutions
  File "lbrynet/wallet/resolve.py", line 109, in _handle_resolve_uri_response
  File "lbrynet/wallet/resolve.py", line 172, in parse_and_validate_claim_result
concurrent.futures._base.CancelledError
2019-05-16 15:16:24,391 WARNING  lbrynet.extras.daemon.Daemon:914: Error downloading mp3: Failed to resolve "mp3" within the timeout
2019-05-16 15:16:31,259 ERROR    lbrynet.wallet.resolve:42: 
Traceback (most recent call last):
  File "lbrynet/wallet/resolve.py", line 38, in resolve
  File "lbrynet/wallet/resolve.py", line 67, in _handle_resolutions
  File "lbrynet/wallet/resolve.py", line 109, in _handle_resolve_uri_response
  File "lbrynet/wallet/resolve.py", line 172, in parse_and_validate_claim_result
concurrent.futures._base.CancelledError
2019-05-16 15:16:31,267 WARNING  lbrynet.extras.daemon.Daemon:914: Error downloading mp3: 'str' object has no attribute 'get'
2019-05-16 15:16:39,715 ERROR    lbrynet.wallet.resolve:42: 
Traceback (most recent call last):
  File "lbrynet/wallet/resolve.py", line 38, in resolve
  File "lbrynet/wallet/resolve.py", line 67, in _handle_resolutions
  File "lbrynet/wallet/resolve.py", line 109, in _handle_resolve_uri_response
  File "lbrynet/wallet/resolve.py", line 172, in parse_and_validate_claim_result
concurrent.futures._base.CancelledError
2019-05-16 15:16:39,728 WARNING  lbrynet.extras.daemon.Daemon:914: Error downloading mp3: 'str' object has no attribute 'get'
2019-05-16 15:18:36,193 INFO     torba.client.baseledger:133: lbc_mainnet: added BlockHeightEvent(height=568536, change=1) header blocks, final height 568536
```

```2019-05-16 15:39:56,441 ERROR    lbrynet.wallet.resolve:42: unpack requires a buffer of 4 bytes
Traceback (most recent call last):
  File "lbrynet/wallet/resolve.py", line 38, in resolve
  File "lbrynet/wallet/resolve.py", line 67, in _handle_resolutions
  File "lbrynet/wallet/resolve.py", line 93, in _handle_resolve_uri_response
  File "lbrynet/wallet/resolve.py", line 156, in parse_and_validate_claim_result
  File "site-packages/torba/client/baseheader.py", line 74, in __getitem__
  File "lbrynet/wallet/header.py", line 35, in deserialize
struct.error: unpack requires a buffer of 4 bytes
2019-05-16 15:39:56,441 ERROR    lbrynet.extras.daemon.Daemon:561: error handling api request
Traceback (most recent call last):
  File "lbrynet/extras/daemon/Daemon.py", line 555, in _process_rpc_call
  File "lbrynet/extras/daemon/Daemon.py", line 1722, in jsonrpc_claim_search
  File "lbrynet/extras/daemon/Daemon.py", line 1722, in <listcomp>
AttributeError: 'str' object has no attribute 'get'
2019-05-16 15:39:56,538 INFO     lbrynet.wallet.resolve:166: fetching certificate to check claim signature
2019-05-16 15:39:56,726 ERROR    lbrynet.wallet.resolve:42: unpack requires a buffer of 4 bytes
Traceback (most recent call last):
  File "lbrynet/wallet/resolve.py", line 38, in resolve
  File "lbrynet/wallet/resolve.py", line 67, in _handle_resolutions
  File "lbrynet/wallet/resolve.py", line 93, in _handle_resolve_uri_response
  File "lbrynet/wallet/resolve.py", line 156, in parse_and_validate_claim_result
  File "site-packages/torba/client/baseheader.py", line 74, in __getitem__
  File "lbrynet/wallet/header.py", line 35, in deserialize
struct.error: unpack requires a buffer of 4 bytes
2019-05-16 15:39:56,726 ERROR    lbrynet.extras.daemon.Daemon:561: error handling api request
Traceback (most recent call last):
  File "lbrynet/extras/daemon/Daemon.py", line 555, in _process_rpc_call
  File "lbrynet/extras/daemon/Daemon.py", line 1722, in jsonrpc_claim_search
  File "lbrynet/extras/daemon/Daemon.py", line 1722, in <listcomp>
AttributeError: 'str' object has no attribute 'get'
2019-05-16 15:39:56,823 INFO     lbrynet.wallet.resolve:166: fetching certificate to check claim signature
2019-05-16 15:39:57,012 ERROR    lbrynet.wallet.resolve:42: unpack requires a buffer of 4 bytes
Traceback (most recent call last):
  File "lbrynet/wallet/resolve.py", line 38, in resolve
  File "lbrynet/wallet/resolve.py", line 67, in _handle_resolutions
  File "lbrynet/wallet/resolve.py", line 93, in _handle_resolve_uri_response
  File "lbrynet/wallet/resolve.py", line 156, in parse_and_validate_claim_result
  File "site-packages/torba/client/baseheader.py", line 74, in __getitem__
  File "lbrynet/wallet/header.py", line 35, in deserialize
struct.error: unpack requires a buffer of 4 bytes
2019-05-16 15:39:57,012 ERROR    lbrynet.extras.daemon.Daemon:561: error handling api request
Traceback (most recent call last):
  File "lbrynet/extras/daemon/Daemon.py", line 555, in _process_rpc_call
  File "lbrynet/extras/daemon/Daemon.py", line 1722, in jsonrpc_claim_search
  File "lbrynet/extras/daemon/Daemon.py", line 1722, in <listcomp>
AttributeError: 'str' object has no attribute 'get'
```

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
This is fixed on 0.37.1
