### ISSUE TITLE
Wallet sync - Error binding parameter 0 - probably unsupported type

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#2164]
## The Issue
Seeing this when syncing my wallet from scratch on 0.37.1. On restart, it resyncs those addresses/txes it failed on.  I can provide a wallet file this happens on. 

```
2019-05-22 11:29:08,217 INFO     torba.client.baseledger:125: (lbc_mainnet) on_address: ['bRFrdNffbqpmLnJDv9n3WPXHSQZx3jbQ9d', 'bCooREDfWchZp2W3J3sp4cpYFTwFgjs4HB', 'bJ4t5xDH3VaCn9tyjf2SGKr9E5NWsTVoZa', 'bR8NvBkV4FKzm3GsrLTLpEdajoPSin86Hg', 'bGuS42xgcRH6eVoXmFusiie2z85v4fbkm5', 'bWc6ZgefAwqvKddQGhbnuNuGe5Qdt3JyS5', 'bGVmKgRnPHq9XWthMoVkJYhP6fM3FuZjFC', 'bZKK6irm4fKg1RrsZA7vTBMuDk7JruSkCe', 'bEWAJXE7uYckDKTzkEREUfnC5Rw4y5y8fa', 'bKMV41fHzU5a3c32HJ42ZL39jXprz9muze', 'bRu9SZhSwrKiPhJEoDSXMsb7JyHmJRg13C', 'bH3J7FnNPtA8RC4CL7pLYZcRBuDE3dfzgk', 'bPwfPQTUTPncazeeJdrNcTYhjKkLQkRDNJ', 'bRaQP4JbgTDJbgvbJaYWNVHzpBoi3TDHGD', 'bWt4UvNRbUqwbJtW5gUabEj3dG2uaRVJzD', 'bUKFnd7uSnFyQbvqvpdK3MGvRA8HccuqYt', 'bEsC4CeSCP5sRsnMgt8G7L2HewrwRzg3en', 'baASTNc6t6V82wNrgSwvwuYK3s6Uga93w7', 'bL5vFyUvzazUkWdgqG1ZRQksW1zBP6KWb5', 'bUqVumd8AYbCNDkvSTPbcN24K7Lk5SnFkm']
2019-05-22 11:29:08,229 INFO     torba.client.baseledger:125: (lbc_mainnet) on_address: ['bLrEADwdXaTuzqJp74JaQ2oKd7TabEAuEX', 'bCvuQRyHLBS1RsQUzYRYvu4FQsVLkB8CqG', 'bRmhdKXXaWJVQP9rc4g6cXzzyoJM5qsDMg', 'bTz5yM5yn19gMTQoJJyUBgubJ34nkuViqh', 'bQ5mfFViSU8b69uNcESfteoF1pAoC2XNrs', 'bCvjVRgnKm28CBLZNDGWHGos2Dv5QL4byA', 'bFLvefdk1Da2GB5oxVZXsK4PZ8Bs24Ghbf', 'bMtWobUFJMutGJ6o5UHN4EAHtK3NnRoxu5', 'bD45BgoG6DxywWzZKY6fbf787M1v2ZgVgZ', 'bEcykVNdYmK9M5JNaCPgfcr1qeK78jGYGf', 'bJZa3GrhWs4u7NZyHgZutaPybQGGeMy1cY', 'bap8B9oci9y1uCPQYbJaguE6ty3N8UnBvM', 'bH7jrnURyV4Azmit8LcfdMgQST5sdhTKx8', 'bNR2EWJGXbU24zxsu1wAw139vwJvmcVizs', 'bM6j8GyvRxZ6xL1kwnKm6TXwYeU3D8CYGS', 'bHcemnXEnisLAouvk3amqXx8X1BfJrTThT', 'bKxxwYWqjsjX9yYwgygWzNGkMYD48UbuYm', 'bP8yrGLewLZKJ8T9EaPXVYWJdNY5Po9V8S', 'bMYhng5tGaa88X62DfnWynmSdM6aPVQamF', 'bHQrTNGLHkMrwZETJaFcD2RwLKdkoQV1oR']
Task exception was never retrieved
future: <Task finished coro=<BaseLedger.subscribe_account() done, defined at c:\users\thoma\documents\lbry\torba\torba\client\baseledger.py:344> exception=InterfaceError('Error binding parameter 0 - probably unsupported type.')>
Traceback (most recent call last):
  File "c:\users\thoma\documents\lbry\torba\torba\client\baseledger.py", line 347, in subscribe_account
    await account.ensure_address_gap()
  File "c:\users\thoma\documents\lbry\torba\torba\client\baseaccount.py", line 375, in ensure_address_gap
    new_addresses = await address_manager.ensure_address_gap()
  File "c:\users\thoma\documents\lbry\torba\torba\client\baseaccount.py", line 139, in ensure_address_gap
    new_keys = await self._generate_keys(start, end-1)
  File "c:\users\thoma\documents\lbry\torba\torba\client\baseaccount.py", line 147, in _generate_keys
    await self.account.ledger.db.add_keys(self.account, self.chain_number, keys)
  File "c:\users\thoma\documents\lbry\torba\torba\client\basedatabase.py", line 516, in add_keys
    for position, pubkey in keys)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\thoma\documents\lbry\torba\torba\client\basedatabase.py", line 61, in __run_transaction
    result = fun(self.connection, *args, **kwargs)  # type: ignore
  File "c:\users\thoma\documents\lbry\torba\torba\client\basedatabase.py", line 39, in __executemany_in_a_transaction
    return conn.executemany(*args, **kwargs)
sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.
2019-05-22 11:29:08,305 INFO     torba.client.baseledger:118: (lbc_mainnet) on_transacti
```

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Just ran into this while testing lbry web / new accounts

```2019-06-05 09:55:46,130 INFO     lbrynet.dht.blob_announcer:51: announced 2 blobs
2019-06-05 09:58:37,174 INFO     torba.client.baseledger:133: lbc_mainnet: added BlockHeightEvent(height=579360, change=1) header blocks, final height 579360
2019-06-05 09:59:58,197 INFO     torba.client.baseledger:125: (lbc_mainnet) on_address: ['bUzhEc4vMt8hkamu9J9CANRajKM96wwKgW', 'bJfoNH2GohaFDaZ8ovgTTzmosjF4w5TMqM', 'bPyifLz9UDuyYbqYBCfVNufmQALSNWCrjV', 'bQsS3c5zYwC3n8Pqg8sexecuRwxdVnA4m7', 'baGdSG5WE5Ytv4vcKwaeep8mBF935F5JLT', 'bFgy5uUAPneeqjBmBpQt6pKR2DHSBnzoLo', 'bEasShW63hKUygHSzpeFTb8jE7xWTPDUUu', 'bPdoid6uCJFj2WMw933EVHBjpmfmhhybHE', 'bT7rcRTVyZX3jMVLc6j9CqbwC5s6moyg9K', 'bDUjsSbT6cKMMm4jzix2qPAErQGyeuYMeL', 'bNjZLHkWdeiJWRsH8XUgoFEgLAk4C9EB4E', 'bLMYFShqzsWpQmiVjaNNCcDWhQhfEQCcAG', 'bKaYxjkRFpqnb2WoNTn9j1WAR97LJEpNtt', 'bU2sH7scScCiXVxPzdbLWDinTW7JGgh22Z', 'bPnde9BwqNcVqTQcSJbbc6bJGs4YmHHpJ6', 'bZPsuNStq34hzjuNx7hgjT6WuNfSzegRtW', 'bbsHzSxAnpn6uo6XsZQTmFCRkt46jJhZGF', 'bMNCPMS9yAbxRWk4FMPTbN5CF9iQrDbryF', 'bPWpzLi7uDBKuUgnTXckpY1wUwy1L1ofmz', 'bJmMS2TVwVzBc2C6zcNh6HmfEmagcuxDr8']
2019-06-05 09:59:58,222 ERROR    lbrynet.extras.daemon.Daemon:576: error handling api request
Traceback (most recent call last):
  File "lbrynet\extras\daemon\Daemon.py", line 570, in _process_rpc_call
  File "lbrynet\extras\daemon\Daemon.py", line 1088, in jsonrpc_account_create
  File "site-packages\torba\client\baseledger.py", line 347, in subscribe_account
  File "site-packages\torba\client\baseaccount.py", line 375, in ensure_address_gap
  File "site-packages\torba\client\baseaccount.py", line 139, in ensure_address_gap
  File "site-packages\torba\client\baseaccount.py", line 147, in _generate_keys
  File "site-packages\torba\client\basedatabase.py", line 516, in add_keys
  File "concurrent\futures\thread.py", line 57, in run
  File "site-packages\torba\client\basedatabase.py", line 61, in __run_transaction
  File "site-packages\torba\client\basedatabase.py", line 39, in __executemany_in_a_transaction
sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.
2019-06-05 09:59:58,258 INFO     torba.client.baseledger:125: (lbc_mainnet) on_address: ['bDMyiiC4ugyR76ddsjKEQFXfvVx8V9jcxH', 'bNJxt6RESvPmUQAG25vwx3Lz3ozgK6mJY3', 'bGnLBKRA5Qdj5ciV7iBUauAgSbEqUW9dUG', 'bVMdmALq43PpTvsoUzVDM8i8AXkQe6qwK3', 'bV98w5boPVwy6Niznk2Az58ysQbA9nhsPN', 'bYL2rzZ7AEKdXiXrCqdBC3qMdovUh5CfxY']
2019-06-05 09:59:58,497 INFO     lbrynet.extras.daemon.Daemon:807: Get version info: {"processor": "AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD", "python_version": "3.7.1", "platform": "Windows-10-10.0.17763", "os_release": "10", "os_system": "Windows", "lbrynet_version": "0.37.2", "build": "release"}```

**Comment by tzarebczan** [comment]
@akinwale is also running into this on  mobile now, and myself/Jeremy also encountered it. Happens when restoring/syncing back a wallet.

**Comment by tzarebczan** [comment]
A couple users are running into this on Android when restoring wallets.

**Comment by lyoshenka** [comment]
Lex/Victor reproduced it at some point.

**Comment by eukreign** [comment]
Excerpts from: https://lbryians.slack.com/archives/C81K0BM9A/p1559746862006900

got it to reproduce:
```
        await asyncio.wait([
            self.daemon.jsonrpc_account_create('second account'+str(x)) for x in range(100)
        ])
```

lex: going to try upgrading sqlite3
lex: trying 3.22
lex: still erroring
lex: it fails much more reliably on 3.22
lex: woah, error doesn't appear to be coming from sqlite
lex: i grepped sqlite source for various parts of the error message and nothing
lex: going to check python source
lex: https://github.com/python/cpython/blob/master/Modules/_sqlite/statement.c#L265
lex: going to have to build python and print that rc value
lex: cus the error that's thrown doesn't include it :facepalm5:
lex: sqlite3.InterfaceError: Error 21 - probably unsupported type.
lex: https://github.com/mackyle/sqlite/blob/master/src/sqlite.h.in#L447
tomzarebczan: Stop using it incorrectly, duh.
lex: yeah, it's so obviouis :rolling_on_the_floor_laughing:
lex: i'm going to give up on this for now

**Comment by jackrobison** [comment]
The hidden `SQLITE_MISUSE` is being returned by 
https://github.com/python/cpython/blob/525269430a3f9fbb7287e4bb6b365ac216004980/Modules/_sqlite/statement.c#L165
