### ISSUE TITLE
file list error - TypeError: '<' not supported between instances of 'int' and 'NoneType'

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#2165]
## The Issue
Akin ran into this while testing range requests on Android. 
```
05-22 15:51:06.609 8634-8699/io.lbry.browser:service_lbrynet I/lbrynetservice: 2019-05-22 15:51:06,608 ERROR    lbrynet.extras.daemon.Daemon:561: error handling api request
    Traceback (most recent call last):
      File "/data/user/0/io.lbry.browser/files/app/crystax_python/site-packages/lbrynet/extras/daemon/Daemon.py", line 553, in _process_rpc_call
        result = fn(self, *_args, **_kwargs)
05-22 15:51:06.610 8634-8699/io.lbry.browser:service_lbrynet I/lbrynetservice:   File "/data/user/0/io.lbry.browser/files/app/crystax_python/site-packages/lbrynet/extras/daemon/Daemon.py", line 72, in _inner
        return fn(*args, **kwargs)
      File "/data/user/0/io.lbry.browser/files/app/crystax_python/site-packages/lbrynet/extras/daemon/Daemon.py", line 1501, in jsonrpc_file_list
        sort, reverse, comparison, **kwargs
      File "/data/user/0/io.lbry.browser/files/app/crystax_python/site-packages/lbrynet/stream/stream_manager.py", line 276, in get_filtered_streams
        streams.sort(key=lambda s: getattr(s, sort_by))
    TypeError: '<' not supported between instances of 'int' and 'NoneType'
```
## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Saw some of these on spee.ch recently too

**Comment by tzarebczan** [comment]
This still happens intermittently if you stream/download and then remove content. 

```2020-01-21 08:58:10,595 ERROR    lbry.extras.daemon.daemon:630: error handling api request
Traceback (most recent call last):
  File "/data/user/0/io.lbry.browser/files/app/crystax_python/site-packages/lbry/extras/daemon/daemon.py", line 624, in _process_rpc_call
    result = await result
  File "/data/user/0/io.lbry.browser/files/app/crystax_python/site-packages/lbry/extras/daemon/daemon.py", line 1873, in jsonrpc_file_list
    self.stream_manager.get_filtered_streams(sort, reverse, comparison, **kwargs), page, page_size
  File "/data/user/0/io.lbry.browser/files/app/crystax_python/site-packages/lbry/stream/stream_manager.py", line 280, in get_filtered_streams
    streams.sort(key=lambda s: getattr(s, sort_by))
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

In this case, it would fail when passing the added on param. Restart seemed to fix it. 
```
jsonrpc":"2.0","method":"file_list","params":{"page_size": 100, "reverse": true, "sort": "added_on"},"id":1556651600094}
```
