### ISSUE TITLE
"Catching up to the blockchain" stalls after first progress report

### ISSUE THREAD

**Issue by whitslack** [lbryio/lbry#25]
At commit 2670279b0d6f94bf25ef34fb654d18c2b3578033.

```
$ lbrynet-console
Loading databases...
Databases loaded.
Loading the wallet...
Catching up to the blockchain...showing blocks left...
1464...
1110...
1110...
1110...
1110...
1110...
1111...
1111...
1111...
1111...
1111...
^C

$ lbrynet-console
Loading databases...
Databases loaded.
Loading the wallet...
Catching up to the blockchain...showing blocks left...
1111...
391...
391...
391...
391...
391...
391...
391...
391...
391...
391...
^C

$ lbrynet-console
Loading databases...
Databases loaded.
Loading the wallet...
Catching up to the blockchain...showing blocks left...
392...
All caught up. Wallet loaded.

You should have received 1000 LBC the first time you ran
this program. If you did not, let us know! But first give
them a moment to show up. The block time is currently 30
seconds so they should show up within a couple of minutes.

Welcome to lbrynet-console!

Enter a command. Try 'get wonderfullife' or 'help' to see more options.
> 
```

**Comment by whitslack** [comment]
At commit 2670279b0d6f94bf25ef34fb654d18c2b3578033.

Perhaps this is a clue. I had an unhandled error (Issue #16), and after exiting and restarting `lbrynet-console`, I ran into this issue again.

```
> Unhandled Error
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/usr/lib64/python2.7/site-packages/twisted/internet/posixbase.py", line 611, in _doReadOrWrite
    why = selectable.doRead()
--- <exception caught here> ---
  File "/usr/lib64/python2.7/site-packages/twisted/internet/udp.py", line 248, in doRead
    self.protocol.datagramReceived(data, addr)
  File "/usr/lib64/python2.7/site-packages/lbrynet/dht/protocol.py", line 114, in datagramReceived
    message = self._translator.fromPrimitive(msgPrimitive)
  File "/usr/lib64/python2.7/site-packages/lbrynet/dht/msgformat.py", line 46, in fromPrimitive
    msgType = msgPrimitive[self.headerType]
exceptions.TypeError: 'NoneType' object has no attribute '__getitem__'


> exit
Shutting down.
lbry@Crushinator ~ $ lbrynet-console 
Loading databases...
Databases loaded.
Loading the wallet...
Catching up to the blockchain...showing blocks left...
2695...
2267...
2268...
2268...
2268...
2268...
2268...
2268...
2269...
^C
```

**Comment by jackrobison** [comment]
Was this fixed by deleting blockchain_headers in the lbryum directory?

**Comment by whitslack** [comment]
That did work last time. This time I just kept killing and restarting `lbrynet-console` to catch it up.

I just did it again:

```
lbry@Crushinator ~ $ lbrynet-console 
Loading databases...
Databases loaded.
Loading the wallet...
Catching up to the blockchain...showing blocks left...
2397...
1698...
1698...
1698...
^Clbry@Crushinator ~ $ lbrynet-console 
Loading databases...
Databases loaded.
Loading the wallet...
Catching up to the blockchain...showing blocks left...
1698...
978...
978...
978...
^Clbry@Crushinator ~ $ lbrynet-console 
Loading databases...
Databases loaded.
Loading the wallet...
Catching up to the blockchain...showing blocks left...
979...
259...
259...
259...
^Clbry@Crushinator ~ $ lbrynet-console 
Loading databases...
Databases loaded.
Loading the wallet...
Catching up to the blockchain...showing blocks left...
260...
All caught up. Wallet loaded.

You should have received 1000 LBC the first time you ran
this program. If you did not, let us know! But first give
them a moment to show up. The block time is currently 30                                                                            
seconds so they should show up within a couple of minutes.                                                                          
                                                                                                                                    
Welcome to lbrynet-console!                                                                                                         
                                                                                                                                    
Enter a command. Try 'get wonderfullife' or 'help' to see more options.
> 
```

**Comment by lyoshenka** [comment]
closing because I believe its fixed. please reopen if this still happens in the latest version (0.3.5 or higher)
