### ISSUE TITLE
If lbryum wallet fails to connect , lbry fails silently

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbry#250]
If lbryum wallet fails to connect to a lbryum server (port 50001 being blocked behind a firewall , server is down, etc..) , lbry will take a while to start up, and than start up silently ignoring the fact that the wallet is not loaded properly.

**Comment by kaykurokawa** [comment]
Logs will appear as below 

2016-11-07 10:45:54,450 INFO     lbrynet.lbrynet_daemon.ExchangeRateManager:137: Starting exchange rate manager
2016-11-07 10:45:55,109 INFO     lbrynet.lbrynet_daemon.UIManager:80: Checking for updates for UI branch: master
2016-11-07 10:45:55,501 INFO     lbrynet.lbrynet_daemon.UIManager:100: UI is up to date
2016-11-07 10:45:55,686 INFO     lbrynet.lbrynet_daemon.Daemon:435: Platform: {"lbrynet_version": "0.7.5", "platform": "Linux-4.4.0-45-generic-x86_64-with-Ubuntu-16.04-xenial", "os_system": "Linux", "python_version": "2.7.12", "os_release": "4.4.0-45-generic", "ip": "38.98.224.98", "lbryum_version": "2.7.1", "ui_version": "1e055ea59fba62221fda83b7a9a3eb14f204c538", "processor": "x86_64"}
2016-11-07 10:45:55,704 INFO     lbrynet.lbrynet_daemon.Daemon:704: Loading databases...
2016-11-07 10:45:55,715 INFO     lbrynet.lbrynet_daemon.Daemon:751: LBRY ID: 1JxcxuxJ2AHafyECb9RDAC7zMtCfwF1wddQ9YAFzJ5qM3o1dcrthznKB6m5z4p7nW
2016-11-07 10:45:55,717 INFO     lbrynet.lbrynet_daemon.Daemon:445: Loaded claim info cache
2016-11-07 10:45:55,719 INFO     lbrynet.lbrynet_daemon.Daemon:812: Using lbryum wallet
2016-11-07 10:45:59,740 INFO     lbrynet.core.BlobManager:95: Setting up the DiskBlobManager. blob_dir: /home/treantprotector/.lbrynet/blobfiles, db_file: /home/treantprotector/.lbrynet/blobs.db
2016-11-07 10:46:05,786 INFO     lbryalert.lbrynet.core.Wallet:1141: Loading the wallet...
2016-11-07 10:48:13,191 ERROR    lbrynet.core.Session:308: Traceback (most recent call last):
Failure: twisted.internet.defer.FirstError: FirstError[#1, [Failure instance: Traceback (failure with no frames): <type 'exceptions.ValueError'>: Failed to connect to network.
]]

2016-11-07 10:48:13,217 INFO     lbrynet.lbrynet_daemon.Daemon:355: Starting balance: 0
2016-11-07 10:48:13,659 INFO     lbrynet.lbrynet_daemon.Daemon:369: Started lbrynet-daemon
2016-11-07 10:48:13,660 INFO     lbrynet.lbrynet_daemon.DaemonControl:159: Using non-authenticated API
2016-11-07 10:48:35,574 INFO     lbrynet.lbrynet_daemon.Daemon:1225: Get version info: {"lbrynet_version": "0.7.5", "platform": "Linux-4.4.0-45-generic-x86_64-with-Ubuntu-16.04-xenial", "os_system": "Linux", "remote_lbryum": "2.7.1", "os_release": "4.4.0-45-generic", "lbryum_version": "2.7.1", "ui_version": null, "lbrynet_update_available": false, "remote_lbrynet": "0.7.5", "lbryum_update_available": false}
2016-11-07 10:48:35,612 INFO     lbrynet.lbrynet_daemon.Daemon:1318: Get balance
2016-11-07 10:48:35,615 INFO     lbrynet.lbrynet_daemon.Daemon:1175: Get startup notice
2016-11-07 10:48:37,403 INFO     lbrynet.lbrynet_daemon.Daemon:1225: Get version info: {"lbrynet_version": "0.7.5", "platform": "Linux-4.4.0-45-generic-x86_64-with-Ubuntu-16.04-xenial", "os_system": "Linux", "remote_lbryum": "2.7.1", "os_release": "4.4.0-45-generic", "lbryum_version": "2.7.1", "ui_version": null, "lbrynet_update_available": false, "remote_lbrynet": "0.7.5", "lbryum_update_available": false}
2016-11-07 10:48:37,431 INFO     lbrynet.lbrynet_daemon.Daemon:1318: Get balance
2016-11-07 10:48:37,434 INFO     lbrynet.lbrynet_daemon.Daemon:1175: Get startup notice
2016-11-07 10:48:39,484 INFO     lbrynet.lbrynet_daemon.Daemon:1225: Get version info: {"lbrynet_version": "0.7.5", "platform": "Linux-4.4.0-45-generic-x86_64-with-Ubuntu-16.04-xenial", "os_system": "Linux", "remote_lbryum": "2.7.1", "os_release": "4.4.0-45-generic", "lbryum_version": "2.7.1", "ui_version": null, "lbrynet_update_available": false, "remote_lbrynet": "0.7.5", "lbryum_update_available": false}
2016-11-07 10:48:39,537 INFO     lbrynet.lbrynet_daemon.Daemon:1318: Get balance
2016-11-07 10:48:39,540 INFO     lbrynet.lbrynet_daemon.Daemon:1175: Get startup notice
2016-11-07 10:48:40,577 INFO     lbrynet.lbrynet_daemon.Daemon:1225: Get version info: {"lbrynet_version": "0.7.5", "platform": "Linux-4.4.0-45-generic-x86_64-with-Ubuntu-16.04-xenial", "os_system": "Linux", "remote_lbryum": "2.7.1", "os_release": "4.4.0-45-generic", "lbryum_version": "2.7.1", "ui_version": null, "lbrynet_update_available": false, "remote_lbrynet": "0.7.5", "lbryum_update_available": false}
2016-11-07 10:48:40,605 INFO     lbrynet.lbrynet_daemon.Daemon:1318: Get balance
2016-11-07 10:48:40,607 INFO     lbrynet.lbrynet_daemon.Daemon:1175: Get startup notice
2016-11-07 10:48:41,925 INFO     lbrynet.lbrynet_daemon.Daemon:1225: Get version info: {"lbrynet_version": "0.7.5", "platform": "Linux-4.4.0-45-generic-x86_64-with-Ubuntu-16.04-xenial", "os_system": "Linux", "remote_lbryum": "2.7.1", "os_release": "4.4.0-45-generic", "lbryum_version": "2.7.1", "ui_version": null, "lbrynet_update_available": false, "remote_lbrynet": "0.7.5", "lbryum_update_available": false}
2016-11-07 10:48:41,942 INFO     lbrynet.lbrynet_daemon.Daemon:2522: Resolving stream info for lbry://tttt
Unhandled error in Deferred:


Traceback (most recent call last):
  File "/usr/share/python/lbrynet/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
  File "/usr/share/python/lbrynet/local/lib/python2.7/site-packages/twisted/internet/base.py", line 798, in runUntilCurrent
    f(*a, **kw)
  File "/usr/share/python/lbrynet/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 393, in callback
    self._startRunCallbacks(result)
  File "/usr/share/python/lbrynet/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/share/python/lbrynet/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/share/python/lbrynet/local/lib/python2.7/site-packages/lbrynet/lbrynet_daemon/Daemon.py", line 2679, in _add_metadata
    d = self.daemon._resolve_name(lbry_file.uri)
  File "/usr/share/python/lbrynet/local/lib/python2.7/site-packages/lbrynet/lbrynet_daemon/Daemon.py", line 933, in _resolve_name
    return helper.get_deferred()
  File "/usr/share/python/lbrynet/local/lib/python2.7/site-packages/lbrynet/lbrynet_daemon/Daemon.py", line 2523, in get_deferred
    d = self.wallet.get_stream_info_for_name(self.name)
  File "/usr/share/python/lbrynet/local/lib/python2.7/site-packages/lbrynet/core/Wallet.py", line 307, in get_stream_info_for_name
    d = self._get_value_for_name(name)
  File "/usr/share/python/lbrynet/local/lib/python2.7/site-packages/lbrynet/core/Wallet.py", line 1389, in _get_value_for_name
    func = getattr(self.cmd_runner, cmd.name)
exceptions.AttributeError: 'NoneType' object has no attribute 'getvalueforname'
2016-11-07 10:48:41,950 INFO     lbrynet.lbrynet_daemon.Daemon:1318: Get balance
Unhandled error in Deferred:

**Comment by kaykurokawa** [comment]
https://github.com/lbryio/lbry/commit/a5c25ff8873e1e6f5dc875d3f9670276245d9ee6

This patch forces lbrynet to not open if lbryum fails to connect to network
