### ISSUE TITLE
publish error notifyFinish

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#343]
2016-12-15 21:58:27,759 ERROR    lbrynet.lbrynet_daemon.auth.server:164: Failed to render API response: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
2016-12-15 21:58:27,760 ERROR    lbrynet.lbrynet_daemon.auth.server:164: API Failure: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 588, in _runCallbacks
  File "C:\projects\lbry\lbrynet\lbrynet_daemon\auth\server.py", line 313, in _callback_render
  File "C:\projects\lbry\lbrynet\lbrynet_daemon\auth\server.py", line 119, in _log_and_render_error
  File "C:\projects\lbry\lbrynet\lbrynet_daemon\auth\server.py", line 114, in _render_error
  File "C:\Python27\lib\site-packages\twisted\web\server.py", line 224, in finish
  File "C:\Python27\lib\site-packages\twisted\web\http.py", line 865, in finish
RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
2016-12-15 21:58:27,944 INFO     lbry

**Comment by tzarebczan** [comment]
UnknownNameError: Name jiggytom is unknown
2016-12-15 21:52:38,857 WARNING  lbrynet.core.Wallet:354: Got an error looking up a name: name is not claimed
2016-12-15 21:52:38,858 ERROR    lbrynet.lbrynet_daemon.Daemon:164: Failed to resolve name: Name jiggytom is unknown
UnknownNameError: Name jiggytom is unknown
2016-12-15 21:55:21,253 INFO     lbrynet.lbrynet_daemon.Daemon:1928: Got new wallet address: bN8afbh4QcT8BRHg8kdRevLBx5QvEw5YWx
2016-12-15 21:55:21,269 INFO     lbrynet.lbrynet_daemon.Daemon:1674: Publish: {u'file_path': u'C:\\Users\\thoma\\Downloads\\Zec miner 0.0.4b.zip', u'bid': 5, u'name': u'jiggytom', u'metadata': {u'license': u'Creative Commons Attribution 4.0 International', u'fee': {u'USD': {u'amount': 5, u'address': u'bN8afbh4QcT8BRHg8kdRevLBx5QvEw5YWx'}}, u'description': u'miner for windows and Linux. 330 sols/s on 1080 and 300 for 1070 well oced.', u'language': u'en', u'author': u'nvidiarepo', u'title': u'zcash miner .4 from ewbf', u'nsfw': False}}
2016-12-15 21:55:21,279 INFO     lbrynet.lbrynet_daemon.Daemon:2479: Resolving stream info for lbry://jiggytom
2016-12-15 21:55:21,598 WARNING  lbrynet.core.Wallet:354: Got an error looking up a name: name is not claimed
2016-12-15 21:55:21,598 INFO     lbrynet.lbrynet_daemon.Publisher:41: Starting publish for jiggytom
2016-12-15 21:55:21,790 INFO     lbrynet.lbryfile.EncryptedFileMetadataManager:226: Saving sd blob hash 6d7d5d63a4d6ee650b23ac392c77d9c5aa6a76b6c4ff78f85fef5a3560d34d30cc049995d7847ef1985c4f700ab0da12 to stream hash 43bca3df440f1518a29344eb19ce343db4383a0f48b30e26f4d460237af6f8e6b092acf830853b31073421276c47bf13
2016-12-15 21:55:23,305 ERROR    lbrynet.lbrynet_daemon.Publisher:164: An error occurred publishing Zec miner 0.0.4b.zip to jiggytom. Error: no such column: n.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\python\threadpool.py", line 246, in inContext
  File "C:\Python27\lib\site-packages\twisted\python\threadpool.py", line 262, in <lambda>
  File "C:\Python27\lib\site-packages\twisted\python\context.py", line 118, in callWithContext
  File "C:\Python27\lib\site-packages\twisted\python\context.py", line 81, in callWithContext
  File "C:\Python27\lib\site-packages\twisted\enterprise\adbapi.py", line 445, in _runInteraction
  File "C:\Python27\lib\site-packages\twisted\enterprise\adbapi.py", line 459, in _runQuery
OperationalError: no such column: n
2016-12-15 21:55:23,306 ERROR    lbrynet.lbrynet_daemon.auth.server:164: API Failure: Publish failed
Exception: Publish failed
2016-12-15 21:55:51,132

**Comment by jobevers** [comment]
@tzarebczan - I think you copied your data folder recently from one machine to different one; unfortunately there was a schema changed that happened with one of the internal databases recently.  I fear that maybe manually copying some stuff meant that the migration didn't happen and you have an old database.

As a TODO for us - the schema version should live in the database itself to prevent this.

**Comment by tzarebczan** [comment]
Ah okay.  Yea I didn't clear that out... I will.

**Comment by tzarebczan** [comment]
Your file has been published to LBRY at the address lbry://jiggytom!
You will now be taken to your My Files page, where your newly published file will be listed. The file will take a few minutes to appear for other LBRY users; until then it will be listed as "pending."

**Comment by tzarebczan** [comment]
And now the file is gone from published, see this in log:
2016-12-16 13:41:32,743 INFO     lbrynet.lbrynet_daemon.Daemon:2479: Resolving stream info for lbry://jiggytom
2016-12-16 13:41:33,164 WARNING  lbrynet.core.Wallet:354: Got an error looking up a name: name is not claimed
2016-12-16 13:41:34,181 INFO     lbrynet.lbrynet_daemon.Daemon:2479: Resolving stream info for lbry://jiggytom
2016-12-16 13:41:34,500 WARNING  lbrynet.core.Wallet:354: Got an error looking up a name: name is not claimed
2016-12-16 13:41:35,516 INFO     lbrynet.lbrynet_daemon.Daemon:2479: Resolving stream info for lbry://jiggytom
2016-12-16 13:41:35,937 WARNING  lbrynet.core.Wallet:354: Got an error looking up a name: name is not claimed
2016-12-16 13:41:36,983 INFO     lbrynet.lbrynet_daemon.Daemon:2479: Resolving stream info for lbry://jiggytom

**Comment by tzarebczan** [comment]
I eventually republished and it's back in My Files>Published.

**Comment by kaykurokawa** [comment]
Related issue https://github.com/lbryio/lbry-web-ui/issues/110

**Comment by lyoshenka** [comment]
@tzarebczan has this happened recently? I suspect it's fixed

**Comment by tzarebczan** [comment]
Nope, let's close for now.
