### ISSUE TITLE
reveal error - from publshed file. 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#344]
We're sorry that LBRY has encountered an error. This has been reported and we will investigate the problem.
API connection string: http://localhost:5279/lbryapi
Method: reveal
Parameters: [{"path":"C:\\Users\\xxxxxx\\Downloads\\xxxxx.zip"}]
Error code: 
Error message: 
Error data:

**Comment by tzarebczan** [comment]
2016-12-15 23:44:08,946 ERROR    lbrynet.lbrynet_daemon.auth.server:164: API Failure: [Error 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\python\threadpool.py", line 246, in inContext
  File "C:\Python27\lib\site-packages\twisted\python\threadpool.py", line 262, in <lambda>
  File "C:\Python27\lib\site-packages\twisted\python\context.py", line 118, in callWithContext
  File "C:\Python27\lib\site-packages\twisted\python\context.py", line 81, in callWithContext
  File "C:\Python27\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 959, in _execute_child
    startupinfo)

**Comment by tzarebczan** [comment]
This is still an issue @jobevers 

Happens in My Files, after you click the ellipses and go to "reveal file" . On windows, just tried in 0.7.12rc3

**Comment by lyoshenka** [comment]
Does this still happen in v0.10.0?

**Comment by lyoshenka** [comment]
No update, so I'm assuming its fixed. This should also most likely be handled in the UI.
