### ISSUE TITLE
couldn't open blob, timeout "

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#389]
2 issues:
1) Couldn't open that blob for some reason.
2) Timeout getting blob for cost est for lbry://thecountofmontecristobkup, using only key fee

2017-01-07 14:44:52,197 ERROR    lbrynet.reflector.client.blob:374: Error reflecting blob 6e0bf18049de97f40771a52efcd40f227870421e7770cd57705f8a65149b85c55d09c130e246a08d389199ec55e5a312: Couldn't open that blob for some reason. blob_hash: 6e0bf18049de97f40771a52efcd40f227870421e7770cd57705f8a65149b85c55d09c130e246a08d389199ec55e5a312
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 588, in _runCallbacks
  File "C:\projects\lbry\lbrynet\reflector\client\blob.py", line 144, in open_blob_for_reading
ValueError: Couldn't open that blob for some reason. blob_hash: 6e0bf18049de97f40771a52efcd40f227870421e7770cd57705f8a65149b85c55d09c130e246a08d389199ec55e5a312
2017-01-07 14:44:52,210 INFO     lbrynet.reflector.reupload:36: lbry://five is available
2017-01-07 14:44:52,210 INFO     lbrynet.reflector.reupload:36: lbry://dopeman is available
2017-01-07 14:44:52,213 ERROR    lbrynet.reflector.client.blob:374: Error reflecting blob cf032863d8a7222d6005cccaead5812cacdfaa81c41d7598b1e561d14e7f0ff7dd863ec611451d39d77fdaad98985384: Couldn't open that blob for some reason. blob_hash: cf032863d8a7222d6005cccaead5812cacdfaa81c41d7598b1e561d14e7f0ff7dd863ec611451d39d77fdaad98985384
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 588, in _runCallbacks
  File "C:\projects\lbry\lbrynet\reflector\client\blob.py", line 144, in open_blob_for_reading
ValueError: Couldn't open that blob for some reason. blob_hash: cf032863d8a7222d6005cccaead5812cacdfaa81c41d7598b1e561d14e7f0ff7dd863ec611451d39d77fdaad98985384
2017-01-07 14:44:52,216 ERROR    lbrynet.reflector.client.blob:374: Error reflecting blob e650f05acad5c3e86254bd0cd3f642b6c4baaf2cd9e6b8358a2a64eed08ddbb1daf398c9f33521ef335398df5ddc7efc: Couldn't open that blob for some reason. blob_hash: e650f05acad5c3e86254bd0cd3f642b6c4baaf2cd9e6b8358a2a64eed08ddbb1daf398c9f33521ef335398df5ddc7efc
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 588, in _runCallbacks
  File "C:\projects\lbry\lbrynet\reflector\client\blob.py", line 144, in open_blob_for_reading
ValueError: Couldn't open that blob for some reason. blob_hash: e650f05acad5c3e86254bd0cd3f642b6c4baaf2cd9e6b8358a2a64eed08ddbb1daf398c9f33521ef335398df5ddc7efc
2017-01-07 14:44:52,217 ERROR    lbrynet.reflector.client.blob:374: Error reflecting blob 285c351beb4f98264da44e02e70ef1b2112722513604ccde823918a81827d80aecc8b6157c694647d62edd41b9af2fa8: Couldn't open that blob for some reason. blob_hash: 285c351beb4f98264da44e02e70ef1b2112722513604ccde823918a81827d80aecc8b6157c694647d62edd41b9af2fa8
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 588, in _runCallbacks
  File "C:\projects\lbry\lbrynet\reflector\client\blob.py", line 144, in open_blob_for_reading
ValueError: Couldn't open that blob for some reason. blob_hash: 285c351beb4f98264da44e02e70ef1b2112722513604ccde823918a81827d80aecc8b6157c694647d62edd41b9af2fa8
2017-01-07 14:44:52,219 ERROR    lbrynet.reflector.client.blob:374: Error reflecting blob 8cdc562fe69326842e21a03e5fbed75f8b226d2df59ba0bb4f68af4b2c12c0a486e6b1504320f386d04a833965cd8733: Couldn't open that blob for some reason. blob_hash: 8cdc562fe69326842e21a03e5fbed75f8b226d2df59ba0bb4f68af4b2c12c0a486e6b1504320f386d04a833965cd8733
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 588, in _runCallbacks
  File "C:\projects\lbry\lbrynet\reflector\client\blob.py", line 144, in open_blob_for_reading
ValueError: Couldn't open that blob for some reason. blob_hash: 8cdc562fe69326842e21a03e5fbed75f8b226d2df59ba0bb4f68af4b2c12c0a486e6b1504320f386d04a833965cd8733
2017-01-07 14:44:52,227 INFO     lbrynet.lbrynet_daemon.ExchangeRateManager:152: Converting 5.000000 LBC to LBC
2017-01-07 14:44:52,233 INFO     lbrynet.lbrynet_daemon.ExchangeRateManager:152: Converting 5.000000 USD to LBC
2017-01-07 14:44:52,234 INFO     lbrynet.lbrynet_daemon.ExchangeRateManager:152: Converting 0.005500 BTC to LBC
2017-01-07 14:44:52,237 INFO     lbrynet.lbrynet_daemon.ExchangeRateManager:152: Converting 2.000000 USD to LBC
2017-01-07 14:44:52,239 INFO     lbrynet.lbrynet_daemon.ExchangeRateManager:152: Converting 0.002200 BTC to LBC
2017-01-07 14:44:52,243 INFO     lbrynet.lbrynet_daemon.ExchangeRateManager:152: Converting 1.000000 USD to LBC
2017-01-07 14:44:52,243 INFO     lbrynet.lbrynet_daemon.ExchangeRateManager:152: Converting 0.001100 BTC to LBC
2017-01-07 14:44:52,246 INFO     lbrynet.reflector.reupload:36: lbry://five is available
2017-01-07 14:44:52,247 INFO     lbrynet.reflector.reupload:36: lbry://five is available
2017-01-07 14:44:52,249 INFO     lbrynet.reflector.reupload:36: lbry://four is available
2017-01-07 14:44:52,250 INFO     lbrynet.reflector.reupload:36: lbry://five is available
2017-01-07 14:44:52,250 ERROR    lbrynet.reflector.client.blob:374: Error reflecting blob 5d2e75ac3dd3f46c2425b90410ffbdbb1daaa6855c87c30c9e6171ac3551056b63355bded1eacdbc8cc3d0e9c2e585a1: Couldn't open that blob for some reason. blob_hash: 5d2e75ac3dd3f46c2425b90410ffbdbb1daaa6855c87c30c9e6171ac3551056b63355bded1eacdbc8cc3d0e9c2e585a1
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 588, in _runCallbacks
  File "C:\projects\lbry\lbrynet\reflector\client\blob.py", line 144, in open_blob_for_reading
ValueError: Couldn't open that blob for some reason. blob_hash: 5d2e75ac3dd3f46c2425b90410ffbdbb1daaa6855c87c30c9e6171ac3551056b63355bded1eacdbc8cc3d0e9c2e585a1
2017-01-07 14:44:52,253 ERROR    lbrynet.reflector.client.blob:374: Error reflecting blob 6f8416ed7672e5b1d42ed8dbee757acae0e187b220ccdaf2a57617c9285ff2bfcda08c189b30f7028f9ae058f2295cb2: Couldn't open that blob for some reason. blob_hash: 6f8416ed7672e5b1d42ed8dbee757acae0e187b220ccdaf2a57617c9285ff2bfcda08c189b30f7028f9ae058f2295cb2
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 588, in _runCallbacks
  File "C:\projects\lbry\lbrynet\reflector\client\blob.py", line 144, in open_blob_for_reading
ValueError: Couldn't open that blob for some reason. blob_hash: 6f8416ed7672e5b1d42ed8dbee757acae0e187b220ccdaf2a57617c9285ff2bfcda08c189b30f7028f9ae058f2295cb2
2017-01-07 14:44:52,253 ERROR    lbrynet.reflector.client.blob:374: Error reflecting blob 042ac1dc1a1c2da77dde844a98aec2a22e2e51ec39e267c81c0e9f340161a95ecbacb41b92961bf9da86a0606046d95c: Couldn't open that blob for some reason. blob_hash: 042ac1dc1a1c2da77dde844a98aec2a22e2e51ec39e267c81c0e9f340161a95ecbacb41b92961bf9da86a0606046d95c
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 588, in _runCallbacks
  File "C:\projects\lbry\lbrynet\reflector\client\blob.py", line 144, in open_blob_for_reading
ValueError: Couldn't open that blob for some reason. blob_hash: 042ac1dc1a1c2da77dde844a98aec2a22e2e51ec39e267c81c0e9f340161a95ecbacb41b92961bf9da86a0606046d95c
2017-01-07 14:44:52,253 ERROR    lbrynet.reflector.client.blob:374: Error reflecting blob 8f0ee0e2fe6f5a12f812e99effb25caf956e88a3e57b9df68c4cecbaaa9a189c1ba7e4db4ca825feedf333f94265950a: Couldn't open that blob for some reason. blob_hash: 8f0ee0e2fe6f5a12f812e99effb25caf956e88a3e57b9df68c4cecbaaa9a189c1ba7e4db4ca825feedf333f94265950a
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 588, in _runCallbacks
  File "C:\projects\lbry\lbrynet\reflector\client\blob.py", line 144, in open_blob_for_reading
ValueError: Couldn't open that blob for some reason. blob_hash: 8f0ee0e2fe6f5a12f812e99effb25caf956e88a3e57b9df68c4cecbaaa9a189c1ba7e4db4ca825feedf333f94265950a
2017-01-07 14:44:52,256 ERROR    lbrynet.reflector.client.blob:374: Error reflecting blob 9b42adab4f9154e10ef2ec610f730c3a0d9e6d0be1bec772ac5334f345bc3d08467beb254fe9b2ac2965fc819341aa51: Couldn't open that blob for some reason. blob_hash: 9b42adab4f9154e10ef2ec610f730c3a0d9e6d0be1bec772ac5334f345bc3d08467beb254fe9b2ac2965fc819341aa51
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 588, in _runCallbacks
  File "C:\projects\lbry\lbrynet\reflector\client\blob.py", line 144, in open_blob_for_reading
ValueError: Couldn't open that blob for some reason. blob_hash: 9b42adab4f9154e10ef2ec610f730c3a0d9e6d0be1bec772ac5334f345bc3d08467beb254fe9b2ac2965fc819341aa51
2017-01-07 14:44:52,256 ERROR    lbrynet.reflector.client.blob:374: Error reflecting blob 047b53bcd1184db27969ed69c75f11c6dc521c70230ff27482e42448ec391261f4f95bbdeb91bea9f881b7d5643b9b43: Couldn't open that blob for some reason. blob_hash: 047b53bcd1184db27969ed69c75f11c6dc521c70230ff27482e42448ec391261f4f95bbdeb91bea9f881b7d5643b9b43
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 588, in _runCallbacks
  File "C:\projects\lbry\lbrynet\reflector\client\blob.py", line 144, in open_blob_for_reading
ValueError: Couldn't open that blob for some reason. blob_hash: 047b53bcd1184db27969ed69c75f11c6dc521c70230ff27482e42448ec391261f4f95bbdeb91bea9f881b7d5643b9b43
2017-01-07 14:44:52,259 ERROR    lbrynet.reflector.client.blob:374: Error reflecting blob 8e877083818a51734b2722e7f53b3352255feca8c38be619471ef1af730b272f295ff1a774cf28f71dfad7b3a249e747: Couldn't open that blob for some reason. blob_hash: 8e877083818a51734b2722e7f53b3352255feca8c38be619471ef1af730b272f295ff1a774cf28f71dfad7b3a249e747
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 588, in _runCallbacks
  File "C:\projects\lbry\lbrynet\reflector\client\blob.py", line 144, in open_blob_for_reading
ValueError: Couldn't open that blob for some reason. blob_hash: 8e877083818a51734b2722e7f53b3352255feca8c38be619471ef1af730b272f295ff1a774cf28f71dfad7b3a249e747
2017-01-07 14:44:52,259 ERROR    lbrynet.reflector.client.blob:374: Error reflecting blob 2d1a78159a6da90f704daa96a44fa68e71340da9ab8d17943148819273e23da37e23b6ffe0794448225c199e97a83bf4: Couldn't open that blob for some reason. blob_hash: 2d1a78159a6da90f704daa96a44fa68e71340da9ab8d17943148819273e23da37e23b6ffe0794448225c199e97a83bf4
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 588, in _runCallbacks
  File "C:\projects\lbry\lbrynet\reflector\client\blob.py", line 144, in open_blob_for_reading
ValueError: Couldn't open that blob for some reason. blob_hash: 2d1a78159a6da90f704daa96a44fa68e71340da9ab8d17943148819273e23da37e23b6ffe0794448225c199e97a83bf4
2017-01-07 14:44:52,265 INFO     lbrynet.reflector.reupload:36: lbry://smlawncare is available
2017-01-07 14:44:52,266 INFO     lbrynet.reflector.reupload:36: lbry://three is available
2017-01-07 14:44:52,267 INFO     lbrynet.reflector.reupload:36: lbry://cinemasix is available
2017-01-07 14:44:52,270 INFO     lbrynet.reflector.reupload:36: lbry://jiggytom is available
2017-01-07 14:44:52,273 INFO     lbrynet.reflector.reupload:36: lbry://jiggytom is available
2017-01-07 14:44:52,275 INFO     lbrynet.reflector.reupload:36: lbry://positivereturnsinnegativerates is available
2017-01-07 14:44:52,276 INFO     lbrynet.reflector.reupload:36: lbry://itsadisaster is available
2017-01-07 14:44:52,276 INFO     lbrynet.reflector.reupload:36: lbry://one is available
2017-01-07 14:44:52,282 INFO     lbrynet.lbrynet_daemon.ExchangeRateManager:152: Converting 10.000000 USD to LBC
2017-01-07 14:44:52,282 INFO     lbrynet.lbrynet_daemon.ExchangeRateManager:152: Converting 0.011000 BTC to LBC
2017-01-07 14:44:52,290 INFO     lbrynet.lbrynet_daemon.ExchangeRateManager:152: Converting 250.000000 LBC to LBC
2017-01-07 14:44:57,150 INFO     lbrynet.lbrynet_daemon.ExchangeRateManager:152: Converting 1.000000 USD to LBC
2017-01-07 14:44:57,150 INFO     lbrynet.lbrynet_daemon.ExchangeRateManager:152: Converting 0.001100 BTC to LBC
2017-01-07 14:44:57,165 INFO     lbrynet.lbrynet_daemon.ExchangeRateManager:152: Converting 5.000000 USD to LBC
2017-01-07 14:44:57,165 INFO     lbrynet.lbrynet_daemon.ExchangeRateManager:152: Converting 0.005500 BTC to LBC
2017-01-07 14:45:50,043 INFO     lbrynet.lbrynet_daemon.Daemon:1186: Get version info: {"lbrynet_version": "0.7.12", "platform": "Windows-10-10.0.14393", "os_system": "Windows", "remote_lbryum": "2.7.1", "os_release": "10", "lbryum_version": "2.7.1", "ui_version": "b78b644826d0077417bfa3b35dcd17db4b1faedc", "lbrynet_update_available": false, "remote_lbrynet": "0.7.12", "lbryum_update_available": false}
2017-01-07 14:45:50,053 INFO     lbrynet.lbrynet_daemon.Daemon:1324: Get balance
2017-01-07 14:45:50,061 INFO     lbrynet.lbrynet_daemon.Daemon:1324: Get balance
2017-01-07 14:45:50,062 INFO     lbrynet.lbrynet_daemon.Daemon:1136: Get startup notice
2017-01-07 14:45:54,934 INFO     lbrynet.lbrynet_daemon.Daemon:2475: Resolving stream info for lbry://teamfortress2
2017-01-07 14:45:54,937 INFO     lbrynet.lbrynet_daemon.Daemon:2475: Resolving stream info for lbry://pillar
2017-01-07 14:45:54,940 INFO     lbrynet.lbrynet_daemon.Daemon:2475: Resolving stream info for lbry://idiocracy
2017-01-07 14:45:54,941 INFO     lbrynet.lbrynet_daemon.Daemon:2475: Resolving stream info for lbry://T
2017-01-07 14:45:54,944 INFO     lbrynet.lbrynet_daemon.Daemon:2475: Resolving stream info for lbry://meetlbry1
2017-01-07 14:45:54,947 INFO     lbrynet.lbrynet_daemon.Daemon:2475: Resolving stream info for lbry://thecountofmontecristobkup
2017-01-07 14:45:55,894 INFO     lbrynet.lbrynet_daemon.ExchangeRateManager:152: Converting 1.100000 LBC to LBC
2017-01-07 14:45:55,898 INFO     lbrynet.lbrynet_daemon.Daemon:2475: Resolving stream info for lbry://v4vendettabkup
2017-01-07 14:45:55,908 INFO     lbrynet.lbrynet_daemon.Daemon:2475: Resolving stream info for lbry://theadventuresofsherlockholmes
2017-01-07 14:45:55,969 INFO     lbrynet.lbrynet_daemon.ExchangeRateManager:152: Converting 0.890000 USD to LBC
2017-01-07 14:45:55,969 INFO     lbrynet.lbrynet_daemon.ExchangeRateManager:152: Converting 0.000979 BTC to LBC
2017-01-07 14:45:55,973 INFO     lbrynet.lbrynet_daemon.Daemon:2475: Resolving stream info for lbry://themetamorphosis
2017-01-07 14:46:01,009 INFO     lbrynet.core.client.ConnectionManager:54: Abruptly closing a connection to 198.199.87.180:3333 due to downloading being paused
2017-01-07 14:46:01,009 WARNING  lbrynet.lbrynet_daemon.Daemon:938: Timeout getting blob for cost est for lbry://thecountofmontecristobkup, using only key fee

**Comment by lyoshenka** [comment]
Does this still happen in v0.10.0?

**Comment by lyoshenka** [comment]
No update, so I'm assuming this is fixed.
