### ISSUE TITLE
Error when stopping a file

### ISSUE THREAD

**Issue by jobevers** [lbryio/lbry#400]
When trying to stop a file:

```
Traceback (most recent call last):
  File "/Users/jobevers/.virtualenvs/lbry/lib/python2.7/site-packages/twisted/internet/defer.py", line 434, in errback
    self._startRunCallbacks(fail)
  File "/Users/jobevers/.virtualenvs/lbry/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
  File "/Users/jobevers/.virtualenvs/lbry/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Users/jobevers/.virtualenvs/lbry/lib/python2.7/site-packages/twisted/internet/defer.py", line 1184, in gotResult
    _inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
  File "/Users/jobevers/.virtualenvs/lbry/lib/python2.7/site-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/Users/jobevers/.virtualenvs/lbry/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/Users/jobevers/projects/lbryio/lbry/lbrynet/lbrynet_daemon/Daemon.py", line 1592, in jsonrpc_stop_lbry_file
    yield self.lbry_file_manager.toggle_lbry_file_running(lbry_file)
  File "/Users/jobevers/.virtualenvs/lbry/lib/python2.7/site-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/Users/jobevers/.virtualenvs/lbry/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/Users/jobevers/projects/lbryio/lbry/lbrynet/lbryfilemanager/EncryptedFileDownloader.py", line 103, in stop
    yield EncryptedFileDownloader.stop(self, err=err)
  File "/Users/jobevers/.virtualenvs/lbry/lib/python2.7/site-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/Users/jobevers/.virtualenvs/lbry/lib/python2.7/site-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/Users/jobevers/.virtualenvs/lbry/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/Users/jobevers/.virtualenvs/lbry/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/Users/jobevers/projects/lbryio/lbry/lbrynet/lbryfile/client/EncryptedFileDownloader.py", line 256, in close_file
    os.remove(name)
exceptions.OSError: [Errno 2] No such file or directory: '/Users/jobevers/Downloads/-7.target-file'
```

Its probably worth noting that the original filename was `target-file` (without an extension)

**Comment by lyoshenka** [comment]
dont think this happens anymore
