### ISSUE TITLE
Error after changing status

### ISSUE THREAD

**Issue by jobevers** [lbryio/lbry#401]
```
Traceback (most recent call last):
  File "/Users/jobevers/.virtualenvs/lbry/lib/python2.7/site-packages/twisted/internet/defer.py", line 1184, in gotResult
    _inlineCallbacks(r, g, deferred)
  File "/Users/jobevers/.virtualenvs/lbry/lib/python2.7/site-packages/twisted/internet/defer.py", line 1174, in _inlineCallbacks
    deferred.errback()
  File "/Users/jobevers/.virtualenvs/lbry/lib/python2.7/site-packages/twisted/internet/defer.py", line 434, in errback
    self._startRunCallbacks(fail)
  File "/Users/jobevers/.virtualenvs/lbry/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/Users/jobevers/.virtualenvs/lbry/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Users/jobevers/projects/lbryio/lbry/lbrynet/lbryfilemanager/EncryptedFileManager.py", line 184, in ignore_stopped
    return wait_for_finished(lbry_file)
  File "/Users/jobevers/projects/lbryio/lbry/lbrynet/lbryfilemanager/EncryptedFileManager.py", line 177, in wait_for_finished
    if count <= 0 or lbry_file.saving_status is False:
exceptions.AttributeError: 'ManagedEncryptedFileDownloader' object has no attribute 'saving_status'
```

There is a chance that this is due to some code change I made recently on my branch that aren't on master - but I'm busy debugging another bug and wanted to make sure I recorded this one.

**Comment by jobevers** [comment]
Yep, totally my fault.
