### ISSUE TITLE
no_such_table during init (OSX 10.12.2)

### ISSUE THREAD

**Issue by Ambros94** [lbryio/lbry#411]
I compiled both versions v0.8.0rc0 and v0.7.12 on on OSX 10.12.2 (Sierra) following INSTALL.md instructions. I'm using python virtual environment any python 2.7.

This is the error i receive when I run  `lbrynet-daemon --log-to-console`

```
Starting lbrynet-daemon from command line
To view activity, view the log file here: /Users/lambrosini/Library/Application Support/LBRY/lbrynet.log
Web UI is available at http://localhost:5279
JSONRPC API is available at http://localhost:5279/lbryapi
To quit press ctrl-c or call 'stop' via the API

Closing lbrynet-daemon
 (lbry-venv) ~/PycharmProjects/lbry-0.8.0rc0  lbrynet-daemon --log-to-console
2017-01-16 10:52:56,293 INFO     lbrynet.lbrynet_daemon.DaemonControl:83: Starting lbrynet-daemon from command line
2017-01-16 10:52:57,345 INFO     lbrynet.lbrynet_daemon.DaemonServer:56: Using non-authenticated API
2017-01-16 10:52:57,346 INFO     twisted:154: Site starting on 5279
2017-01-16 10:52:57,347 INFO     twisted:154: Starting factory <twisted.web.server.Site instance at 0x111976368>
2017-01-16 10:52:57,347 INFO     lbrynet.lbrynet_daemon.Daemon:315: Starting lbrynet-daemon
2017-01-16 10:52:57,895 INFO     lbrynet.lbrynet_daemon.Daemon:165: remote lbrynet 0.7.12 > local lbrynet 0.8.0rc0 = False
2017-01-16 10:52:58,341 INFO     lbrynet.lbrynet_daemon.Daemon:150: remote lbryum 2.7.3 > local lbryum 2.7.3 = False
2017-01-16 10:52:58,341 INFO     lbrynet.lbrynet_daemon.ExchangeRateManager:142: Starting exchange rate manager
2017-01-16 10:52:58,702 INFO     lbrynet.lbrynet_daemon.UIManager:91: Checking for updates for UI branch: master
2017-01-16 10:52:59,195 INFO     lbrynet.lbrynet_daemon.UIManager:125: UI is up to date
2017-01-16 10:53:00,138 INFO     lbrynet.lbrynet_daemon.Daemon:349: Platform: {"lbrynet_version": "0.8.0rc0", "platform": "Darwin-16.3.0-x86_64-i386-64bit", "os_system": "Darwin", "python_version": "2.7.10", "os_release": "16.3.0", "ip": "**********", "lbryum_version": "2.7.3", "ui_version": "b78b644826d0077417bfa3b35dcd17db4b1faedc", "processor": "i386", "build": "dev"}
2017-01-16 10:53:00,142 INFO     lbrynet.lbrynet_daemon.Daemon:636: Loading databases
2017-01-16 10:53:00,144 INFO     lbrynet.lbrynet_daemon.Daemon:661: Upgrading your databases
2017-01-16 10:53:00,144 INFO     lbrynet.db_migrator.migrate1to2:9: Doing the migration
2017-01-16 10:53:00,145 INFO     twisted:154: "127.0.0.1" - - [16/Jan/2017:09:53:00 +0000] "GET / HTTP/1.1" 200 1509 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0.2 Safari/602.3.12"
2017-01-16 10:53:00,146 ERROR    lbrynet.lbrynet_daemon.DaemonControl:134: Failed to startup
Traceback (most recent call last):
  File "/Users/lambrosini/PycharmProjects/lbry-0.8.0rc0/lbry-venv/lib/python2.7/site-packages/lbrynet/lbrynet_daemon/DaemonControl.py", line 131, in start_server_and_listen
    yield daemon_server.start(use_auth, launchui)
  File "/Users/lambrosini/PycharmProjects/lbry-0.8.0rc0/lbry-venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/Users/lambrosini/PycharmProjects/lbry-0.8.0rc0/lbry-venv/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/Users/lambrosini/PycharmProjects/lbry-0.8.0rc0/lbry-venv/lib/python2.7/site-packages/lbrynet/lbrynet_daemon/DaemonServer.py", line 48, in start
    yield self._api.setup(launch_ui)
  File "/Users/lambrosini/PycharmProjects/lbry-0.8.0rc0/lbry-venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/Users/lambrosini/PycharmProjects/lbry-0.8.0rc0/lbry-venv/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/Users/lambrosini/PycharmProjects/lbry-0.8.0rc0/lbry-venv/lib/python2.7/site-packages/lbrynet/lbrynet_daemon/Daemon.py", line 329, in setup
    yield self._check_db_migration()
  File "/Users/lambrosini/PycharmProjects/lbry-0.8.0rc0/lbry-venv/lib/python2.7/site-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/Users/lambrosini/PycharmProjects/lbry-0.8.0rc0/lbry-venv/lib/python2.7/site-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/Users/lambrosini/PycharmProjects/lbry-0.8.0rc0/lbry-venv/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/Users/lambrosini/PycharmProjects/lbry-0.8.0rc0/lbry-venv/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/Users/lambrosini/PycharmProjects/lbry-0.8.0rc0/lbry-venv/lib/python2.7/site-packages/lbrynet/db_migrator/dbmigrator.py", line 9, in migrate_db
    do_migration(db_dir)
  File "/Users/lambrosini/PycharmProjects/lbry-0.8.0rc0/lbry-venv/lib/python2.7/site-packages/lbrynet/db_migrator/migrate1to2.py", line 10, in do_migration
    migrate_blockchainname_db(db_dir)
  File "/Users/lambrosini/PycharmProjects/lbry-0.8.0rc0/lbry-venv/lib/python2.7/site-packages/lbrynet/db_migrator/migrate1to2.py", line 37, in migrate_blockchainname_db
    claim_metadata = file_cursor.execute("select * from claim_ids").fetchall()
OperationalError: no such table: claim_ids
2017-01-16 10:53:00,151 INFO     lbrynet.lbrynet_daemon.Daemon:552: Closing lbrynet session
2017-01-16 10:53:00,151 INFO     lbrynet.lbrynet_daemon.Daemon:553: Status at time of shutdown: loading_db
2017-01-16 10:53:01,164 INFO     lbrynet.lbrynet_daemon.ExchangeRateManager:147: Stopping exchange rate manager
2017-01-16 10:53:01,164 INFO     twisted:154: (TCP Port 5279 Closed)
2017-01-16 10:53:01,165 INFO     twisted:154: Stopping factory <twisted.web.server.Site instance at 0x111976368>
2017-01-16 10:53:01,165 INFO     twisted:154: Main loop terminated.
```

**Comment by jobevers** [comment]
Do you get this error if you reset the LBRY folder: `mv ~/Library/Application Support/LBRY ~/LBRY_backup` and then retry?

**Comment by Ambros94** [comment]
I've tried with the 7.x.x version and It was still there, but it works with the last version (v0.8.0rc2-2-g91d673a).
