### ISSUE TITLE
Error while publishing

### ISSUE THREAD

**Issue by jobevers** [lbryio/lbry#422]
```
2017-01-17 20:06:58,124 ERROR    lbrynet.lbrynet_daemon.Publisher:79: An error occurred publishing None to aabbccde: 'claim_id'
Traceback (most recent call last):
  File "/Users/jobevers/.virtualenvs/lbry/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Users/jobevers/projects/lbryio/lbry/lbrynet/lbrynet_daemon/Publisher.py", line 149, in set_claim_out
    claim_out['claim_id'], claim_out['fee'])
KeyError: 'claim_id'
2017-01-17 20:06:58,130 ERROR    lbrynet.lbrynet_daemon.Publisher:411: Failed to run callback
Traceback (most recent call last):
  File "/Users/jobevers/projects/lbryio/lbry/lbrynet/core/log_support.py", line 403, in _fail
    return callback(err, *args, **kwargs)
  File "/Users/jobevers/projects/lbryio/lbry/lbrynet/lbrynet_daemon/Publisher.py", line 170, in _throw_publish_error
    raise Exception("Publish failed")
Exception: Publish failed
2017-01-17 20:06:58,134 ERROR    lbrynet.lbrynet_daemon.auth.server:214: Failed to process publish: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/Users/jobevers/.virtualenvs/lbry/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Users/jobevers/projects/lbryio/lbry/lbrynet/lbrynet_daemon/Daemon.py", line 1789, in <lambda>
    d.addCallback(lambda claim_out: self._add_to_pending_claims(name, claim_out))
  File "/Users/jobevers/projects/lbryio/lbry/lbrynet/lbrynet_daemon/Daemon.py", line 398, in _add_to_pending_claims
    txid = claim_out['txid']
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by jobevers** [comment]
Fixed
