### ISSUE TITLE
dht contact bug

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry#436]
```
2017-01-23 14:59:11,554 CRITICAL twisted:154: Unhandled Error
Traceback (most recent call last):
  File "/home/grin/.virtualenvs/lbry/local/lib/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/grin/.virtualenvs/lbry/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/grin/.virtualenvs/lbry/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/home/grin/.virtualenvs/lbry/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
--- <exception caught here> ---
  File "/home/grin/.virtualenvs/lbry/local/lib/python2.7/site-packages/twisted/internet/udp.py", line 248, in doRead
    self.protocol.datagramReceived(data, addr)
  File "/home/grin/code/lbry/lbry/lbrynet/dht/protocol.py", line 158, in datagramReceived
    self._node.addContact(remoteContact)
  File "/home/grin/code/lbry/lbry/lbrynet/dht/node.py", line 385, in addContact
    self._routingTable.addContact(contact)
  File "/home/grin/code/lbry/lbry/lbrynet/dht/routingtable.py", line 403, in addContact
    self._replacementCache[bucketIndex].append(contact)
exceptions.KeyError: 0
```

**Comment by lyoshenka** [comment]
@kaykurokawa is this fixed?

**Comment by mlncn** [comment]
I'm getting this also (over and over and over again, heh).  It was using as much CPU as it could grab and a substantial chunk of RAM too (and i have 16 gigs).

I had installed per the https://lbry.io/quickstart/install instructions for Linux.

Started the lbrynet-daemon and it had been running since, with not deleterious effects that i was aware of.

I had suspended the computer and changed locations a few times already with no incident.  The only possible thing i can think of now being different is that it took a while to reconnect to the wifi network this time.  Maybe this error could be triggered by not having network access for a time?

**Comment by mlncn** [comment]
It was running at full resource hog mode for about an hour before i ctrl+Cd it.  There was one other set of error messages i got (showing much more occasionally than the constant of the error lyoshenka already reported) that is not reported yet, "lbrynet.dht.protocol:262: Can't send data to dht: EWOULDBLOCK".  For those who want the full flavor, here's a slice of the errors it kept spitting out:

```
2017-03-20 18:40:29,109 CRITICAL twisted:154: Unhandled Error
Traceback (most recent call last):
  File "site-packages/twisted/python/log.py", line 86, in callWithContext
    
  File "site-packages/twisted/python/context.py", line 118, in callWithContext
    
  File "site-packages/twisted/python/context.py", line 81, in callWithContext
    
  File "site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    
--- <exception caught here> ---
  File "site-packages/twisted/internet/udp.py", line 249, in doRead
    
  File "site-packages/lbrynet/dht/protocol.py", line 160, in datagramReceived
    
  File "site-packages/lbrynet/dht/node.py", line 385, in addContact
    
  File "site-packages/lbrynet/dht/routingtable.py", line 403, in addContact
    
exceptions.KeyError: 0

2017-03-20 18:40:29,224 WARNING  lbrynet.dht.protocol:262: Can't send data to dht: EWOULDBLOCK
2017-03-20 18:40:29,224 WARNING  lbrynet.dht.protocol:262: Can't send data to dht: EWOULDBLOCK
2017-03-20 18:40:29,225 WARNING  lbrynet.dht.protocol:262: Can't send data to dht: EWOULDBLOCK
2017-03-20 18:40:29,225 WARNING  lbrynet.dht.protocol:262: Can't send data to dht: EWOULDBLOCK
2017-03-20 18:40:29,225 WARNING  lbrynet.dht.protocol:262: Can't send data to dht: EWOULDBLOCK
2017-03-20 18:40:29,226 WARNING  lbrynet.dht.protocol:262: Can't send data to dht: EWOULDBLOCK
2017-03-20 18:40:29,226 WARNING  lbrynet.dht.protocol:262: Can't send data to dht: EWOULDBLOCK
2017-03-20 18:40:29,227 WARNING  lbrynet.dht.protocol:262: Can't send data to dht: EWOULDBLOCK
2017-03-20 18:40:29,227 WARNING  lbrynet.dht.protocol:262: Can't send data to dht: EWOULDBLOCK
2017-03-20 18:40:29,227 WARNING  lbrynet.dht.protocol:262: Can't send data to dht: EWOULDBLOCK
Unhandled Error
Traceback (most recent call last):
  File "site-packages/twisted/python/log.py", line 86, in callWithContext
    
  File "site-packages/twisted/python/context.py", line 118, in callWithContext
    
  File "site-packages/twisted/python/context.py", line 81, in callWithContext
    
  File "site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    
--- <exception caught here> ---
  File "site-packages/twisted/internet/udp.py", line 249, in doRead
    
  File "site-packages/lbrynet/dht/protocol.py", line 160, in datagramReceived
    
  File "site-packages/lbrynet/dht/node.py", line 385, in addContact
    
  File "site-packages/lbrynet/dht/routingtable.py", line 403, in addContact
    
exceptions.KeyError: 0

2017-03-20 18:40:29,264 CRITICAL twisted:154: Unhandled Error
Traceback (most recent call last):
  File "site-packages/twisted/python/log.py", line 86, in callWithContext
    
  File "site-packages/twisted/python/context.py", line 118, in callWithContext
    
  File "site-packages/twisted/python/context.py", line 81, in callWithContext
    
  File "site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    
--- <exception caught here> ---
  File "site-packages/twisted/internet/udp.py", line 249, in doRead
    
  File "site-packages/lbrynet/dht/protocol.py", line 160, in datagramReceived
    
  File "site-packages/lbrynet/dht/node.py", line 385, in addContact
    
  File "site-packages/lbrynet/dht/routingtable.py", line 403, in addContact
    
exceptions.KeyError: 0

```

**Comment by mlncn** [comment]
Killing the daemon gave the "Can't stop reactor that isn't running" error message mentioned in #544, among other output, but i doubt any of that output is relevant to this issue.  Let me know if you want it though!

**Comment by lyoshenka** [comment]
@jimmykiselak any idea what this is, before we dig deeper?

**Comment by jimmykiselak** [comment]
@lyoshenka nope, haven't seen that before.
