### ISSUE TITLE
test_double_download fails occasionally 

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbry#527]
test_double_download under test_misc fails occasionally, likely due to some race condition. Below is the error log. I believe the problem happens due to _delete_blobs_marked_for_deletion() is called in manage() when db_conn may be closed already. 

[ERROR]

Traceback (most recent call last):

  File "/home/travis/build/lbryio/lbry/lbrynet/core/BlobManager.py", line 200, in delete_from_db

    d = self._delete_blobs_from_db(b_hs)

  File "/home/travis/build/lbryio/lbry/lbrynet/core/sqlite_helpers.py", line 19, in wrapper

    d = f(*args, **kwargs)

  File "/home/travis/build/lbryio/lbry/lbrynet/core/BlobManager.py", line 309, in _delete_blobs_from_db

    return self.db_conn.runInteraction(delete_blobs)

exceptions.AttributeError: 'NoneType' object has no attribute 'runInteraction'

tests.functional.test_misc.TestTransfer.test_double_download

**Comment by kaykurokawa** [comment]
Example of build failing here: https://travis-ci.org/lbryio/lbry/builds/209860687

**Comment by kaykurokawa** [comment]
test_last_blob_retrieval also fails occasionally , like for related reason. Error below:

Traceback (most recent call last):

  File "/home/travis/build/lbryio/lbry/venv/local/lib/python2.7/site-packages/twisted/enterprise/adbapi.py", line 474, in _runInteraction

    conn.rollback()

  File "/home/travis/build/lbryio/lbry/venv/local/lib/python2.7/site-packages/twisted/enterprise/adbapi.py", line 52, in rollback

    self._connection.rollback()

sqlite3.OperationalError: cannot rollback - no transaction is active

tests.functional.test_misc.TestTransfer.test_last_blob_retrieval

https://travis-ci.org/lbryio/lbry/builds/215692820

**Comment by jackrobison** [comment]
fixed in https://github.com/lbryio/lbry/pull/682
