### ISSUE TITLE
LBRY is not working to stream files

### ISSUE THREAD

**Issue by starrychloe** [lbryio/lbry#53]
I clicked a link and launched LBRY, but it only opened this web page and is stuck for the longest time. 

https://ipfs.pics/QmaRNDdCS8nwuFYS427zS8FHEhY9fKG6oR45gDmi8X8h3K
![lbry-disaster](https://ipfs.pics/ipfs/QmaRNDdCS8nwuFYS427zS8FHEhY9fKG6oR45gDmi8X8h3K)

https://ipfs.pics/QmWFt5rK45RvJnyjhQsJRJBek9MQAofkjnkmF34baa3RXt
![lbry-what](https://ipfs.pics/ipfs/QmWFt5rK45RvJnyjhQsJRJBek9MQAofkjnkmF34baa3RXt)

Ubuntu 14.04.4 LTS

**Comment by jackrobison** [comment]
what was your balance?

**Comment by starrychloe** [comment]
What's a balance and how do I check it?

**Comment by starrychloe** [comment]
Notice it doesn't even work for 'what', which I assume is free.

**Comment by starrychloe** [comment]
Here is a log from starting the daemon. It gives several warnings.

```
$ lbrynet-daemon --log-to-console
/usr/local/lib/python2.7/dist-packages/setuptools-4.0.1-py2.7.egg/pkg_resources.py:1045: UserWarning: /home/joe/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
:0: UserWarning: You do not have a working installation of the service_identity module: 'No module named service_identity'.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module and a recent enough pyOpenSSL to support it, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
INFO:lbrynet.lbrynet_daemon.LBRYDaemonControl:Starting lbrynet-daemon from command line
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:Loaded lbrynet-daemon configuration
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:Using wallet type lbrycrd specified from command line
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:Loaded claim info cache
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:Using lbrycrd.conf found at /home/joe/.lbrycrd/lbrycrd.conf
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:[2016-07-05 12:31:59.236935] Starting lbrynet-daemon
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:remote lbrynet 0.3.1 > local lbrynet 0.3.1 = False
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:remote lbryum 2.6.0.6 > local lbryum 2.6.0.6 = False
INFO:lbrynet.lbrynet_daemon.LBRYUIManager:Checking for updates for UI branch: master
INFO:lbrynet.lbrynet_daemon.LBRYUIManager:UI is up to date
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:Platform: {"ip": "208.120.122.29", "python_version: ": "2.7.6", "os_system": "Linux", "lbrynet_version: ": "0.3.1", "os_release": "3.13.0-91-generic", "platform": "Linux-3.13.0-91-generic-x86_64-with-Ubuntu-14.04-trusty", "lbryum_version: ": "2.6.0.6", "ui_version": "49eaa25423aaaa2ed317d747c152b67608c14183", "processor": "x86_64"}
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:Loading databases...
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:Generated new LBRY ID: 8egG55b9rrxP6EuTmKjVA3CPHjC3Q6Z4S5APKaw4jXLCeZ6FgeynmjECwS6vnVRnNc
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:Using lbrycrd wallet
INFO:lbryalert.lbrynet.core.LBRYWallet:Connecting to lbrycrdd...

INFO:lbryalert.lbrynet.core.LBRYWallet:Connected to lbrycrdd.
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:Starting balance: 0E-8
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): lbry.io


/usr/local/lib/python2.7/dist-packages/requests-2.10.0-py2.7.egg/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/requests-2.10.0-py2.7.egg/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:[2016-07-05 12:32:14.266474] Started lbrynet-daemon


```

**Comment by starrychloe** [comment]
Here is the log from when I reloaded the page http://localhost://5279/?watch=what . It just repeats that it's looking for the file and can't find it, until I killed it.


```
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:[2016-07-05 12:38:10.793891] daemon status: {'progress': None, 'message': 'Started lbrynet', 'code': 'started', 'is_lagging': None, 'problem_code': None}
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:[2016-07-05 12:38:10.867174] Get version info: {"lbrynet_version": "0.3.1", "platform": "Linux-3.13.0-91-generic-x86_64-with-Ubuntu-14.04-trusty", "os_system": "Linux", "remote_lbryum": "2.6.0.6", "os_release": "3.13.0-91-generic", "lbryum_version": "2.6.0.6", "ui_version": null, "remote_lbrynet": "0.3.1"}
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:[2016-07-05 12:38:10.889421] Returning cached stream info for lbry://what
INFO:lbrynet.lbrynet_daemon.LBRYDownloader:Download lbry://what status changed to downloading_metadata
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:[2016-07-05 12:38:10.895451] Returning cached stream info for lbry://what
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:Did not find LBRY file for name: what
...
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:[2016-07-05 12:38:22.839720] Returning cached stream info for lbry://what
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:Did not find LBRY file for name: what
^CINFO:lbrynet.lbrynet_daemon.LBRYDaemon:Closing lbrynet session
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:Status at time of shutdown: started
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): lbry.io
/usr/local/lib/python2.7/dist-packages/requests-2.10.0-py2.7.egg/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:[2016-07-05 12:38:23.647578] Returning cached stream info for lbry://what
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:Did not find LBRY file for name: what
ERROR:lbrynet.core.LBRYWallet:Something went wrong during manage. Error message: Unable to connect to an lbrycrd server. Make sure an lbrycrd server is running and that this application can connect to it.
ERROR:lbrynet.core.LBRYWallet:An error occurred stopping the wallet: Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.2.0-py2.7-linux-x86_64.egg/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.2.0-py2.7-linux-x86_64.egg/twisted/_threads/_team.py", line 190, in doWork
    task()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.2.0-py2.7-linux-x86_64.egg/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.2.0-py2.7-linux-x86_64.egg/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.2.0-py2.7-linux-x86_64.egg/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.2.0-py2.7-linux-x86_64.egg/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/usr/local/lib/python2.7/dist-packages/lbrynet-0.3.1-py2.7.egg/lbrynet/core/LBRYWallet.py", line 46, in w
    "is running and that this application can connect to it.")
exceptions.ValueError: Unable to connect to an lbrycrd server. Make sure an lbrycrd server is running and that this application can connect to it.

INFO:lbryalert.lbrynet.core.LBRYWallet:Stopping lbrycrdd...
INFO:lbryalert.lbrynet.core.LBRYWallet:Stopped lbrycrdd.
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:[2016-07-05 12:38:23.908526] Returning cached stream info for lbry://what
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:Did not find LBRY file for name: what
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:[2016-07-05 12:38:24.166050] Returning cached stream info for lbry://what
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:Did not find LBRY file for name: what
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:[2016-07-05 12:38:24.423710] Returning cached stream info for lbry://what
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:Did not find LBRY file for name: what
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:[2016-07-05 12:38:24.681781] Returning cached stream info for lbry://what
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:Did not find LBRY file for name: what
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:[2016-07-05 12:38:24.940625] Returning cached stream info for lbry://what
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:Did not find LBRY file for name: what
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:[2016-07-05 12:38:25.198548] Returning cached stream info for lbry://what
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:Did not find LBRY file for name: what
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:[2016-07-05 12:38:25.457072] Returning cached stream info for lbry://what
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:Did not find LBRY file for name: what
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:[2016-07-05 12:38:25.715489] Returning cached stream info for lbry://what
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:Did not find LBRY file for name: what
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:[2016-07-05 12:38:25.973335] Returning cached stream info for lbry://what
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:Did not find LBRY file for name: what
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:[2016-07-05 12:38:26.233827] Returning cached stream info for lbry://what
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:Did not find LBRY file for name: what
^CUnhandled Error
Traceback (most recent call last):
  File "/usr/local/bin/lbrynet-daemon", line 9, in <module>
    load_entry_point('lbrynet==0.3.1', 'console_scripts', 'lbrynet-daemon')()
  File "/usr/local/lib/python2.7/dist-packages/lbrynet-0.3.1-py2.7.egg/lbrynet/lbrynet_daemon/LBRYDaemonControl.py", line 113, in start
    reactor.run()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.2.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.2.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.2.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 798, in runUntilCurrent
    f(*a, **kw)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.2.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 581, in stop
    "Can't stop reactor that isn't running.")
twisted.internet.error.ReactorNotRunning: Can't stop reactor that isn't running.

INFO:lbrynet.lbrynet_daemon.LBRYDaemon:[2016-07-05 12:38:26.492880] Returning cached stream info for lbry://what
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:Did not find LBRY file for name: what
^CUnhandled Error
Traceback (most recent call last):
  File "/usr/local/bin/lbrynet-daemon", line 9, in <module>
    load_entry_point('lbrynet==0.3.1', 'console_scripts', 'lbrynet-daemon')()
  File "/usr/local/lib/python2.7/dist-packages/lbrynet-0.3.1-py2.7.egg/lbrynet/lbrynet_daemon/LBRYDaemonControl.py", line 113, in start
    reactor.run()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.2.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.2.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.2.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 798, in runUntilCurrent
    f(*a, **kw)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.2.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 581, in stop
    "Can't stop reactor that isn't running.")
twisted.internet.error.ReactorNotRunning: Can't stop reactor that isn't running.

INFO:lbrynet.lbrynet_daemon.LBRYDaemon:[2016-07-05 12:38:26.749774] Returning cached stream info for lbry://what
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:Did not find LBRY file for name: what
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:[2016-07-05 12:38:27.007572] Returning cached stream info for lbry://what
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:Did not find LBRY file for name: what
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:[2016-07-05 12:38:27.265659] Returning cached stream info for lbry://what
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:Did not find LBRY file for name: what
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:[2016-07-05 12:38:27.523899] Returning cached stream info for lbry://what
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:Did not find LBRY file for name: what
```

**Comment by jobevers** [comment]
Closing this as its old; please re-open if it still persists on the most recent version.
