### ISSUE TITLE
TypeError: 'unicode' object does not support item assignment

### ISSUE THREAD

**Issue by theredcomputer** [lbryio/lbry#535]
## The Issue
Unable to publish file because of TypeError

### Steps to reproduce
1. Attempt to publish a file

### Expected behaviour
The file should be published to the network.

### Actual behaviour
Console output when running publish command:

```
017-03-17 01:10:43,670 INFO     lbrynet.lbrynet_daemon.Daemon:1738: Publish: {'fee': None, 'bid': 1, 'metadata': {u'ver': u'_0_0_1', u'description': u'A image obtained from a computer glitch showing Heavy from Team Fortress 2 holding a glowing dove.', u'license': u'Creative Commons Attribution 3.0 United States', u'author': u'Stephen', u'title': u'St. Hoovy', u'language': u'en', u'nsfw': u'False', u'content_type': u'Image', u'sources': u''}, 'name': u'hoovy', 'file_path': u'/home/stephen/Pictures/hoovy.jpg'}
2017-03-17 01:10:43,670 INFO     lbrynet.lbrynet_daemon.Publisher:35: Starting publish for hoovy
2017-03-17 01:10:56,128 INFO     lbrynet.lbryfile.EncryptedFileMetadataManager:243: Saving sd blob hash c083bd36127b63ef4afa8fc737b9417d3ed4776a76feba45bcff159e65518f5fd70be86f373cef441db895b48705f9e9 to stream hash 15a96713badfceddebc3a6cae3f472a34bf10e623b9b9188423257b7c69fb0ffb0454565ee74d8b85136cd46c56de912
2017-03-17 01:10:56,135 ERROR    lbrynet.lbrynet_daemon.auth.server:352: Failed to process publish: 'unicode' object does not support item assignment
Traceback (most recent call last):
  File "site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
  File "site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
  File "site-packages/lbrynet/lbrynet_daemon/Daemon.py", line 824, in _publish_stream
  File "site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
  File "site-packages/lbrynet/lbrynet_daemon/Publisher.py", line 46, in publish_stream
TypeError: 'unicode' object does not support item assignment
```

## System Configuration
- LBRY Daemon version:
```
[
  {
    "lbrynet_update_available": false,
    "lbrynet_version": "0.9.0",
    "lbryum_version": "2.7.13",
    "os_release": "4.4.0-66-generic",
    "os_system": "Linux",
    "platform": "Linux-4.4.0-66-generic-x86_64-with-Ubuntu-16.04-xenial",
    "remote_lbrynet": "0.9.0",
    "ui_version": "not loaded yet"
  }
]
```

**Comment by jackrobison** [comment]
>`u'ver': u'_0_0_1'` 

You experimenting with lbryschema? If so, it isn't supported yet - and publish will autofill this field.

There's a few parameters you've got that are automatically filled in or have the wrong type, try

```
{
    'bid': 1.0,
    'description': 'A image obtained from a computer glitch showing Heavy from Team Fortress 2 holding a glowing dove.',
    'license': u'Creative Commons Attribution 3.0 United States',
    'author': u'Stephen',
    'title': u'St. Hoovy',
    'language': 'en',
    'nsfw': False,
    'name': 'hoovy',
    'file_path': '/home/stephen/Pictures/hoovy.jpg'
}
```
