### ISSUE TITLE
Cannot install following INSTALL.md on Ubuntu 14.04.5, ARMv7, Python 2.7.6/2.7.11

### ISSUE THREAD

**Issue by alpo** [lbryio/lbry#536]
### Steps to reproduce
Follow steps in INSTALL.md

### Expected behaviour
The application installed

### Actual behaviour

After `pip install -U -r requirements.txt`

```
Running setup.py install for cryptography
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/odroid/lbry/lbry-venv/local/lib/python2.7/site-packages/setuptools/__init__.py", line 12, in <module>
        import setuptools.version
      File "/home/odroid/lbry/lbry-venv/local/lib/python2.7/site-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/home/odroid/lbry/lbry-venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 72, in <module>
        import packaging.requirements
      File "/home/odroid/lbry/lbry-venv/local/lib/python2.7/site-packages/packaging/requirements.py", line 9, in <module>
        from pyparsing import stringStart, stringEnd, originalTextFor, ParseException
    ImportError: No module named pyparsing
```

After `pip install -U pyparsing && pip install -U -r requirements.txt` installation was finished apparently successfully, but `lbrynet-daemon` doesn't work, the loading log is attached.

[startup.log.txt](https://github.com/lbryio/lbry/files/850091/startup.log.txt)

After Python upgrade to 2.7.11 and repeating installation steps (with change `virtualenv --python /usr/local/lib/python2.7.11/bin/python lbry-venv`)  `lbrynet-daemon` doesn't work, giving startup 2.log.txt

[startup2.log.txt](https://github.com/lbryio/lbry/files/850308/startup2.log.txt)

## System Configuration

- LBRY Daemon version: current master branch b00c20180be9f0e92ebfb2087dc98bcbc0183ed0
- Operating system: Ubuntu 14.04.5 LTS up to date, ARMv7, Python 2.7.6/2.7.11

**Comment by lyoshenka** [comment]
I fixed this bug in the most recent version. Please try installing again.

That said, we don't test on ARM processors, so if you encounter ARM-specific bugs, we'll do our best but we may not be able to help much.
