### ISSUE TITLE
KeyError: 'getpubkyes'

### ISSUE THREAD

**Issue by alpo** [lbryio/lbry#537]
### Steps to reproduce
1. Issue command `curl 'http://localhost:5279/lbryapi' --data '{"method": "wallet_public_key", "params":{"wallet":"STRING RETURNED BY wallet_new_address"}}'`

### Expected behaviour
Something reasonable without errors.

### Actual behaviour
```
{
  "fault": "JSONRPCException",
  "faultCode": 8002,
  "faultString": "Traceback (most recent call last):\n  File \"/home/odroid/lbry/lbrynet/lbrynet_daemon/DaemonRequest.py\", line 94, in requestReceived\n    self.process()\n  File \"/home/odroid/lbry/lbry-venv/lib/python2.7/site-packages/twisted/web/server.py\", line 190, in process\n    self.render(resrc)\n  File \"/home/odroid/lbry/lbry-venv/lib/python2.7/site-packages/twisted/web/server.py\", line 241, in render\n    body = resrc.render(self)\n  File \"/home/odroid/lbry/lbrynet/lbrynet_daemon/auth/server.py\", line 210, in render\n    d = defer.maybeDeferred(function, **args)\n--- <exception caught here> ---\n  File \"/home/odroid/lbry/lbry-venv/lib/python2.7/site-packages/twisted/internet/defer.py\", line 150, in maybeDeferred\n    result = f(*args, **kw)\n  File \"/home/odroid/lbry/lbrynet/lbrynet_daemon/Daemon.py\", line 2001, in jsonrpc_wallet_public_key\n    d = self.session.wallet.get_pub_keys(wallet)\n  File \"/home/odroid/lbry/lbrynet/core/Wallet.py\", line 1105, in get_pub_keys\n    return self._run_cmd_as_defer_succeed('getpubkyes', wallet)\n  File \"/home/odroid/lbry/lbrynet/core/Wallet.py\", line 956, in _run_cmd_as_defer_succeed\n    cmd = known_commands[command_name]\nexceptions.KeyError: 'getpubkyes'\n"
```

Daemon log:
```
Traceback (most recent call last):
  File "/home/odroid/lbry/lbry-venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/odroid/lbry/lbrynet/lbrynet_daemon/Daemon.py", line 2001, in jsonrpc_wallet_public_key
    d = self.session.wallet.get_pub_keys(wallet)
  File "/home/odroid/lbry/lbrynet/core/Wallet.py", line 1105, in get_pub_keys
    return self._run_cmd_as_defer_succeed('getpubkyes', wallet)
  File "/home/odroid/lbry/lbrynet/core/Wallet.py", line 956, in _run_cmd_as_defer_succeed
    cmd = known_commands[command_name]
KeyError: 'getpubkyes'
```

## System Configuration

 

- LBRY Daemon version: [
  {
    "lbrynet_update_available": false,
    "lbrynet_version": "0.9.0",
    "lbryum_version": "2.7.13",
    "os_release": "3.10.96-149",
    "os_system": "Linux",
    "platform": "Linux-3.10.96-149-armv7l-with-debian-jessie-sid",
    "remote_lbrynet": "0.9.0",
    "ui_version": "not loaded yet"
  }
]
- Operating system: Ubuntu 14.04.5

**Comment by kauffj** [comment]
I lol'ed at "something reasonable without errors".

We'll get this one patched up, thanks!

**Comment by kaykurokawa** [comment]
I'll fix this

**Comment by kaykurokawa** [comment]
Fixed in https://github.com/lbryio/lbry/pull/540
