### ISSUE TITLE
twisted.internet.error.ReactorNotRunning: Can't stop reactor that isn't running

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry#544]
When killing the daemon using Ctrl-C (or possibly pressing Ctrl-C twice before it dies):

```
CRITICAL twisted:154: Unhandled Error
Traceback (most recent call last):
  File "daemon.py", line 4, in <module>

  File "site-packages/lbrynet/lbrynet_daemon/DaemonControl.py", line 97, in start

  File "site-packages/twisted/internet/base.py", line 1199, in run

  File "site-packages/twisted/internet/base.py", line 1208, in mainLoop

--- <exception caught here> ---
  File "site-packages/twisted/internet/base.py", line 801, in runUntilCurrent

  File "site-packages/twisted/internet/base.py", line 584, in stop

twisted.internet.error.ReactorNotRunning: Can't stop reactor that isn't running.
```

**Comment by lyoshenka** [comment]
@kaykurokawa ill tackle this one

**Comment by lyoshenka** [comment]
I believe @jackrobison fixed this
