### ISSUE TITLE
Failure in publishing due to transaction rejected

### ISSUE THREAD

**Issue by nikooo777** [lbryio/lbry#552]
## The Issue
While publishing 10 files concurrently I stumbled twice into this possible _bug_

Basically there isn't much info about it, but the publication would fail with the following error:
```
{
  "fault": "JSONRPCException",
  "faultCode": 8002,
  "faultString": "Traceback (most recent call last):\nFailure: exceptions.Exception: Transaction rejected\n"
}
```

as seen on the daemon
```
2017-03-21 23:48:53,427 ERROR    lbrynet.lbrynet_daemon.auth.server:352: Failed to process publish: Transaction rejected
Exception: Transaction rejected
```

### Steps to reproduce
1. publish more file concurrently (?)
2. wait for it

### Expected behaviour
The claim should be taken and the content announced to the DHT (i guess)

### Actual behaviour
after this exception is risen, the particular file will not be uploaded and the name will not be claimed

## System Configuration

 

```
[
  {
    "build": "release",
    "ip": "*********",
    "lbrynet_update_available": false,
    "lbrynet_version": "0.9.1",
    "lbryum_version": "2.7.13",
    "os_release": "4.4.0-64-generic",
    "os_system": "Linux",
    "platform": "Linux-4.4.0-64-generic-x86_64-with-Ubuntu-16.04-xenial",
    "processor": "x86_64",
    "python_version": "2.7.12",
    "remote_lbrynet": "0.9.1"
  }
]
```

## Anything Else

it should be noted that the 2 claims that failed were already previously claimed for 1 LBC (by the same wallet)
```
niko@home~$ lbrynet-cli claim_show name=ucberkeley-ItgGi1oeSP8
{
  "amount": 1.0,
  "claim_id": "ddbbdba499140f4a3f54671d0f24f49e592db601",
  "height": 144459,
  "meta_version": "0.0.3",
  "name": "ucberkeley-ItgGi1oeSP8",
  "nout": 1,
  "supports": [],
  "txid": "3ed58fadd7d14ac2c91f5df213a44c4d9f37e53bd97a21726b63b48dbf1c3ea1",
  "value": {
    "author": "UC Berkeley",
    "content_type": "video/mp4",
    "description": "Computer Science 162, 001 - Spring 2015\nOperating Systems and System Programming - John Kubiatowicz\nCreative Commons 3.0: Attribution-NonCommercial-NoDerivs",
    "language": "en",
    "license": "Creative Commons 3.0: Attribution-NonCommercial-NoDerivs",
    "nsfw": false,
    "sources": {
      "lbry_sd_hash": "4a265774cbd53915b06b96592c18109bcd421b92bf9e626704f932e196f295bbdb85e0afa42ac999146ebdfd7ef97344"
    },
    "thumbnail": "http://berk.ninja/thumbnails/ItgGi1oeSP8",
    "title": "Computer Science 162 - 2015-05-04",
    "ver": "0.0.3"
  }
}
niko@home~$ lbrynet-cli claim_show name=ucberkeley-pulauDjH1KM
{
  "amount": 1.0,
  "claim_id": "2e5651c677bf99bd834c331e8a352a945c00759c",
  "height": 144459,
  "meta_version": "0.0.3",
  "name": "ucberkeley-pulauDjH1KM",
  "nout": 0,
  "supports": [],
  "txid": "cf9b10dd84c05ba5662d0fa6a42ebd5d082df01ff41be054e6be8d8380b9a157",
  "value": {
    "author": "UC Berkeley",
    "content_type": "video/mp4",
    "description": "Media Studies 104A, 001 - Spring 2015\nFreedom of Speech and the  Press - William B Turner\nCreative Commons 3.0: Attribution-NonCommercial-NoDerivs",
    "language": "en",
    "license": "Creative Commons 3.0: Attribution-NonCommercial-NoDerivs",
    "nsfw": false,
    "sources": {
      "lbry_sd_hash": "98a22e8e7cbd68b542da2c4b35669f5a125c412c61cc68f46185c6400ef7591f6572856c1a698824e7b65389488616d1"
    },
    "thumbnail": "http://berk.ninja/thumbnails/pulauDjH1KM",
    "title": "Media Studies 104A - 2015-05-05",
    "ver": "0.0.3"
  }
}
```

**Comment by nikooo777** [comment]
while uploading 35 videos tonight 3 of them failed for this same reason. I did try to re-run the script for these 3 videos and they eventually worked just fine.

Since I did not change any parameter I would say it's something that breaks in the daemon.

**Comment by kaykurokawa** [comment]
basically due to known race condition in wallet https://github.com/lbryio/lbry/issues/341
requires https://github.com/lbryio/lbry/issues/506 to be fixed

**Comment by lyoshenka** [comment]
@jackrobison i think this is fixed by the work you've been doing, right? if so, please close this issue. if not, leave comment about what's left to do.

**Comment by nikooo777** [comment]
We sort of bypassed the issue by spending from different addresses, however i believe that if you try to publish by spending from the same address multiple times, then it will be rejected again.

Not so sure tho, it's still a bit too technical for me. Jack will know better

**Comment by lyoshenka** [comment]
I'm seeing the same error when publishing multiple files using my version of youtube sync

**Comment by nikooo777** [comment]
you'll have to generate wallets using the script jack provided me with.

I can brief you later tonight my time if you're available (that'd be in 4 hours)

**Comment by lyoshenka** [comment]
Generating wallets solves a different issue. The problem here probably has to do with the coinchooser not being concurrent-safe. Here's what happens when I try to publish two items simultaneously. Notice how coinchooser chooses the same address to use for both publishes.

```
2017-10-02 15:41:22,657 INFO     lbrynet.daemon.Daemon:1902: Publish: {'claim_address': u'bRKhcHXmbERXUm3sm7TkPw2rb7jtDmHUgK', 'name': u'a', 'bid': 0.01, 'claim_dict': {'version': '_0_0_1', 'claimType': 'streamType', 'stream': {'version': '_0_0_1', 'metadata': {'version': '_0_1_0', 'language': u'en', 'title': u'a'}}}, 'file_path': u'/home/grin/Desktop/cake.jpg', 'change_address': None}
2017-10-02 15:41:23,191 INFO     lbrynet.daemon.Publisher:27: Starting publish for a
2017-10-02 15:41:23,197 INFO     lbrynet.daemon.auth.server:380: queued publish
2017-10-02 15:41:23,251 INFO     lbrynet.lbry_file.EncryptedFileMetadataManager:246: Saved sd blob hash 1bad9e09159df509159c852569210128a0553c41e2242f3e883c8671a7006c11547d2372bf94199060d1b6c7c26434e2 to stream hash 60bce45d321bf964d39b3b437150c1a3e2823b00d1475e813ee39be18650f8f3aa1c7127921a26d5d37ed3d534ed92a9
2017-10-02 15:41:23,252 INFO     lbrynet.core.Wallet:1368: Send claim: a for 0.01: 080110011a5d08011215080410011a016122002a00320038004a0052005a001a42080110011a301bad9e09159df509159c852569210128a0553c41e2242f3e883c8671a7006c11547d2372bf94199060d1b6c7c26434e2220a696d6167652f6a706567 
2017-10-02 15:41:27,156 ERROR    lbryum:116: [CoinChooserOldestFirst] change: [(1, 'bFhC1kkAPM8YCr3ENFhU8vcRxJ72h7NuZ3', 87480450)]

2017-10-02 15:41:27,156 ERROR    lbryum:116: [CoinChooserOldestFirst] change: [(1, 'bFhC1kkAPM8YCr3ENFhU8vcRxJ72h7NuZ3', 87480450)]

2017-10-02 15:41:27,156 ERROR    lbryum:116: [CoinChooserOldestFirst] using 1 inputs

2017-10-02 15:41:27,156 ERROR    lbryum:116: [CoinChooserOldestFirst] using 1 inputs

2017-10-02 15:41:27,157 ERROR    lbryum:116: [CoinChooserOldestFirst] using buckets: [u'f45e563a3d368ae782a2786bfea821fc76157ccd7403cb04b5e8270478744906:1']

2017-10-02 15:41:27,157 ERROR    lbryum:116: [CoinChooserOldestFirst] using buckets: [u'f45e563a3d368ae782a2786bfea821fc76157ccd7403cb04b5e8270478744906:1']

2017-10-02 15:41:27,409 ERROR    lbryum:116: adding signature for ff0488b21e000000000000000000548f12442af0179487f9b3749b86dd191a84cecec5a9ffd93941348a3e416a9002e1d4b251ad109fc23db8ec62b8d19104ac77f4db019a293d6677a51889a7634100000000

2017-10-02 15:41:27,409 ERROR    lbryum:116: adding signature for ff0488b21e000000000000000000548f12442af0179487f9b3749b86dd191a84cecec5a9ffd93941348a3e416a9002e1d4b251ad109fc23db8ec62b8d19104ac77f4db019a293d6677a51889a7634100000000

2017-10-02 15:41:27,699 ERROR    lbryum:116: adding signature for ff0488b21e000000000000000000548f12442af0179487f9b3749b86dd191a84cecec5a9ffd93941348a3e416a9002e1d4b251ad109fc23db8ec62b8d19104ac77f4db019a293d6677a51889a7634101004400

2017-10-02 15:41:27,699 ERROR    lbryum:116: adding signature for ff0488b21e000000000000000000548f12442af0179487f9b3749b86dd191a84cecec5a9ffd93941348a3e416a9002e1d4b251ad109fc23db8ec62b8d19104ac77f4db019a293d6677a51889a7634101004400

2017-10-02 15:41:27,988 ERROR    lbryum:116: is_complete True

2017-10-02 15:41:27,988 ERROR    lbryum:116: is_complete True

2017-10-02 15:41:28,200 INFO     lbrynet.core.Wallet:949: Saving metadata for claim 760d400a1fa00c518231dcce27fa302e612cf632d23ad055a44bb484373cc6bf 0
2017-10-02 15:41:28,250 INFO     lbrynet.daemon.Daemon:716: Success! Published to lbry://a txid: 760d400a1fa00c518231dcce27fa302e612cf632d23ad055a44bb484373cc6bf nout: 0
2017-10-02 15:41:28,252 INFO     lbrynet.daemon.auth.server:382: running publish from queue
2017-10-02 15:41:28,252 INFO     lbrynet.daemon.Daemon:1902: Publish: {'claim_address': u'bRKhcHXmbERXUm3sm7TkPw2rb7jtDmHUgK', 'name': u'b', 'bid': 0.01, 'claim_dict': {'version': '_0_0_1', 'claimType': 'streamType', 'stream': {'version': '_0_0_1', 'metadata': {'version': '_0_1_0', 'language': u'en', 'title': u'b'}}}, 'file_path': u'/home/grin/Desktop/cake.jpg', 'change_address': None}
2017-10-02 15:41:28,840 INFO     lbrynet.daemon.Publisher:27: Starting publish for b
2017-10-02 15:41:28,895 INFO     lbrynet.lbry_file.EncryptedFileMetadataManager:246: Saved sd blob hash 266516984ae5bdb92c436c310229696461fe432c2c8cfeca07a2674d5e6c70a3351f6f532c81ad796253eb35dd842114 to stream hash fc825dca8f331b6d710e0a4c57fd4f1f7203aacd9f576baedae731712790d272c2194a84bd9a66eff31e39ec705c4729
2017-10-02 15:41:28,896 INFO     lbrynet.core.Wallet:1368: Send claim: b for 0.01: 080110011a5d08011215080410011a016222002a00320038004a0052005a001a42080110011a30266516984ae5bdb92c436c310229696461fe432c2c8cfeca07a2674d5e6c70a3351f6f532c81ad796253eb35dd842114220a696d6167652f6a706567 
2017-10-02 15:41:33,127 ERROR    lbryum:116: [CoinChooserOldestFirst] change: [(1, 'baxi1M4Eh6e8j3tgLVq6bvC2aHusUCD3pN', 87480450)]

2017-10-02 15:41:33,127 ERROR    lbryum:116: [CoinChooserOldestFirst] change: [(1, 'baxi1M4Eh6e8j3tgLVq6bvC2aHusUCD3pN', 87480450)]

2017-10-02 15:41:33,127 ERROR    lbryum:116: [CoinChooserOldestFirst] using 1 inputs

2017-10-02 15:41:33,127 ERROR    lbryum:116: [CoinChooserOldestFirst] using 1 inputs

2017-10-02 15:41:33,127 ERROR    lbryum:116: [CoinChooserOldestFirst] using buckets: [u'f45e563a3d368ae782a2786bfea821fc76157ccd7403cb04b5e8270478744906:1']

2017-10-02 15:41:33,127 ERROR    lbryum:116: [CoinChooserOldestFirst] using buckets: [u'f45e563a3d368ae782a2786bfea821fc76157ccd7403cb04b5e8270478744906:1']

2017-10-02 15:41:33,367 ERROR    lbryum:116: adding signature for ff0488b21e000000000000000000548f12442af0179487f9b3749b86dd191a84cecec5a9ffd93941348a3e416a9002e1d4b251ad109fc23db8ec62b8d19104ac77f4db019a293d6677a51889a7634100000000

2017-10-02 15:41:33,367 ERROR    lbryum:116: adding signature for ff0488b21e000000000000000000548f12442af0179487f9b3749b86dd191a84cecec5a9ffd93941348a3e416a9002e1d4b251ad109fc23db8ec62b8d19104ac77f4db019a293d6677a51889a7634100000000

2017-10-02 15:41:33,660 ERROR    lbryum:116: adding signature for ff0488b21e000000000000000000548f12442af0179487f9b3749b86dd191a84cecec5a9ffd93941348a3e416a9002e1d4b251ad109fc23db8ec62b8d19104ac77f4db019a293d6677a51889a7634101004400

2017-10-02 15:41:33,660 ERROR    lbryum:116: adding signature for ff0488b21e000000000000000000548f12442af0179487f9b3749b86dd191a84cecec5a9ffd93941348a3e416a9002e1d4b251ad109fc23db8ec62b8d19104ac77f4db019a293d6677a51889a7634101004400

2017-10-02 15:41:33,950 ERROR    lbryum:116: is_complete True

2017-10-02 15:41:33,950 ERROR    lbryum:116: is_complete True

2017-10-02 15:41:34,293 ERROR    lbrynet.daemon.auth.server:398: Failed to process publish: Claim to name b failed: error: The transaction was rejected by network rules.(258: txn-mempool-conflict)
[01000000029570e9e12614a87b333472bec96bc3371dc75a817e5aa6450abeb19f6c068de6000000006b483045022100ad57e872f9c819960042dc413bbd1a72ed6a9233ffdc36ed9cefd658e7607d2602202684bed0da2647918bbb98f894e31f081d27f34eeb340fb29cc678a7057a5fea012102ea946d4ac2ee9b657a760a575185e102f705831d42a90ab3b1958b8e3a3eab4cffffffff064974780427e8b504cb0374cd7c1576fc21a8fe6b78a282e78a363d3a565ef4010000006b483045022100d0b20a3ea1dc54061367fcb0ff43dd704301b1c4ea62b54fa21b21a56af64e20022047a56c13d16062dc941e52948636f231c50343b41f53504372733c5ed7e93fee012102611e96c34e242a25dd5b8103d980d676886c7ffd5979dd398007c66cb1868987ffffffff0240420f0000000000f6b7016214a97f7d1cb400b7ac2f7278ebdbe60d7ceb74bf1b4cc1080110011a5d08011215080410011a016222002a00320038004a0052005a001a42080110011a30266516984ae5bdb92c436c310229696461fe432c2c8cfeca07a2674d5e6c70a3351f6f532c81ad796253eb35dd842114220a696d6167652f6a7065672a5c080110031a400982ed47746c2d289d8c7c17aed2355ccb4a7d44fa1455a70d8f5fc5a4252c6c3d9043346e9116553fb7c15e43c42e12c75c9d6066cab8c2efd68ff815b50a7222148ca8281d337a9892c1a73a90cc90d6aa9914dd726d6d76a9148a24732bbad3463af7452904bd12e195fc1477a988ac82d83605000000001976a914f3dd4deed7d88794744f4d7198d7a8e882be6dc388ac00000000]
Traceback (most recent call last):
  File "/home/grin/.virtualenvs/lbry/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "/home/grin/code/lbry/lbry/lbrynet/core/Wallet.py", line 945, in claim_name
    raise Exception(msg)
Exception: Claim to name b failed: error: The transaction was rejected by network rules.(258: txn-mempool-conflict)
[01000000029570e9e12614a87b333472bec96bc3371dc75a817e5aa6450abeb19f6c068de6000000006b483045022100ad57e872f9c819960042dc413bbd1a72ed6a9233ffdc36ed9cefd658e7607d2602202684bed0da2647918bbb98f894e31f081d27f34eeb340fb29cc678a7057a5fea012102ea946d4ac2ee9b657a760a575185e102f705831d42a90ab3b1958b8e3a3eab4cffffffff064974780427e8b504cb0374cd7c1576fc21a8fe6b78a282e78a363d3a565ef4010000006b483045022100d0b20a3ea1dc54061367fcb0ff43dd704301b1c4ea62b54fa21b21a56af64e20022047a56c13d16062dc941e52948636f231c50343b41f53504372733c5ed7e93fee012102611e96c34e242a25dd5b8103d980d676886c7ffd5979dd398007c66cb1868987ffffffff0240420f0000000000f6b7016214a97f7d1cb400b7ac2f7278ebdbe60d7ceb74bf1b4cc1080110011a5d08011215080410011a016222002a00320038004a0052005a001a42080110011a30266516984ae5bdb92c436c310229696461fe432c2c8cfeca07a2674d5e6c70a3351f6f532c81ad796253eb35dd842114220a696d6167652f6a7065672a5c080110031a400982ed47746c2d289d8c7c17aed2355ccb4a7d44fa1455a70d8f5fc5a4252c6c3d9043346e9116553fb7c15e43c42e12c75c9d6066cab8c2efd68ff815b50a7222148ca8281d337a9892c1a73a90cc90d6aa9914dd726d6d76a9148a24732bbad3463af7452904bd12e195fc1477a988ac82d83605000000001976a914f3dd4deed7d88794744f4d7198d7a8e882be6dc388ac00000000]
2017-10-02 15:41:34,397 INFO     lbrynet.reflector.client.client:77: Reflector has all blobs for lbry://a (1bad9e09159df509)
2017-10-02 15:41:34,397 INFO     lbrynet.daemon.Daemon:712: Reflected new publication to lbry://a
```

**Comment by alyssaoc** [comment]
@lyoshenka Should this go to the icebox and/or closed?
