### ISSUE TITLE
addContact unhandled error

### ISSUE THREAD

**Issue by nikooo777** [lbryio/lbry#553]
## The Issue
If you leave the daemon running for a while and you have published content you'll likely incur in this exception
```
2017-03-22 02:21:41,553 CRITICAL twisted:154: Unhandled Error
Traceback (most recent call last):
  File "site-packages/twisted/python/log.py", line 86, in callWithContext
    
  File "site-packages/twisted/python/context.py", line 118, in callWithContext
    
  File "site-packages/twisted/python/context.py", line 81, in callWithContext
    
  File "site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    
--- <exception caught here> ---
  File "site-packages/twisted/internet/udp.py", line 249, in doRead
    
  File "site-packages/lbrynet/dht/protocol.py", line 160, in datagramReceived
    
  File "site-packages/lbrynet/dht/node.py", line 385, in addContact
    
  File "site-packages/lbrynet/dht/routingtable.py", line 403, in addContact
    
exceptions.KeyError: 0
```

The log is flooded with this. Jack knows about the issue but I'm putting it here for reference
### Steps to reproduce
While I don't have a reliable way of reproducing this, following the 2 points here **could** produce it
1. possibly publish content
2. wait a while

### Expected behaviour
No exception is left unhandled and the log looks clean and boring

### Actual behaviour
flooded output

## System Configuration

 

generally observed on linux, didn't test on other OS
```
[
  {
    "build": "rc",
    "ip": "****",
    "lbrynet_update_available": false,
    "lbrynet_version": "0.9.1",
    "lbryum_version": "2.7.13",
    "os_release": "4.4.0-66-generic",
    "os_system": "Linux",
    "platform": "Linux-4.4.0-66-generic-x86_64-with-Ubuntu-16.04-xenial",
    "processor": "x86_64",
    "python_version": "2.7.12",
    "remote_lbrynet": "0.9.1"
  }
]
```

**Comment by nikooo777** [comment]
pardon, this seems to be a duplicate of #436 
feel free to close if so

**Comment by lyoshenka** [comment]
Yep.
