### ISSUE TITLE
lbrynet-gui doesn't work on Ubuntu 14

### ISSUE THREAD

**Issue by starrychloe** [lbryio/lbry#58]
This is the error it gives in the console. It was installed by double clicking the `lbrynet_0.3.1_amd64.deb` file.

```
$ cat lbrynet-gui-error.txt
Traceback (most recent call last):
  File "/usr/local/bin/lbrynet-gui", line 9, in <module>
    load_entry_point('lbrynet==0.2.5', 'console_scripts', 'lbrynet-gui')()
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 356, in load_entry_point

  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2439, in load_entry_point
    )
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2155, in load
    for group, lines in data:
  File "/usr/local/lib/python2.7/dist-packages/lbrynet-0.2.5-py2.7.egg/lbrynet/lbrynet_gui/gui.py", line 4, in <module>
    from lbrynet.lbrynet_gui.GuiApp import DownloaderApp
  File "/usr/local/lib/python2.7/dist-packages/lbrynet-0.2.5-py2.7.egg/lbrynet/lbrynet_gui/GuiApp.py", line 1, in <module>
    import Tkinter as tk
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 42, in <module>
    raise ImportError, str(msg) + ', please install the python-tk package'
ImportError: No module named _tkinter, please install the python-tk package
```

**Comment by Fillerix99** [comment]
@starrychloe: about your problem with the gui not showing up, install the python-tk package from apt-get like this `sudo apt-get install python-tk`

**Comment by jobevers** [comment]
Closing this as its old; please re-open if it still persists on the most recent version (0.6.3)
