### ISSUE TITLE
Error resolving name that's an integer (thanks, dynamic typing)

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry#588]
Run this: `lbrynet-cli resolve_name name=1`

Get this error:

```
ERROR: 'int' object has no attribute 'startswith'

Help for resolve_name method:
    
    Resolve stream info from a LBRY name
    
    Args:
        'name': (str) name to look up, do not include lbry:// prefix
    Returns:
        (dict) Metadata dictionary from name claim, None if the name is not
                resolvable
    
Here's the traceback for the error you encountered:
Traceback (most recent call last):
  File "/home/grin/lbry/lbrynet/lbrynet_daemon/auth/server.py", line 214, in render
    return self._render(request)
  File "/home/grin/lbry/lbrynet/lbrynet_daemon/auth/server.py", line 327, in _render
    d = defer.maybeDeferred(function, **args_dict)
  File "/home/grin/.virtualenvs/lbry/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/grin/.virtualenvs/lbry/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1445, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/home/grin/.virtualenvs/lbry/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "/home/grin/lbry/lbrynet/lbrynet_daemon/Daemon.py", line 1343, in jsonrpc_resolve_name
    metadata = yield self._resolve_name(name, force_refresh=force)
  File "/home/grin/lbry/lbrynet/lbrynet_daemon/Daemon.py", line 761, in _resolve_name
    if name.startswith('lbry://'):
exceptions.AttributeError: 'int' object has no attribute 'startswith'
```

**Comment by kauffj** [comment]
This appears to be finished?
