### ISSUE TITLE
Franklin error: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry#610]
Hard-to-reproduce error from franklin. This doesn't happen when you just get the one name, but it happens when you get a bunch of names in a row.
 
 ```
Requested download of lbry://A-Woman-s-Journey-Round-the-World-by-Ida-Pfeiffer (1.67 seconds)
Caught exception: 'NoneType' object has no attribute '__getitem__'
Aborting tests.
lbry\ResponseException: 'NoneType' object has no attribute '__getitem__' in /home/lbry/franklin/vendor/lbryio/php-api/src/BaseApi.php:50
Stack trace:
#0 /home/lbry/franklin/vendor/lbryio/php-api/src/DaemonApi.php(19): lbry\BaseApi::makeRequest('http://localhos...', 'stream_cost_est...', Array)
#1 /home/lbry/franklin/src/Franklin.php(280): lbry\DaemonApi::call('stream_cost_est...', Array)
#2 /home/lbry/franklin/src/Franklin.php(370): Franklin->getEstimatedPrice('A-dissolucao-do...')
#3 /home/lbry/franklin/src/Franklin.php(313): Franklin->tryStartFile('A-dissolucao-do...')
#4 /home/lbry/franklin/src/Franklin.php(161): Franklin->startDownloads(Array)
#5 /home/lbry/franklin/src/Franklin.php(69): Franklin->testDownload(Array)
#6 /home/lbry/franklin/run.php(26): Franklin->run()
#7 {main}
```

Daemon log:

```
Apr 13 16:06:31 test lbrynet-daemon[11684]: 2017-04-13 16:06:31,344 ERROR    lbrynet.lbrynet_daemon.auth.server:352: Failed to process stream_cost_estimate: 'NoneType' object has no attribute '__getitem__'
Apr 13 16:06:31 test lbrynet-daemon[11684]: Traceback (most recent call last):
Apr 13 16:06:31 test lbrynet-daemon[11684]:   File "site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
Apr 13 16:06:31 test lbrynet-daemon[11684]:   File "site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
Apr 13 16:06:31 test lbrynet-daemon[11684]:   File "site-packages/lbrynet/lbrynet_daemon/Daemon.py", line 1721, in jsonrpc_stream_cost_estimate
Apr 13 16:06:31 test lbrynet-daemon[11684]:   File "site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
Apr 13 16:06:31 test lbrynet-daemon[11684]:   File "site-packages/lbrynet/lbrynet_daemon/Daemon.py", line 897, in get_est_cost_from_uri
Apr 13 16:06:31 test lbrynet-daemon[11684]:   File "site-packages/lbryschema/claim.py", line 140, in load_dict
Apr 13 16:06:31 test lbrynet-daemon[11684]:   File "site-packages/lbryschema/encoding.py", line 33, in decode_fields
Apr 13 16:06:31 test lbrynet-daemon[11684]: TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by kaykurokawa** [comment]
happens due to non decodeable claims when calling stream_cost_estimate. fixed in https://github.com/lbryio/lbry/pull/614
