### ISSUE TITLE
BaseException: local variable 'claim_id' referenced before assignment

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry#624]
## Franklin

```
Attempting to publish Hatter_and_Hare_Dunking_Dormouse.jpg to franklin-2017-04-25-931
Publish took 11.82 seconds. No errors encountered.
Waiting 60s for blobs to be reflected
Resetting env.
Waiting for block 164329 to be mined.
Waited for next block for 23 seconds. Trying download.
Failed to start lbry://franklin-2017-04-25-931. Trying once more in 5 seconds.
lbry\ResponseException: local variable 'claim_id' referenced before assignment in /home/lbry/franklin/vendor/lbryio/php-api/src/BaseApi.php:50
Stack trace:
#0 /home/lbry/franklin/vendor/lbryio/php-api/src/DaemonApi.php(19): lbry\BaseApi::makeRequest('http://localhos...', 'stream_cost_est...', Array)
#1 /home/lbry/franklin/src/Franklin.php(283): lbry\DaemonApi::call('stream_cost_est...', Array)
#2 /home/lbry/franklin/src/Franklin.php(373): Franklin->getEstimatedPrice('franklin-2017-0...')
#3 /home/lbry/franklin/src/Franklin.php(396): Franklin->tryStartFile('franklin-2017-0...', false)
#4 /home/lbry/franklin/src/Franklin.php(518): Franklin->tryStartFile('franklin-2017-0...')
#5 /home/lbry/franklin/src/Franklin.php(68): Franklin->testPublish()
#6 /home/lbry/franklin/run.php(26): Franklin->run()
```

## Daemon
```
2017-04-25 17:32:45,192 ERROR    lbrynet.lbrynet_daemon.auth.server:352: Failed to process stream_cost_estimate: Failed to get response from server within timeout of 30
Traceback (most recent call last):
  File "site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
  File "site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
  File "site-packages/lbrynet/lbrynet_daemon/Daemon.py", line 1726, in jsonrpc_stream_cost_estimate
  File "site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
  File "site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
  File "site-packages/lbrynet/lbrynet_daemon/Daemon.py", line 891, in get_est_cost_from_uri
  File "site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
  File "site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
  File "site-packages/lbrynet/core/Wallet.py", line 584, in resolve_uri
  File "site-packages/twisted/python/threadpool.py", line 246, in inContext
  File "site-packages/twisted/python/threadpool.py", line 262, in <lambda>
  File "site-packages/twisted/python/context.py", line 118, in callWithContext
  File "site-packages/twisted/python/context.py", line 81, in callWithContext
  File "site-packages/lbryum/commands.py", line 152, in func_wrapper
  File "site-packages/lbryum/commands.py", line 955, in getvalueforuri
  File "site-packages/lbryum/commands.py", line 152, in func_wrapper
  File "site-packages/lbryum/commands.py", line 885, in getvalueforname
  File "site-packages/lbryum/commands.py", line 152, in func_wrapper
  File "site-packages/lbryum/commands.py", line 874, in requestvalueforname
  File "site-packages/lbryum/network.py", line 803, in synchronous_get
BaseException: Failed to get response from server within timeout of 30
2017-04-25 17:33:04,563 ERROR    lbrynet.lbrynet_daemon.auth.server:352: Failed to process stream_cost_estimate: local variable 'claim_id' referenced before assignment
Traceback (most recent call last):
  File "site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
  File "site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
  File "site-packages/lbrynet/lbrynet_daemon/Daemon.py", line 1726, in jsonrpc_stream_cost_estimate
  File "site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
  File "site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
  File "site-packages/lbrynet/lbrynet_daemon/Daemon.py", line 891, in get_est_cost_from_uri
  File "site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
  File "site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
  File "site-packages/lbrynet/core/Wallet.py", line 584, in resolve_uri
  File "site-packages/twisted/python/threadpool.py", line 246, in inContext
  File "site-packages/twisted/python/threadpool.py", line 262, in <lambda>
  File "site-packages/twisted/python/context.py", line 118, in callWithContext
  File "site-packages/twisted/python/context.py", line 81, in callWithContext
  File "site-packages/lbryum/commands.py", line 152, in func_wrapper
  File "site-packages/lbryum/commands.py", line 955, in getvalueforuri
  File "site-packages/lbryum/commands.py", line 152, in func_wrapper
  File "site-packages/lbryum/commands.py", line 885, in getvalueforname
  File "site-packages/lbryum/commands.py", line 152, in func_wrapper
  File "site-packages/lbryum/commands.py", line 874, in requestvalueforname
  File "site-packages/lbryum/network.py", line 805, in synchronous_get
BaseException: local variable 'claim_id' referenced before assignment
```

## Version

```
{
  "build": "dev",
  "installation_id": "24DZ7LemZf5Zd6cBy5U7gQHURfjgvLf8gykgx9N6aCj6G5pZXoNXp5ipSC1LHxhkjR",
  "lbrynet_version": "0.10.0rc13",
  "lbryschema_version": "0.0.4",
  "lbryum_version": "2.7.21",
  "os_release": "4.4.0-72-generic",
  "os_system": "Linux",
  "platform": "Linux-4.4.0-72-generic-x86_64-with-Ubuntu-16.04-xenial",
  "processor": "x86_64",
  "python_version": "2.7.12"
}
```

**Comment by kaykurokawa** [comment]
I see the problem , its lbryum server related will have fix soon

**Comment by kaykurokawa** [comment]
fixed in https://github.com/lbryio/lbryum-server/pull/25
