### ISSUE TITLE
lbrynet_0.3.1_amd64.deb does not install (Ubuntu 16.04)

### ISSUE THREAD

**Issue by eshriek** [lbryio/lbry#63]
Double clicking does not launch lbry installer. Ubuntu software launches with white screen only.

Using terminal: dpkg -i lbrynet_0.3.1_amd64.deb //fails with "dpkg: error: requested operation requires superuser privilege"

sudo dpkg -i lbrynet_0.3.1_amd64.deb  installs but localhost:5279 hangs with "There was a problem checking for updates on github..." in chrome and ff.

Guessing deb should not install with sudo and when that is tried there is an owner/permission conflict?

**Comment by eshriek** [comment]
I set up Ubuntu 16.04 as a VM, updated, then tried the following:

$sudo apt-get install libgmp3-dev build-essential python2.7 python2.7-dev python-pip
$git clone https://github.com/lbryio/lbry.git
$cd lbry
$sudo python setup.py install
$lbrynet-daemon
Starting lbrynet-daemon from command line
To view activity, view the log file here: /home/lbry/.lbrynet/lbrynet.log
Web UI is available at http://localhost:5279
JSONRPC API is available at http://localhost:5279/lbryapi
To quit press ctrl-c or call 'stop' via the API
Traceback (most recent call last):
  File "/usr/local/bin/lbrynet-daemon", line 9, in <module>
    load_entry_point('lbrynet==0.3.4', 'console_scripts', 'lbrynet-daemon')()
  File "/usr/local/lib/python2.7/dist-packages/lbrynet-0.3.4-py2.7.egg/lbrynet/lbrynet_daemon/LBRYDaemonControl.py", line 108, in start
    branch_specified=True if args.branch else False)
  File "/usr/local/lib/python2.7/dist-packages/lbrynet-0.3.4-py2.7.egg/lbrynet/lbrynet_daemon/LBRYDaemonServer.py", line 192, in start
    d = self._setup_server(wallet)
  File "/usr/local/lib/python2.7/dist-packages/lbrynet-0.3.4-py2.7.egg/lbrynet/lbrynet_daemon/LBRYDaemonServer.py", line 186, in _setup_server
    self._api = LBRYDaemon(self.root, wallet_type="lbrycrd")
  File "/usr/local/lib/python2.7/dist-packages/lbrynet-0.3.4-py2.7.egg/lbrynet/lbrynet_daemon/LBRYDaemon.py", line 356, in __init__
    with open(self.lbrycrd_conf, 'w') as f:
IOError: [Errno 2] No such file or directory: '/home/lbry/.lbrycrd/lbrycrd.conf'

...


$ cat lbrynet.log
Starting lbrynet-daemon from command line
Writing default settings : {"cache_time": 3600, "download_directory": "/home/lbry/Downloads", "data_rate": 0.005, "delete_blobs_on_remove": true, "wallet_type": "lbrycrd", "max_upload": 0.0, "last_version": {"lbryum": "2.6.0.6", "lbrynet": "0.3.4"}, "upload_log": true, "run_on_startup": false, "startup_scripts": [], "max_search_results": 25, "download_timeout": 30, "max_download": 0.0, "requested_first_run_credits": false, "dht_node_port": 4444, "max_key_fee": 100.0, "search_timeout": 3.0, "peer_port": 3333, "use_upnp": true, "start_lbrycrdd": true} --> /home/lbry/.lbrynet/daemon_settings.json
Using wallet type lbrycrd specified from command line
No lbrycrd.conf found at /home/lbry/.lbrycrd/lbrycrd.conf. Generating now...


//The file does not generate. Manually added lbrycrd.conf with rpc user name and password specified in file.

Then tried:

$ lbrynet-daemon
Starting lbrynet-daemon from command line
To view activity, view the log file here: /home/lbry/.lbrynet/lbrynet.log
Web UI is available at http://localhost:5279
JSONRPC API is available at http://localhost:5279/lbryapi
To quit press ctrl-c or call 'stop' via the API
Unhandled error in Deferred:


Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.3.0-py2.7-linux-x86_64.egg/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.3.0-py2.7-linux-x86_64.egg/twisted/_threads/_team.py", line 190, in doWork
    task()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.3.0-py2.7-linux-x86_64.egg/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.3.0-py2.7-linux-x86_64.egg/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.3.0-py2.7-linux-x86_64.egg/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.3.0-py2.7-linux-x86_64.egg/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/usr/local/lib/python2.7/dist-packages/lbrynet-0.3.4-py2.7.egg/lbrynet/core/LBRYWallet.py", line 625, in _make_connection
    self._start_daemon()
  File "/usr/local/lib/python2.7/dist-packages/lbrynet-0.3.4-py2.7.egg/lbrynet/core/LBRYWallet.py", line 756, in _start_daemon
    raise ValueError("Couldn't launch lbrycrdd. Tried %s" % self.lbrycrdd_path)
exceptions.ValueError: Couldn't launch lbrycrdd. Tried ./lbrycrdd

**Comment by lyoshenka** [comment]
@eshriek can you please try the latest build (0.3.5) and see if you experience the same issue. make sure you uninstall (apt-get purge) any previous lbry or lbrynet installs, or just start from a clean vm. 

thanks.

**Comment by eshriek** [comment]
No problems at all with 0.3.5 install from deb file. Thanks! Looking forward to more updates.
