### ISSUE TITLE
Exception when listing channels after claiming one

### ISSUE THREAD

**Issue by nikooo777** [lbryio/lbry#634]
## The Issue
If a channel has just been claimed and the command channel_list_mine is called, the daemon throws an exception
### Steps to reproduce
1. ./lbrynet-cli channel_new channel_name=@YTTest amount=1
2. issue `./lbrynet-cli channel_list_mine` multiple times

### Expected behaviour
empty array until the channel is claimed [or queued (?)] and then an array of channels

### Actual behaviour
Empty array returned for the first few seconds and then an exception is thrown (see below)

## System Configuration

```
{
  "id": null,
  "jsonrpc": "2.0",
  "result": {
    "build": "rc",
    "ip": "46.127.177.176",
    "lbrynet_version": "0.10.3rc1",
    "lbryschema_version": "0.0.4",
    "lbryum_version": "2.7.21",
    "os_release": "4.4.0-75-generic",
    "os_system": "Linux",
    "platform": "Linux-4.4.0-75-generic-x86_64-with-Ubuntu-16.04-xenial",
    "processor": "x86_64",
    "python_version": "2.7.12"
  }
}
```

## Anything Else
```
niko@home~/lbry$ ./lbrynet-cli channel_list_mine
ERROR: NOT NULL constraint failed: claim_cache.height

Help for channel_list_mine method:
    
    Get my channels
    
    Returns:
        (list) ClaimDict
    
Here's the traceback for the error you encountered:
Traceback (most recent call last):
  File "site-packages/twisted/internet/defer.py", line 498, in errback
  File "site-packages/twisted/internet/defer.py", line 565, in _startRunCallbacks
  File "site-packages/twisted/internet/defer.py", line 651, in _runCallbacks
  File "site-packages/twisted/internet/defer.py", line 1355, in gotResult
--- <exception caught here> ---
  File "site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
  File "site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
  File "site-packages/lbrynet/lbrynet_daemon/Daemon.py", line 1733, in jsonrpc_channel_list_mine
  File "site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
  File "site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
  File "site-packages/lbrynet/core/Wallet.py", line 901, in channel_list
  File "site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
  File "site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
  File "site-packages/lbrynet/core/Wallet.py", line 800, in _handle_claim_result
  File "site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
  File "site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
  File "site-packages/lbrynet/core/Wallet.py", line 339, in save_claim_to_cache
  File "site-packages/twisted/python/threadpool.py", line 246, in inContext
  File "site-packages/twisted/python/threadpool.py", line 262, in <lambda>
  File "site-packages/twisted/python/context.py", line 118, in callWithContext
  File "site-packages/twisted/python/context.py", line 81, in callWithContext
  File "site-packages/twisted/enterprise/adbapi.py", line 477, in _runInteraction
  File "site-packages/twisted/enterprise/adbapi.py", line 467, in _runInteraction
  File "site-packages/twisted/enterprise/adbapi.py", line 486, in _runOperation
sqlite3.IntegrityError: NOT NULL constraint failed: claim_cache.height

```

**Comment by nikooo777** [comment]
This issue has been fixed I believe, am I correct?

**Comment by kaykurokawa** [comment]
Yes, this has been fixed, it was lbryum server problem
