### ISSUE TITLE
ERROR: 'Manager' object has no attribute ....

### ISSUE THREAD

**Issue by dindinw** [lbryio/lbry#635]
## The Issue
`Manager' object has no attribute 'send_credits_sent'` error, when I try to send some LBC to my address.

### Steps to reproduce
```
$ (master) lbrynet-cli send_amount_to_address amount=0.1 address="<my_address>"
ERROR: 'Manager' object has no attribute 'send_credits_sent'

Help for send_amount_to_address method:

    Send credits to an address

    Args:
        'amount': (float) the amount to send
        'address': (str) the address of the recipient in base58
    Returns:
        (bool) true if payment successfully scheduled

Here's the traceback for the error you encountered:
Traceback (most recent call last):
  File "/work/github.com/lbryio/lbry/lbrynet/lbrynet_daemon/auth/server.py", line 214, in render
    return self._render(request)
  File "/work/github.com/lbryio/lbry/lbrynet/lbrynet_daemon/auth/server.py", line 327, in _render
    d = defer.maybeDeferred(function, **args_dict)
  File "/work/github.com/lbryio/lbry/lbry-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/work/github.com/lbryio/lbry/lbry-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1445, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/work/github.com/lbryio/lbry/lbry-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "/work/github.com/lbryio/lbry/lbrynet/lbrynet_daemon/Daemon.py", line 2227, in jsonrpc_send_amount_to_address
    self.analytics_manager.send_credits_sent()
exceptions.AttributeError: 'Manager' object has no attribute 'send_credits_sent'
```
## System Configuration

- LBRY Daemon version:
```
$ (master) lbrynet-daemon --version
{
  "build": "dev",
  "installation_id": "my_id",
  "lbrynet_version": "0.10.3rc1",
  "lbryschema_version": "0.0.4",
  "lbryum_version": "2.7.21",
  "os_release": "4.8.0-46-generic",
  "os_system": "Linux",
  "platform": "Linux-4.8.0-46-generic-x86_64-with-Ubuntu-16.04-xenial",
  "processor": "x86_64",
  "python_version": "2.7.12"
}
```
- LBRY CLI:
```
$ (master) lbrynet-cli version
{
  "build": "dev",
  "ip": "<my_ip>",
  "lbrynet_version": "0.10.3rc1",
  "lbryschema_version": "0.0.4",
  "lbryum_version": "2.7.21",
  "os_release": "4.8.0-46-generic",
  "os_system": "Linux",
  "platform": "Linux-4.8.0-46-generic-x86_64-with-Ubuntu-16.04-xenial",
  "processor": "x86_64",
  "python_version": "2.7.12"
}
```

**Comment by kaykurokawa** [comment]
Ran into the same problem , this was due to there being a folder "analytics" under lbrynet that got replaced by analytics.py . If you installed a version from source that had the "analytics" folder using python setup.py install,  this folder will not get purged from your build unless you clean it up by running: ''sudo python setup.py clean --all'

and then running 'sudo python setup.py install' should remove this problem.

**Comment by kauffj** [comment]
@kaykurokawa so is there an outstanding issue here?

**Comment by kaykurokawa** [comment]
if this fixes the problem for @dindinw , we can close it as there isn't any solution for this other than to tell people to run the clean command.
