### ISSUE TITLE
lbry://None in log file warnings/errors

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry#660]
_From @tzarebczan on May 31, 2017 0:49_

 

### Steps to reproduce
1. Run LBRY
2. Check Log
3. See that lbry://None reflector fails, but then a claim is found supposedly. 

### Expected behaviour
None is not a claim, should not be referenced

### Actual behaviour
warnings/errors regarding None

## System Configuration

 

- LBRY Daemon version:
- LBRY App version: 0.11.6
- LBRY Installation ID:
- Operating system: Windows

## Anything Else

2017-05-30 20:42:14,219 WARNING  lbrynet.reflector.client.client:226: Reflector failed to receive descriptor c6b73968bc1ab997 for lbry://None
2017-05-30 20:42:14,220 WARNING  lbrynet.reflector.client.client:169: An error occurred handling the response: Traceback (most recent call last):
  File "site-packages\twisted\internet\tcp.py", line 214, in _dataReceived
    
  File "site-packages\lbrynet\reflector\client\client.py", line 70, in dataReceived
    
  File "site-packages\twisted\internet\defer.py", line 319, in addCallback
    
  File "site-packages\twisted\internet\defer.py", line 308, in addCallbacks
    
--- <exception caught here> ---
  File "site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    
  File "site-packages\lbrynet\reflector\client\client.py", line 70, in <lambda>
    
  File "site-packages\lbrynet\reflector\client\client.py", line 309, in send_next_request
    
  File "site-packages\lbrynet\reflector\client\client.py", line 256, in open_blob_for_reading
    
exceptions.AttributeError: 'unicode' object has no attribute 'is_validated'

2017-05-30 20:42:14,220 WARNING  lbrynet.reflector.client.client:226: Reflector failed to receive descriptor c6b73968bc1ab997 for lbry://None
2017-05-30 20:42:14,223 WARNING  lbrynet.reflector.client.client:169: An error occurred handling the response: Traceback (most recent call last):
  File "site-packages\twisted\internet\tcp.py", line 214, in _dataReceived
    
  File "site-packages\lbrynet\reflector\client\client.py", line 70, in dataReceived
    
  File "site-packages\twisted\internet\defer.py", line 319, in addCallback
    
  File "site-packages\twisted\internet\defer.py", line 308, in addCallbacks
    
--- <exception caught here> ---
  File "site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    
  File "site-packages\lbrynet\reflector\client\client.py", line 70, in <lambda>
    
  File "site-packages\lbrynet\reflector\client\client.py", line 309, in send_next_request
    
  File "site-packages\lbrynet\reflector\client\client.py", line 256, in open_blob_for_reading
    
exceptions.AttributeError: 'unicode' object has no attribute 'is_validated'

2017-05-30 20:42:14,471 WARNING  lbrynet.core.Wallet:666: Claim does not exist: c5ed67b1b928752515797c780b00ecd2b14badf2
2017-05-30 20:42:14,792 WARNING  lbrynet.core.Wallet:666: Claim does not exist: 64ceb23ad330ff29e7a836baf6e747f84618b901
2017-05-30 20:42:15,138 ERROR    lbrynet.lbrynet_daemon.auth.server:346: Failed to process file_list: string indices must be integers
Traceback (most recent call last):
  File "site-packages\twisted\internet\defer.py", line 1299, in _inlineCallbacks
  File "site-packages\lbrynet\core\Wallet.py", line 770, in _handle_claim_result
  File "site-packages\lbryschema\claim.py", line 140, in load_dict
  File "site-packages\lbryschema\encoding.py", line 33, in decode_fields
TypeError: string indices must be integers
2017-05-30 20:42:24,602 INFO     lbrynet.reflector.client.client:223: Sent reflector descriptor c6b73968bc1ab997
2017-05-30 20:42:24,602 INFO     lbrynet.reflector.client.client:77: Reflector has all blobs for lbry://None (c6b73968bc1ab997)

## Screenshots

_Copied from original issue: lbryio/lbry-app#161_

**Comment by kauffj** [comment]
There may also be an app API call that is improper, but the app isn't requesting lbry://None. I believe that's an error related to type coercion somewhere in this repo.

**Comment by kauffj** [comment]
I'm not seeing this in my current wallet, will re-open if I see it again. Possibly related to old data.
