### ISSUE TITLE
Library downloaded/published will not load after upgrading from legacy

### ISSUE THREAD

**Issue by kimihiro64** [lbryio/lbry#706]
I upgraded from lbry 0.6.9 or so to latest 0.12.0, when going to downloads/publishes, it just sits on Loading... forever. I can see it running through lbry URLs for things I've download/published in the past in the console. Here are some potentially useful console warnings/errors, betting it's the last one:

2017-06-17 22:29:12,812 WARNING  lbrynet.core.sqlite_helpers:14: database was locked. rerunning <function save_name_metadata at 0x7fc698848578> with args (<lbrynet.core.Wallet.SqliteStorage object at 0x7fc696461310>, u'five', 6e0b0aedbe119fb3aafe89bf0c280464d11c77ab38dd9d45d10e40168b4d462e:1, '8be699fd598f2d6a5bc12490e375ff92f63eaedad7948f5d87f2ea43279ec674d4212022158d717eb34e97ddfd181ecb'), kwargs {}

2017-06-17 22:29:07,769 WARNING  lbrynet.core.Wallet:738: lbry://four#70a4753a0648d45346580c5c3dd5363e417d6a02 has an invalid signature

2017-06-17 22:28:45,074 ERROR    lbrynet.lbrynet_daemon.auth.server:346: Failed to process file_list: string indices must be integers
Traceback (most recent call last):
  File "site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
  File "site-packages/lbrynet/core/Wallet.py", line 770, in _handle_claim_result
  File "site-packages/lbryschema/claim.py", line 140, in load_dict
  File "site-packages/lbryschema/encoding.py", line 33, in decode_fields
TypeError: string indices must be integers

About
Your copy of LBRY is up to date.

daemon (lbrynet)	0.11.0
wallet (lbryum)	2.7.25
interface	0.12.0
Platform	Linux (Linux-4.4.0-75-generic-x86_64-with-Ubuntu-16.04-xenial)
Installation ID	3n1vtReZyaeUpTweiXPuVF7ncX1HVAKj3mJp9Lhpns71kbh6c9yv8yDzHenokJWRfc

**Comment by tzarebczan** [comment]
It's a known issue, we have it logged under here https://github.com/lbryio/lbry/issues/661

**Comment by tzarebczan** [comment]
@kimihiro64 can you see if this is still happening on 0.13? Personally I still have trouble with the download/published  list showing, but I don't get the 'string indices must be integers'. Instead, I have a Unicode issue which should be fixed soon (not in any build) 

Please try again on 0.13 and repost log.

**Comment by kauffj** [comment]
It sounds like @kimihiro64 already rescued his credits and reset his install from other messages. I am fairly confident that these issues were from old data that wasn't properly migrated, so looking into these issues will be low priority compared to issues affecting all users.

I'm going to close this, but please re-open if there is an issue we think still currently affecting anyone.
