### ISSUE TITLE
RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry#720]
I ran a script to send ~150 claims to an address. Here's the script:

```
for claimid in $(/opt/lbry/lbrynet-cli claim_list_mine | ./jq '.[].claim_id' | cut -d'"' -f2 ); do echo $claimid; /opt/lbry/lbrynet-cli claim_send_to_address $claimid ADDRESS; done
```

After a few dozen claims were sent, I got the following error. The daemon froze and had to be killed.

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "site-packages/lbryum/network.py", line 755, in run
  File "site-packages/lbryum/network.py", line 747, in wait_on_sockets
  File "site-packages/lbryum/network.py", line 528, in process_responses
  File "site-packages/lbryum/network.py", line 480, in process_response
  File "site-packages/lbryum/synchronizer.py", line 110, in addr_history_response
  File "site-packages/lbryum/wallet.py", line 952, in receive_history_callback
  File "site-packages/lbryum/util.py", line 174, in <lambda>
  File "site-packages/lbryum/util.py", line 170, in do_profile
  File "site-packages/lbryum/wallet.py", line 255, in save_transactions
  File "site-packages/lbryum/wallet.py", line 118, in put
  File "copy.py", line 163, in deepcopy
  File "copy.py", line 256, in _deepcopy_dict
RuntimeError: dictionary changed size during iteration
```

**Comment by alyssaoc** [comment]
@eukreign Could you test this with the new wallet and close as necessary?

**Comment by eukreign** [comment]
The entire `lbryum` package no longer exists in new wallet, closing.
