### ISSUE TITLE
Error while running: pip install -U -r requirements.txt

### ISSUE THREAD

**Issue by miketrimmel** [lbryio/lbry#726]
Collecting wsgiref==0.1.2 (from -r requirements.txt (line 31))
  Using cached wsgiref-0.1.2.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/dt/15hq2jbn0l3c1xnqyg3xxhrh0000gn/T/pip-build-mk0x1u2k/wsgiref/setup.py", line 5, in <module>
        import ez_setup
      File "/private/var/folders/dt/15hq2jbn0l3c1xnqyg3xxhrh0000gn/T/pip-build-mk0x1u2k/wsgiref/ez_setup/__init__.py", line 170
        print "Setuptools version",version,"or greater has been installed."
                                 ^
    SyntaxError: Missing parentheses in call to 'print'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/dt/15hq2jbn0l3c1xnqyg3xxhrh0000gn/T/pip-build-mk0x1u2k/wsgiref/

**Comment by zestyr** [comment]
You need to use Python 2.7, `lbry` doesn't support Python 3

**Comment by miketrimmel** [comment]
Ok, thanks.
