### ISSUE TITLE
Daemon connection refused or timed out

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#742]
## The Issue
Several users are reporting connection issue, gui gets stuck on green blockchain screen.  One occurrence referenced a large wallet, but unlikely to be caused by that. It's a warning message at 1k. The cut off is at 15K. There was also another user in #735 which sounds like a very similar issue. 

Connection either gets refused or times out. 
![img_20170629_202154](https://user-images.githubusercontent.com/8120721/27720979-595295fc-5d2b-11e7-9d5a-2013db0878db.jpg)
![img_20170629_200224](https://user-images.githubusercontent.com/8120721/27720987-63e32b26-5d2b-11e7-85b3-9cebe03079ee.jpg)

### Steps to reproduce
1. Start wallet with many addresses 
2. Connection refused or timed out. 

### Expected behaviour
Daemon connects. 

### Actual behaviour
Daemon is stuck on catching up with the blockchain... 

## System Configuration

 

- LBRY Daemon version: 0.13.1
- LBRY App version: 0.13.0rc1
- LBRY Installation ID:
- Operating system: Unix

## Anything Else

after that I see it gradually getting more and more behind

```
2017-06-30 10:22:10,995 ERROR    lbryum.interface:115: Failed to connect to (2, 1, 6, '', ('54.159.52.68', 50001))
```

2017-06-30 10:22:31,156 INFO     lbrynet.core.Wallet:1234: Local Height: 199199, remote height: 199266, behind: 67
2017-06-30 10:23:10,493 INFO     lbrynet.core.Wallet:1234: Local Height: 199199, remote height: 0, behind: None
2017-06-30 10:23:11,809 INFO     lbrynet.core.Wallet:1234: Local Height: 199199, remote height: 199266, behind: 67
2017-06-30 10:23:16,501 INFO     lbrynet.core.Wallet:1234: Local Height: 199199, remote height: 199266, behind: 67
2017-06-30 10:23:31,380 INFO     lbrynet.core.Wallet:1234: Local Height: 199199, remote height: 199267, behind: 68
2017-06-30 10:24:10,597 INFO     lbrynet.core.Wallet:1234: Local Height: 199199, remote height: 0, behind: None
2017-06-30 10:24:12,536 INFO     lbrynet.core.Wallet:1234: Local Height: 199199, remote height: 199267, behind: 68
```

here's the full traceback:
```
2017-06-30 10:22:10,995 ERROR    lbryum.interface:115: Failed to connect to (2, 1, 6, '', ('54.159.52.68', 50001))
Traceback (most recent call last):
  File "site-packages/lbryum/interface.py", line 110, in get_simple_socket
  File "socket.py", line 228, in meth
error: [Errno 61] Connection refused
```
## Screenshots
<!-- If a screenshot would help explain the bug, please include one or two here -->

**Comment by kauffj** [comment]
@tzarebczan "daemon connection refused or timed out" is a catch all message display when the daemon cannot be connected to. On it's own, it's difficult to investigate from this message alone.

Instead, when a user reports this issue, we need to get their lbrynet.log file and use those details to figure out specifically why the daemon is not starting in that particular instance.

In this case, the issue is the "failed to connect" issue with lbryum, which I believe is fixed.

**Comment by tzarebczan** [comment]
[lbrynet-lartera.txt](https://github.com/lbryio/lbry/files/1126855/lbrynet-lartera.txt)
Per conversation with @lyoshenka, asked to upload a user's log file who is having issues with connecting.  I believe he is stuck on "catching up with the blockchain"  but his log shows "Connection refused" to one of our lbryum servers.  User is lartera from Slack.  I'm going to have him try again today since we did have some server work done overthe last couple of days.

**Comment by kauffj** [comment]
@tzarebczan I believe if the user closes all copies of lbry and lbrynet-daemon, upgrades, and runs it again, that it will connect fine.
