### ISSUE TITLE
Better Claim_abandon support, cannot abandon in a couple scenarios

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#795]
## The Issue
Added support (claim_new_support via api) to someone else's claim twice and it looks like the claim_id is the same on both entries. 
    {
      "address": "bXJjCQxEedecAdrWarfzMbeuX7ZFdDJU4r",
      "amount": 1.0,
      "blocks_to_expiration": 243208,
      "category": "support",
      "claim_id": "b64155f2d44553871dfdb1785aa49d6d3972cd84",
      "confirmations": 19766,
      "expiration_height": 454392,
      "expired": false,
      "height": 191418,
      "is_pending": false,
      "is_spent": false,
      "name": "three",
      "nout": 0,
      "txid": "02c6d313e8cdcce96382ed4450205180ca63d7d424e734e72c3dcb44350133e0"
    },
    {
      "address": "bCrbM9X7shQhxsaxKHBk7xAFCPZMR8h3gd",
      "amount": 249.0,
      "blocks_to_expiration": 243208,
      "category": "support",
      "claim_id": "b64155f2d44553871dfdb1785aa49d6d3972cd84",
      "confirmations": 19766,
      "expiration_height": 454392,
      "expired": false,
      "height": 191418,
      "is_pending": false,
      "is_spent": false,
      "name": "three",
      "nout": 1,
      "txid": "67b078d4b19e90a078441bdf8191d1960126b45b3d66b07927b78200c008202e"
    },

Which causes claim_abandon to fail since it only takes a claim ID.  

The same scenario happens when you add support to your own claim. 

Additional claim_abandon support will be needed for tipping: https://github.com/lbryio/lbry-app/issues/355 

### Steps to reproduce
1. Add claim support to the same claim twice
2. Try to abandon claim
3. Fails - "more than one claim that matches"

### Expected behaviour
1) Abandon all claims with that claim id
or
2) Each support claim should have its own claimid
or
3) allow txid as part of args (optional), so you can abandon each

### Actual behaviour
cannot abandon

## System Configuration

 

- LBRY Daemon version: 0.14.2RC7
- LBRY App version: 0.13.0
- LBRY Installation ID:
- Operating system: Windows

**Comment by kaykurokawa** [comment]
This is actually expected behavior when abandoning by claim_id if there is more than one match. 

Lbryum has an option to abandon by txid/nout which allows you to specify exactly which claim you want to abandon. However, this option does no exist in lbrynet so needs to be put there. 

In addition, a more useful error message should be thrown when abandoning, such as "more than one claim that matches, specify exact claim to abandon by txid/nout"

**Comment by tzarebczan** [comment]
This also occurs if you Publish something yourself and add claim support. 

I think it's important for Tipping as well, since the plan was to use supports.

**Comment by tzarebczan** [comment]
Also, the claim which I supported is now gone, but I still should be able to abandon my claim. See info about the claim below:

2017-07-25 17:09:44,260 INFO     lbrynet.core.Wallet:822: Resolving lbry://three#b64155f2d44553871dfdb1785aa49d6d3972cd84
2017-07-25 17:09:44,793 ERROR    lbrynet.daemon.auth.server:353: Failed to process resolve: Certificate claim 512a347c4c7bd8251ac82ef061a94d3396a60e94 not found
Traceback (most recent call last):
  File "site-packages\twisted\internet\defer.py", line 1297, in _inlineCallbacks
  File "site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator
  File "site-packages\lbrynet\daemon\Daemon.py", line 1423, in jsonrpc_resolve
  File "site-packages\twisted\internet\defer.py", line 1297, in _inlineCallbacks
  File "site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator
  File "site-packages\lbrynet\core\Wallet.py", line 825, in resolve
  File "site-packages\twisted\python\threadpool.py", line 246, in inContext
  File "site-packages\twisted\python\threadpool.py", line 262, in <lambda>
  File "site-packages\twisted\python\context.py", line 118, in callWithContext
  File "site-packages\twisted\python\context.py", line 81, in callWithContext
  File "site-packages\lbryum\commands.py", line 140, in func_wrapper
  File "site-packages\lbryum\commands.py", line 1120, in getvaluesforuris
  File "site-packages\lbryum\commands.py", line 1002, in _handle_resolve_uri_response
  File "site-packages\lbryum\commands.py", line 738, in parse_and_validate_claim_result
Exception: Certificate claim 512a347c4c7bd8251ac82ef061a94d3396a60e94 not found

**Comment by okwme** [comment]
I had a claim with a support from myself.
I re-published the claim to lower the initial amount, but my support amount can't be changed or removed at this point?
Are my LBC completely locked up until this bug is fixed?

**Comment by kauffj** [comment]
There is likely a command line fix for this, please join our Slack for live help if this is urgent. But otherwise, yes.

Sorry :(

**Comment by okwme** [comment]
There's nothing listed in the documentation for CLI
Slack help/tech channel pointed me here : (

**Comment by tzarebczan** [comment]
@kaykurokawa are there any lbryum commands we could use? Without breaking the claim?

**Comment by okwme** [comment]
i'm happy to abandon the claim for what it's worth

**Comment by tzarebczan** [comment]
I'll let you know if we find a way around it.

**Comment by kaykurokawa** [comment]
https://github.com/lbryio/lbry/pull/829 should fix this problem
