### ISSUE TITLE
Auth error when opening and reclosing app

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry#860]
Trace:
```
2017-08-19 12:11:19,013 ERROR    lbrynet.daemon.auth.server:353: Failed to process resolve: 'NoneType' object has no attribute 'get_local_height'
Traceback (most recent call last):
  File "site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
  File "site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
  File "site-packages/lbrynet/daemon/Daemon.py", line 1433, in jsonrpc_resolve
  File "site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
  File "site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
  File "site-packages/lbrynet/core/Wallet.py", line 826, in resolve
  File "site-packages/twisted/python/threadpool.py", line 246, in inContext
  File "site-packages/twisted/python/threadpool.py", line 262, in <lambda>
  File "site-packages/twisted/python/context.py", line 118, in callWithContext
  File "site-packages/twisted/python/context.py", line 81, in callWithContext
  File "site-packages/lbryum/commands.py", line 141, in func_wrapper
  File "site-packages/lbryum/commands.py", line 1113, in getvaluesforuris
AttributeError: 'NoneType' object has no attribute 'get_local_height'
```

This will happen fairly reliably if I close the application and re-run it too quickly.

**Comment by alyssaoc** [comment]
@eukreign can you confirm this is fixed with new wallet implementation?

**Comment by hackrush01** [comment]
I think this is might be an authentication bug, I will post more details if I find something.

**Comment by eukreign** [comment]
Traceback is referencing the old lbryum based wallet, presumably this is no longer an issue in the new wallet, closing this as outdated.
