### ISSUE TITLE
Publishing right after channel creation results in publish failure

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#893]
## The Issue
Update: see https://github.com/lbryio/lbry/issues/893#issuecomment-367131981 for latest error when publishing to a newly created channel before its confirmed. 

Original issue:
If a user tries to publish something on a channel they just created, the Publishes screen hangs up and daemon throws a `Certificate claim d779aa006befe9a9eb12d6f8f7755b127d6e56bf not found`. The console also records a similar error in the API call. Could not get the claim to show in Publishes area until after Developer>Reload.  

The same error occurs when calling claim_list_mine right after creating the channel, see https://github.com/lbryio/lbry/issues/902

```
2017-09-08 11:16:24,785 INFO     lbrynet.core.Wallet:902: Preparing to make certificate claim for @jiggytomtest5
2017-09-08 11:16:25,276 ERROR    lbryum:115: [CoinChooserOldestFirst] change: [(1, 'bNGxZXBwvxna8dLt5MkxK2JBBNMrGK8pn5', 98982700)]

2017-09-08 11:16:25,276 ERROR    lbryum:115: [CoinChooserOldestFirst] using 1 inputs

2017-09-08 11:16:25,276 ERROR    lbryum:115: [CoinChooserOldestFirst] using buckets: [u'd7d6a17d8c14669f3dbfb43e78be9c5f353baa10a1739157fce700d3776a0611:0']

2017-09-08 11:16:25,467 ERROR    lbryum:115: adding signature for ff0488b21e000000000000000000cea7a2cd3087dde6100e682eb10d5d186e6ccfc20a75ce50db63e4b37c1658e90338c43761dd563be775666daa8d19596af43b6e72d95f1657d13ad02d88e4abc500001400

2017-09-08 11:16:25,927 ERROR    lbryum:115: is_complete True

2017-09-08 11:16:26,069 INFO     lbrynet.daemon.Daemon:1682: Claimed a new channel! Result: {'fee': '0.000173', 'success': True, 'tx': '010000000111066a77d300e7fc579173a110aa3b355f9cbe783eb4bf3d9f66148c7da1d6d7000000006a4730440220599be04de397aa2686ad51ad27a8f0a6a67baabcfa50b7d85d52e9396b7b3eaf0220719544c67ee9e95c3ce96deeadac160ec2696d3edc6d6d635b1373876e6dbc7f01210322096ddafe093d9061801529a35fb1cd9043a2ee985cccc02d76b3d5110a7b88ffffffff0240420f000000000091b50e406a69676779746f6d74657374354c6408011002225e0801100322583056301006072a8648ce3d020106052b8104000a03420004d8268602800fe231dd4bf20ebdef6f08108fb5984a2f52d667afcc9cfede4da90031cfb6492bdcb93da2bc2cc8a49f5fdab4c63be976afca8c754904db5d1b0c6d7576a914f2c2d2313cd0f456e3e31da9058eae7e696a3f6088ac2c5be605000000001976a91468b74e6524ab4436ea120e9d4b28dd836c4fb34088ac00000000', 'txid': 'f4d0ccfe5b08c049a7a1366cf38d3ed31cfc4dac814fcb3518c0dd0a1d1916c0', 'claim_id': 'd779aa006befe9a9eb12d6f8f7755b127d6e56bf', 'nout': 0}
2017-09-08 11:16:27,173 INFO     lbrynet.core.Wallet:823: Resolving lbry://@jiggytomtest5/modernie1024x768
2017-09-08 11:16:27,766 ERROR    lbryum.commands:1065: No valid claims for this name for this channel
2017-09-08 11:16:46,283 INFO     lbrynet.daemon.Daemon:1851: Publish: {'claim_address': None, 'name': u'modernie1024x768', 'bid': 0.01, 'claim_dict': {'version': '_0_0_1', 'claimType': 'streamType', 'stream': {'version': '_0_0_1', 'metadata': {u'language': u'en', u'license': u'', u'title': u'test 1', 'version': '_0_1_0', u'nsfw': False, u'licenseUrl': None}}}, 'file_path': u'C:\\BGinfo\\modern.IE.1024x768.jpg', 'change_address': None}
2017-09-08 11:16:46,286 INFO     lbrynet.daemon.Publisher:27: Starting publish for modernie1024x768
2017-09-08 11:16:46,526 INFO     lbrynet.lbry_file.EncryptedFileMetadataManager:246: Saved sd blob hash c1861ba2b12683026c8fdcb8b32608c59186b2e2a2471eca7d64b7ef6b496e5f0d921fa0bd10f0a9b365b98063037bcf to stream hash feb5d05e33e4549418a822e49d98960999e70bc3d6ebea1bdbb32767306ba13ac6895b2add2f15a9a88b7e77bc77a181
2017-09-08 11:16:46,676 INFO     lbrynet.core.Wallet:1368: Send claim: modernie1024x768 for 0.01: 080110011a620801121a080410011a0674657374203122002a00320038004a0052005a001a42080110011a30c1861ba2b12683026c8fdcb8b32608c59186b2e2a2471eca7d64b7ef6b496e5f0d921fa0bd10f0a9b365b98063037bcf220a696d6167652f6a706567 
2017-09-08 11:16:47,117 ERROR    lbryum:115: [CoinChooserOldestFirst] change: [(1, 'bEez4YM3hmWoiCy3Ugb9kKY2pTDDFt6GSE', 98977700)]

2017-09-08 11:16:47,117 ERROR    lbryum:115: [CoinChooserOldestFirst] using 1 inputs

2017-09-08 11:16:47,118 ERROR    lbryum:115: [CoinChooserOldestFirst] using buckets: [u'01a57e49882bd27638af4644d7a86029b236fce96bc0d6b97c838e7e04784e4f:1']

2017-09-08 11:16:47,315 ERROR    lbryum:115: adding signature for ff0488b21e000000000000000000cea7a2cd3087dde6100e682eb10d5d186e6ccfc20a75ce50db63e4b37c1658e90338c43761dd563be775666daa8d19596af43b6e72d95f1657d13ad02d88e4abc500003200

2017-09-08 11:16:47,816 ERROR    lbryum:115: is_complete True

2017-09-08 11:16:47,993 INFO     lbrynet.core.Wallet:949: Saving metadata for claim b4ad88fac07a24c07d6a207326ae82d901da5d5ffa15962fc228d66389701e1f 0
2017-09-08 11:16:48,030 INFO     lbrynet.daemon.Daemon:665: Success! Published to lbry://modernie1024x768 txid: b4ad88fac07a24c07d6a207326ae82d901da5d5ffa15962fc228d66389701e1f nout: 0
2017-09-08 11:16:48,174 INFO     lbrynet.reflector.client.client:134: Reflector needs descriptor and 1 blobs for lbry://modernie1024x768
2017-09-08 11:16:48,213 INFO     lbrynet.reflector.client.client:223: Sent reflector descriptor c1861ba2b1268302
2017-09-08 11:16:48,303 INFO     lbrynet.reflector.client.client:77: Reflector has all blobs for lbry://modernie1024x768 (c1861ba2b1268302)
2017-09-08 11:16:48,303 INFO     lbrynet.daemon.Daemon:661: Reflected new publication to lbry://modernie1024x768
2017-09-08 11:17:08,266 ERROR    lbrynet.daemon.auth.server:353: Failed to process claim_list_mine: Certificate claim d779aa006befe9a9eb12d6f8f7755b127d6e56bf not found
Traceback (most recent call last):
  File "site-packages\twisted\internet\defer.py", line 150, in maybeDeferred
  File "site-packages\lbrynet\daemon\Daemon.py", line 1974, in jsonrpc_claim_list_mine
  File "site-packages\lbrynet\core\Wallet.py", line 1360, in get_name_claims
  File "site-packages\lbrynet\core\Wallet.py", line 1288, in _run_cmd_as_defer_succeed
  File "site-packages\lbryum\commands.py", line 141, in func_wrapper
  File "site-packages\lbryum\commands.py", line 1304, in getnameclaims
  File "site-packages\lbryum\commands.py", line 739, in parse_and_validate_claim_result
Exception: Certificate claim d779aa006befe9a9eb12d6f8f7755b127d6e56bf not found

```
### Steps to reproduce
1. Create channel and then immeadiately publish something
2. Try to see published item, does not show. 

### Expected behaviour
Should be able to publish after creating channel or should be told to wait for confirmation? 

### Actual behaviour
To the typical user, it seems like something has failed. 

## System Configuration

 

- LBRY Daemon version: 0.15.2
- LBRY App version: 0.15.1
- LBRY Installation ID:
- Operating system:

**Comment by tzarebczan** [comment]
Jeremy noticed this also occurs right when you call claim_list_mine after creating the channel:
https://github.com/lbryio/lbry/issues/902

**Comment by lyoshenka** [comment]
possibly the same error as #1037

**Comment by tzarebczan** [comment]
Not sure exactly in which version this behavior changed, but now the result is a 500 api error on the publish call and the daemon returns the follow when you try to publish before the channel confirms:

```
2018-02-20 16:34:07,540 INFO     lbrynet.daemon.Daemon:1852: Claimed a new channel! Result: {'claim_address': 'bUyFYKCUmvzJCnqvP6xxh97kQRimrANNeK', 'value': '08011002225e0801100322583056301006072a8648ce3d020106052b8104000a03420004bc03536171fb1262c506e5cc6fe1006dc21660c9038ca7935b3eee5f138af58485dcf69ab04435598d702a34ce723eea7e0f1ed106724b298d91a5d1b6beced4', 'fee': '0.000174', 'tx': '01000000016085938a64fbf2690c6fa4d1b738c83d8884a40e0d5914f6c0fdcdacc64fe153000000006b483045022100d8e1f5f4ffa408fda8212d67e1ecab6138eaf4b556fded5718ee6bbe95ece66402203f2583391c499bd57a2f66836b992b9f0fd248cfe4b7dcaf6c8b806a07325311012102fb98109262a5c79d697b5b29e4c271dc4d081f4323c64ba4d72ddd30ad4e0056ffffffff0240420f000000000093b51040717569636b7075626368616e6e656c4c6408011002225e0801100322583056301006072a8648ce3d020106052b8104000a03420004bc03536171fb1262c506e5cc6fe1006dc21660c9038ca7935b3eee5f138af58485dcf69ab04435598d702a34ce723eea7e0f1ed106724b298d91a5d1b6beced46d7576a914b226df77da9726b028070c2825f420ed24298d0188acc83bdc0b000000001976a9145a90a86f9390ae7c35ec4a547c925e049fe273ae88ac00000000', 'success': True, 'claim_id': '4d4b487878ca2c745d2ee1746e0765c665074e4f', 'nout': 0, 'txid': 'e47a94a40831c8e9fdbd0c5f6c77c54731688428e653f05c2becea53dfda85e8'}
2018-02-20 16:34:32,618 INFO     lbrynet.daemon.Daemon:2096: Publish: {'claim_address': None, 'channel_id': None, 'name': u'touchme', 'claim_dict': {'version': '_0_0_1', 'claimType': 'streamType', 'stream': {'version': '_0_0_1', 'metadata': {u'description': u'create channel + quick pub', u'license': u'None', u'title': u'quick pub test', u'language': u'en', 'version': '_0_1_0', u'nsfw': False, u'licenseUrl': None}}}, 'channel_name': u'@quickpubchannel', 'bid': 0.01, 'file_path': u'C:\\Users\\SoloDolo\\Pictures\\touchme.JPG', 'change_address': None}
2018-02-20 16:34:35,233 WARNING  lbrynet.daemon.auth.server:228: error processing api request: Cannot publish using channel @quickpubchannel
traceback:   File "site-packages\twisted\internet\defer.py", line 1299, in _inlineCallbacks
    
  File "site-packages\lbrynet\daemon\Daemon.py", line 2109, in jsonrpc_publish
    
exceptions.Exception: Cannot publish using channel @quickpubchannel
2018-02-20 16:35:29,707 WARNING  lbrynet.daemon.auth.server:445: API function "channel_list_mine" is deprecated, please update to use "channel_list"
2018-02-20 16:35:49,144 INFO     lbrynet.daemon.Daemon:2096: Publish: {'claim_address': None, 'channel_id': None, 'name': u'touchme', 'claim_dict': {'version': '_0_0_1', 'claimType': 'streamType', 'stream': {'version': '_0_0_1', 'metadata': {u'description': u'2nd try', u'license': u'None', u'title': u'test pub after quickchan', u'language': u'en', 'version': '_0_1_0', u'nsfw': False, u'licenseUrl': None}}}, 'channel_name': u'@quickpubchannel', 'bid': 0.01, 'file_path': u'C:\\Users\\SoloDolo\\Pictures\\touchme.JPG', 'change_address': None}
2018-02-20 16:35:51,805 WARNING  lbrynet.daemon.auth.server:228: error processing api request: Cannot publish using channel @quickpubchannel
traceback:   File "site-packages\twisted\internet\defer.py", line 1299, in _inlineCallbacks
    
  File "site-packages\lbrynet\daemon\Daemon.py", line 2109, in jsonrpc_publish
    
exceptions.Exception: Cannot publish using channel @quickpubchannel
2018-02-20 16:37:15,930 WARNING  lbrynet.daemon.auth.server:445: API function "channel_list_mine" is deprecated, please update to use "channel_list"
2018-02-20 16:37:53,500 INFO     lbrynet.daemon.Daemon:2096: Publish: {'claim_address': None, 'channel_id': None, 'name': u'touchme', 'claim_dict': {'version': '_0_0_1', 'claimType': 'streamType', 'stream': {'version': '_0_0_1', 'metadata': {u'description': u'third try', u'license': u'None', u'title': u'try 3 quick pub', u'language': u'en', 'version': '_0_1_0', u'nsfw': False, u'licenseUrl': None}}}, 'channel_name': u'@quickpubchannel', 'bid': 0.01, 'file_path': u'C:\\Users\\SoloDolo\\Pictures\\touchme.JPG', 'change_address': None}
2018-02-20 16:37:55,967 WARNING  lbrynet.daemon.auth.server:228: error processing api request: Cannot publish using channel @quickpubchannel
traceback:   File "site-packages\twisted\internet\defer.py", line 1299, in _inlineCallbacks
    
  File "site-packages\lbrynet\daemon\Daemon.py", line 2109, in jsonrpc_publish
    
exceptions.Exception: Cannot publish using channel @quickpubchannel

```
API return:
```
{
  "error": {
    "code": -32500,
    "data": {
      "traceback": [
        "Traceback (most recent call last):",
        "  File \"site-packages\\lbrynet\\daemon\\auth\\server.py\", line 240, in render",
        "    ",
        "  File \"site-packages\\lbrynet\\daemon\\auth\\server.py\", line 355, in _render",
        "    ",
        "  File \"site-packages\\twisted\\internet\\defer.py\", line 150, in maybeDeferred",
        "    ",
        "  File \"site-packages\\twisted\\internet\\defer.py\", line 1445, in unwindGenerator",
        "    ",
        "--- <exception caught here> ---",
        "  File \"site-packages\\twisted\\internet\\defer.py\", line 1299, in _inlineCallbacks",
        "    ",
        "  File \"site-packages\\lbrynet\\daemon\\Daemon.py\", line 1920, in jsonrpc_publish",
        "    ",
        "exceptions.Exception: Cannot publish using channel @quickchan01",
        ""
      ]
    },
    "message": "Cannot publish using channel @quickchan01"
  },
  "id": 1450,
  "jsonrpc": "2.0"
}
```

**Comment by lyoshenka** [comment]
For the record, you can work around this by publishing the channel claim, then using `--channel_id` param when publishing content claims into the channel. Spee.ch is already doing this. The app should start doing it (@seanyesmunt).

The real solution for this will be to fix tx malleability.

**Comment by tzarebczan** [comment]
Closing this in favor of: https://github.com/lbryio/lbry/issues/1188

The app now uses channel id, but the protocol should do a better job of not allowing this to begin with or giving the user a better error message.
