### ISSUE TITLE
API call to blob_list with --uri paramater fails

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#895]
## The Issue
When calling `blob_list` with `--uri=claimname` you get an ERROR: 'stream' response. See full stack below:

```
Here's the traceback for the error you encountered:
Traceback (most recent call last):
  File "site-packages\twisted\internet\defer.py", line 457, in callback

  File "site-packages\twisted\internet\defer.py", line 565, in _startRunCallbacks

  File "site-packages\twisted\internet\defer.py", line 651, in _runCallbacks

  File "site-packages\twisted\internet\defer.py", line 1355, in gotResult

--- <exception caught here> ---
  File "site-packages\twisted\internet\defer.py", line 1299, in _inlineCallbacks

  File "site-packages\lbrynet\daemon\Daemon.py", line 2536, in jsonrpc_blob_list

  File "site-packages\lbrynet\core\utils.py", line 125, in get_sd_hash

exceptions.KeyError: 'stream'

```
### Steps to reproduce
1. call `./lbrynet-cli blob_list --uri=one`

### Expected behavior
Should return a list of blobs

### Actual behavior
Error

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by KamilPiekutowski** [comment]
self.get_blobs_for_stream_hash does not get executed
although it is assigned to a callback here:
        d.addCallback(self.get_blobs_for_stream_hash)

**Comment by lyoshenka** [comment]
fixed by https://github.com/lbryio/lbry/pull/1100

**Comment by tzarebczan** [comment]
Reopening- https://github.com/lbryio/lbry/pull/1100#issuecomment-367078951

**Comment by jackrobison** [comment]
fixed in https://github.com/lbryio/lbry/pull/1126
