### ISSUE TITLE
claim_list_mine fails immediately after a publish on a new channel

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry#902]
## The Issue

Calling `claim_list_mine` immediately after a new publish to a new channel results in an error.

I'm not sure if this happens 100% of the time.

### Steps to reproduce
1. Make a new channel and new publish on that channel.
2. Call `claim_list_mine.
3.

### Expected behaviour
Standard response.

### Actual behaviour
Received error with following trace:
```
2017-09-18 17:30:17,760 ERROR    lbrynet.daemon.auth.server:353: Failed to process claim_list_mine: Certificate claim 7efd2cd4b7bf4f0f57777881f22d88bb4fec2eef not found
Traceback (most recent call last):
  File "site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
  File "site-packages/lbrynet/daemon/Daemon.py", line 1976, in jsonrpc_claim_list_mine
  File "site-packages/lbrynet/core/Wallet.py", line 1360, in get_name_claims
  File "site-packages/lbrynet/core/Wallet.py", line 1288, in _run_cmd_as_defer_succeed
  File "site-packages/lbryum/commands.py", line 91, in func_wrapper
  File "site-packages/lbryum/commands.py", line 1333, in getnameclaims
  File "site-packages/lbryum/commands.py", line 769, in parse_and_validate_claim_result
Exception: Certificate claim 7efd2cd4b7bf4f0f57777881f22d88bb4fec2eef not found
```

## System Configuration

- LBRY Daemon version: 0.16.0
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tzarebczan** [comment]
Have the same error logged here: https://github.com/lbryio/lbry/issues/893 - pretty sure its because the block with the certificate claim hasn't been mined yet. This could possibly be fixed by the certificate caching @jackrobison mentioned on the call today.

**Comment by kauffj** [comment]
Yes, this goes away once a block is confirmed, but it's a clear bug that this errors in the interim.

**Comment by kauffj** [comment]
Feel free to consolidate tickets.

**Comment by tzarebczan** [comment]
Will close this one and track under 893.
