### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_balance'

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry#907]
daemon version v0.16.0

Cloudflare DNS was struggling this morning, so this could be related.

```
niko@youtube-sync-srv19:~/lbry$ ./lbrynet-daemon 
2017-09-20 13:25:08,235 INFO     lbrynet.daemon.DaemonControl:70: Starting lbrynet-daemon from command line
2017-09-20 13:25:08,685 INFO     lbrynet.daemon.DaemonServer:66: Using non-authenticated API
2017-09-20 13:25:08,688 INFO     lbrynet.daemon.Daemon:244: Starting lbrynet-daemon
2017-09-20 13:25:08,689 INFO     lbrynet.daemon.ExchangeRateManager:170: Starting exchange rate manager
2017-09-20 13:25:09,089 INFO     lbrynet.daemon.Daemon:270: Platform: {"lbrynet_version": "0.16.0", "platform": "Linux-4.4.0-81-generic-x86_64-with-Ubuntu-16.04-xenial", "os_system": "Linux", "python_version": "2.7.12", "os_release": "4.4.0-81-generic", "lbryum_version": "3.1.7", "ip": "52.3.250.150", "lbryschema_version": "0.0.11", "processor": "x86_64", "build": "release"}
2017-09-20 13:25:09,091 INFO     lbrynet.daemon.Daemon:471: Loading databases
2017-09-20 13:25:09,094 INFO     lbrynet.daemon.Daemon:537: Using lbryum wallet
2017-09-20 13:25:13,102 INFO     lbrynet.core.Session:254: Starting DHT
2017-09-20 13:25:13,109 INFO     lbrynet.dht.protocol:216: DHT listening on UDP 4444
2017-09-20 13:25:13,111 INFO     lbrynet.core.RateLimiter:72: Starting rate limiter.
2017-09-20 13:25:13,112 INFO     lbrynet.core.BlobManager:42: Starting disk blob manager. blob_dir: /home/niko/.lbrynet/blobfiles, db_file: /home/niko/.lbrynet/blobs.db
2017-09-20 13:25:13,112 INFO     lbrynet.core.Wallet:451: Starting wallet.
2017-09-20 13:25:13,120 ERROR    lbrynet.daemon.DaemonControl:100: Failed to start lbrynet-daemon
Traceback (most recent call last):
  File "site-packages/lbrynet/daemon/DaemonControl.py", line 97, in start_server_and_listen
FirstError: FirstError[#1, [Failure instance: Traceback: <class 'socket.gaierror'>: [Errno -2] Name or service not known
site-packages/twisted/internet/base.py:1208:mainLoop
site-packages/twisted/internet/base.py:801:runUntilCurrent
site-packages/twisted/internet/defer.py:457:callback
site-packages/twisted/internet/defer.py:565:_startRunCallbacks
--- <exception caught here> ---
site-packages/twisted/internet/defer.py:651:_runCallbacks
site-packages/lbrynet/core/Wallet.py:458:<lambda>
site-packages/lbrynet/core/Wallet.py:1188:_start
site-packages/lbrynet/core/Wallet.py:1169:setup_network
site-packages/lbryum/network.py:202:__init__
site-packages/lbryum/network.py:313:_set_online_servers
site-packages/lbryum/network.py:314:<dictcomp>
site-packages/lbryum/network.py:26:is_online
]]
2017-09-20 13:25:13,123 INFO     lbrynet.daemon.DaemonServer:57: Stopping the reactor
2017-09-20 13:25:13,123 INFO     lbrynet.daemon.Daemon:400: Closing lbrynet session
2017-09-20 13:25:13,124 INFO     lbrynet.daemon.Daemon:401: Status at time of shutdown: loading_wallet
2017-09-20 13:25:13,124 INFO     lbrynet.core.Session:172: Stopping session.
2017-09-20 13:25:13,125 INFO     lbrynet.core.BlobAvailability:35: Stopping blob availability tracker.
2017-09-20 13:25:13,125 INFO     lbrynet.core.RateLimiter:83: Stopping rate limiter.
2017-09-20 13:25:13,125 INFO     lbrynet.core.client.DHTPeerFinder:28: Stopping DHT peer finder.
2017-09-20 13:25:13,125 INFO     lbrynet.core.server.DHTHashAnnouncer:31: Stopping DHT hash announcer.
2017-09-20 13:25:13,125 INFO     lbrynet.core.Wallet:476: Stopping wallet.
2017-09-20 13:25:13,126 ERROR    lbrynet.core.Wallet:542: Something went wrong during manage. Error message: 'NoneType' object has no attribute 'get_balance'
2017-09-20 13:25:13,127 ERROR    lbrynet.core.Wallet:473: An error occurred stopping the wallet: Traceback (most recent call last):
  File "site-packages/twisted/internet/defer.py", line 308, in addCallbacks
    
  File "site-packages/twisted/internet/defer.py", line 651, in _runCallbacks
    
  File "site-packages/lbrynet/core/Wallet.py", line 529, in <lambda>
    
  File "site-packages/twisted/internet/defer.py", line 1445, in unwindGenerator
    
--- <exception caught here> ---
  File "site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    
  File "site-packages/lbrynet/core/Wallet.py", line 559, in update_balance
    
  File "site-packages/lbrynet/core/Wallet.py", line 1303, in _update_balance
    
  File "site-packages/lbrynet/core/Wallet.py", line 1288, in _run_cmd_as_defer_succeed
    
  File "site-packages/lbryum/commands.py", line 91, in func_wrapper
    
  File "site-packages/lbryum/commands.py", line 309, in getbalance
    
exceptions.AttributeError: 'NoneType' object has no attribute 'get_balance'

2017-09-20 13:25:13,129 ERROR    lbrynet.core.Wallet:473: An error occurred stopping the wallet: Traceback (most recent call last):
  File "site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    
  File "site-packages/lbrynet/core/Wallet.py", line 486, in stop
    
  File "site-packages/twisted/internet/defer.py", line 319, in addCallback
    
  File "site-packages/twisted/internet/defer.py", line 308, in addCallbacks
    
--- <exception caught here> ---
  File "site-packages/twisted/internet/defer.py", line 651, in _runCallbacks
    
  File "site-packages/lbrynet/core/Wallet.py", line 486, in <lambda>
    
  File "site-packages/lbrynet/core/Wallet.py", line 1201, in _stop
    
  File "site-packages/twisted/internet/task.py", line 202, in stop
    
exceptions.AssertionError: Tried to stop a LoopingCall that was not running.

2017-09-20 13:25:13,131 INFO     lbrynet.core.BlobManager:46: Stopping disk blob manager.
2017-09-20 13:25:13,140 INFO     lbrynet.core.Session:323: Unsetting upnp for session
2017-09-20 13:25:13,140 INFO     lbrynet.dht.protocol:468: Stopping DHT
2017-09-20 13:25:13,140 INFO     lbrynet.dht.protocol:484: DHT stopped

```

**Comment by jackrobison** [comment]
Yes, this was the same issue as https://github.com/lbryio/lbry/issues/908

**Comment by lyoshenka** [comment]
Looks like the same error as the latest comment in #626

**Comment by alyssaoc** [comment]
@eukreign Can you confirm this is still an issue? Will the new wallet fix it?

**Comment by eukreign** [comment]
I think this is fixed by the components.
