### ISSUE TITLE
Crash at start in Windows 10

### ISSUE THREAD

**Issue by temandroid** [lbryio/lbry#911]
## The Issue
Can't start LBRY after first install/reinstall

### Steps to reproduce
1. Run LBRY
2. Daemon crashed...
3.

### Expected behaviour
On another PC working perfectly

### Actual behaviour
`C:\Program Files (x86)\LBRY\resources\app\dist>lbrynet-daemon.exe
Traceback (most recent call last):
  File "site-packages\PyInstaller\loader\rthooks\pyi_rth_twisted.py", line 23, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\twisted\internet\default.py", line 56, in <module>
  File "site-packages\twisted\internet\default.py", line 50, in _getInstallFunction
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\twisted\internet\selectreactor.py", line 18, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\twisted\internet\posixbase.py", line 18, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\twisted\internet\tcp.py", line 28, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\twisted\internet\_newtls.py", line 21, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\twisted\protocols\tls.py", line 41, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\OpenSSL\__init__.py", line 8, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\OpenSSL\crypto.py", line 12, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\cryptography\x509\__init__.py", line 9, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\cryptography\x509\base.py", line 16, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\cryptography\x509\extensions.py", line 13, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\asn1crypto\keys.py", line 22, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\asn1crypto\_elliptic_curve.py", line 51, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\asn1crypto\_int.py", line 56, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\asn1crypto\_perf\_big_num_ctypes.py", line 31, in <module>
  File "ctypes\util.py", line 53, in find_library
  File "ntpath.py", line 85, in join
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd2 in position 7: ordinal not in range(128)
Failed to execute script pyi_rth_twisted`

## System Configuration

 

- LBRY Daemon version: 
- LBRY App version: 0.15.0, 0.15.1
- LBRY Installation ID:
- Operating system: Win10 1703 15063.608

**Comment by tzarebczan** [comment]
We mention this issue on: https://lbry.io/faq/startup-troubleshooting

And have it logged here: https://github.com/lbryio/lbry/issues/794

We don't have a workaround for the scenario your case at this time. Can you tell me what your users directory is in c:\users\xxxx? 

The only recommendation we can make is to create a separate Windows user without any special characters.

**Comment by temandroid** [comment]
User folder in with cyryllic symbols, i think this is why i han an error... thank u
