### ISSUE TITLE
Failed to process transaction_list

### ISSUE THREAD

**Issue by mirgee** [lbryio/lbry#916]
## The Issue
Calling transaction_list or clicking on wallet ballance in the app results in the following error:

2017-09-22 15:13:36,791 ERROR    lbrynet.daemon.auth.server:398: Failed to process transaction_list: 'tiphistory'
Traceback (most recent call last):
  File "/home/miroslav/Source/lbry/lbry-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/miroslav/Source/lbry/lbrynet/daemon/Daemon.py", line 2142, in jsonrpc_transaction_list
    d = self.session.wallet.get_history(include_tip_info)
  File "/home/miroslav/Source/lbry/lbrynet/core/Wallet.py", line 995, in get_history
    d = self._get_history(include_tip_info)
  File "/home/miroslav/Source/lbry/lbrynet/core/Wallet.py", line 1461, in _get_history
    return self._run_cmd_as_defer_succeed('tiphistory')
  File "/home/miroslav/Source/lbry/lbrynet/core/Wallet.py", line 1286, in _run_cmd_as_defer_succeed
    cmd = known_commands[command_name]
KeyError: 'tiphistory'

The same with claimhistory.

### Steps to reproduce
1. Call transaction_list

### Expected behaviour
Method returns list transactions belonging to wallet

### Actual behaviour
Abovementioned error is thrown

## System Configuration
{
  "build": "dev",
  "lbrynet_version": "0.16.1-2-g875d512",
  "lbryschema_version": "0.0.11rc1",
  "lbryum_version": "3.1.7rc5",
  "os_release": "4.10.0-35-generic",
  "os_system": "Linux",
  "platform": "Linux-4.10.0-35-generic-x86_64-with-Ubuntu-16.04-xenial",
  "processor": "x86_64",
  "python_version": "2.7.12"
}

## Screenshots

![screenshot from 2017-09-22 15-32-53](https://user-images.githubusercontent.com/11699479/30746800-55f12870-9fab-11e7-84d8-d607d56fed7f.png)

**Comment by tzarebczan** [comment]
Is this happening in the v16 release or just on the source?

**Comment by mirgee** [comment]
@tzarebczan This does not happen on v16 release.
