### ISSUE TITLE
ValueError: There is already a blob download request active

### ISSUE THREAD

**Issue by jackrobison** [lbryio/lbry#950]
With 0.17.0

```
2017-10-12 13:52:54,172 INFO     lbrynet.core.client.ClientProtocol:185: Closing the connection to x.x.x.x:3333 because the download of blob a5d1ebd863d2b5f7 was canceled
2017-10-12 13:52:54,174 ERROR    lbrynet.core.client.ClientProtocol:130: An unexpected error occurred creating or sending a request to x.x.x.x:3333. Error message: Traceback (most recent call last):
  File "site-packages/twisted/internet/defer.py", line 651, in _runCallbacks
  File "site-packages/lbrynet/core/client/ClientProtocol.py", line 235, in get_next_request
  File "site-packages/lbrynet/core/client/ClientProtocol.py", line 147, in _ask_for_request
  File "site-packages/twisted/internet/defer.py", line 1445, in unwindGenerator
--- <exception caught here> ---
  File "site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
  File "site-packages/lbrynet/core/client/ConnectionManager.py", line 111, in get_next_request
  File "site-packages/lbrynet/core/client/ConnectionManager.py", line 137, in _send_primary_requests
  File "site-packages/lbrynet/core/client/BlobRequester.py", line 66, in send_next_request
  File "site-packages/lbrynet/core/client/BlobRequester.py", line 113, in _send_next_request
  File "site-packages/lbrynet/core/client/BlobRequester.py", line 440, in make_request_and_handle_response
  File "site-packages/lbrynet/core/client/BlobRequester.py", line 493, in _handle_download_request
  File "site-packages/lbrynet/core/client/BlobRequester.py", line 540, in create_add_blob_request
  File "site-packages/lbrynet/core/client/ClientProtocol.py", line 108, in add_blob_request
exceptions.ValueError: There is already a blob download request active
```

**Comment by jackrobison** [comment]
It appears there is a related uncaught exception:

```
2017-10-12 13:52:55,726 CRITICAL twisted:154: Unhandled error in Deferred:
2017-10-12 13:52:55,727 CRITICAL twisted:154: 
DownloadCanceledError
```
