### ISSUE TITLE
"Invalid or missing token" dht related error

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#955]
## The Issue
Not sure why its happening but I've seen this on my logs and on srv25. Looks like its only happening to a single IP - 45.32.149.146. It does happen repeatedly in my logs and at different intervals.

```
2017-10-14 17:13:56,619 WARNING  lbrynet.core.server.ServerProtocol:47: Closing a connection. Reason: Connection to the other side was lost in a non-clean fashion.
2017-10-14 18:36:14,480 INFO     lbrynet.core.server.BlobRequestHandler:151: Sending dce7025c49ea0433 to 92.62.199.202:56859
2017-10-14 18:36:16,733 INFO     lbrynet.core.server.BlobRequestHandler:151: Sending b45843c920c7b950 to 92.62.199.202:43125
2017-10-14 18:36:25,395 INFO     lbrynet.core.server.BlobRequestHandler:151: Sending ef50ada028967f70 to 92.62.199.202:43125
2017-10-14 18:38:52,471 ERROR    lbrynet.dht.protocol:391: error handling request for 45.32.149.146: store
Traceback (most recent call last):
  File "site-packages\lbrynet\dht\protocol.py", line 387, in _handleRPC
  File "site-packages\lbrynet\dht\node.py", line 475, in store
ValueError: Invalid or missing token
2017-10-14 18:48:01,617 INFO     lbrynet.core.server.BlobRequestHandler:151: Sending 34c64a690e5f2e64 to 192.161.109.76:56920
```

srv25:
```
2017-10-14 19:49:27,951 INFO     lbrynet.core.server.BlobRequestHandler:151: Sending 3d78c437be52e702 to 104.238.169.122:54130
2017-10-14 19:49:28,619 INFO     lbrynet.core.server.BlobRequestHandler:151: Sending 4658e950c8945788 to 104.238.169.122:54130
2017-10-14 22:38:50,350 ERROR    lbrynet.dht.protocol:391: error handling request for 45.32.149.146: store
Traceback (most recent call last):
  File "site-packages/lbrynet/dht/protocol.py", line 387, in _handleRPC
  File "site-packages/lbrynet/dht/node.py", line 475, in store
ValueError: Invalid or missing token
2017-10-15 07:02:40,159 ERROR    lbrynet.dht.protocol:391: error handling request for 45.32.149.146: store
Traceback (most recent call last):
  File "site-packages/lbrynet/dht/protocol.py", line 387, in _handleRPC
  File "site-packages/lbrynet/dht/node.py", line 475, in store
ValueError: Invalid or missing token
2017-10-15 07:02:42,413 ERROR    lbrynet.dht.protocol:391: error handling request for 45.32.149.146: store
Traceback (most recent call last):
  File "site-packages/lbrynet/dht/protocol.py", line 387, in _handleRPC
  File "site-packages/lbrynet/dht/node.py", line 475, in store
ValueError: Invalid or missing token
2017-10-15 18:44:51,727 WARNING  lbrynet.core.server.ServerProtocol:47: Closing a connection. Reason: Connection to the other side was lost in a non-clean fashion.
2017-10-15 18:56:15,903 INFO     lbrynet.core.server.BlobRequestHandler:151: Sending 729589475e97fd29 to 71.84.87.143:55146
2017-10-16 05:15:18,829 INFO     lbrynet.core.server.BlobRequestHandler:151: Sending 236502c239d62779 to 182.77.106.97:50069

```

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by lyoshenka** [comment]
@jackrobison says this is probably related to old clients (from before we fixed the lbry id issue)
