### ISSUE TITLE
DHT error : Failed to contact

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#967]
## The Issue
Discussed this with @jackrobison, he said he would look at it this morning and is aware of the issue.

```
017-10-20 13:32:25,980 ERROR    lbrynet.dht.node:830: Failed to contact <lbrynet.dht.contact.Contact object; IP address: 73.4.5.86, UDP port: 4444>
Traceback (most recent call last):
  File "site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
  File "site-packages\lbrynet\dht\node.py", line 757, in removeFromShortlist
  File "site-packages\twisted\python\failure.py", line 344, in trap
Failure: [Failure instance: Traceback: <type 'exceptions.TypeError'>: string indices must be integers, not str
site-packages\twisted\internet\udp.py:249:doRead
site-packages\lbrynet\dht\protocol.py:248:datagramReceived
site-packages\twisted\internet\defer.py:457:callback
site-packages\twisted\internet\defer.py:565:_startRunCallbacks
--- <exception caught here> ---
site-packages\twisted\internet\defer.py:651:_runCallbacks
site-packages\lbrynet\dht\node.py:712:extendShortlist
site-packages\lbrynet\dht\node.py:726:_keepSearching
site-packages\lbrynet\dht\node.py:732:_getContactTriples
```

## System Configuration

 

- LBRY Daemon version: 0.17.0RC1
- LBRY App version: 0.17.0
- LBRY Installation ID:
- Operating system: Windows

**Comment by jackrobison** [comment]
fixed in https://github.com/lbryio/lbry/commit/0b771c16ba058d3919b2bac482f4d725473a72fa
