### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'Could not determine IP'

### ISSUE THREAD

**Issue by stevenmos** [lbryio/lbry#985]
## The Issue
On attempting to download a file via the command line, I get the following error:

     Unhandled error in Deferred:
     2017-11-03 21:57:30,435 CRITICAL twisted:154: Unhandled error in Deferred:
     
     2017-11-03 21:57:30,435 CRITICAL twisted:154: 
     Traceback (most recent call last):
       File "site-packages/twisted/internet/defer.py", line 651, in _runCallbacks
       File "site-packages/lbrynet/dht/node.py", line 281, in requestPeers
       File "site-packages/lbrynet/dht/node.py", line 466, in store
       File "site-packages/lbrynet/dht/contact.py", line 33, in compact_ip
       File "site-packages/lbrynet/dht/contact.py", line 33, in <lambda>
     ValueError: invalid literal for int() with base 10: 'Could not determine IP'

### Steps to reproduce
1. Start the daemon
2. Attempt to download a file
3.

### Expected behaviour
Tell us what should happen:
Either: detect the ip correctly, or fail gracefully

### Actual behaviour
Tell us what happens instead:
Neither of the above, and download apparently failed

## System Configuration

 

- LBRY Daemon version:
lbrynet-cli 0.17.1
lbrynet-daemon 0.17.1
- LBRY App version:
N/A 
- LBRY Installation ID:
- Operating system: Solus 3

**Comment by tzarebczan** [comment]
Thanks for logging this @stevenmos! I did mention this to the devs last week and they weren't sure why it was happening. I'm guessing its something to do with the OS you are running or do you have IPV6 possibly?

Please check out https://lbry.io/faq/tips

**Comment by stevenmos** [comment]
Thank you.  I disable IPv6 to increase the security of the VPN I use.  I did, briefly, try lbry without it but there was no difference.

**Comment by alyssaoc** [comment]
@tzarebczan can you check loggly for this?

**Comment by tzarebczan** [comment]
hey @stevenmos , can you check if this is still happening on the latest version of LBRY for you (https://lbry.io/get)

I see similar errors on Loggly, but more related to the DHT side - 
```DHT RECV REMOTE EXCEPTION FROM 19x.21x.5x.5x:46492: invalid literal for int() with base 10: ''```
or 
```Unexpected response: invalid literal for int() with base 10: ''```

Any idea what that could be @jackrobison / @shyba ?

**Comment by shyba** [comment]
Not immediately from me, but I will reply if I stumble on that error or if I see something on the code. For now it looks like it got moved/rewritten. Maybe @jackrobison will have a better idea if something got fixed in there between 0.17 and 0.21

**Comment by jackrobison** [comment]
These are two different (although related) bugs

The first one was when the ip was incorrectly set to the string `Could not determine IP` and then this was used to try to announce blobs (the nodes receiving these requests then fail to decode the datagram). This one should be fixed.

The second bug is when a field that is not supposed to be blank is blank - `''`. I'm not sure where that's coming from. @shyba ran into it recently (is it this the same node as the one sending you those error responses?) Maybe it's a single old node with a bug that's now fixed everywhere else.

**Comment by tzarebczan** [comment]
Yes, that's the same node producing both messages. It's someone on Win 7 and the latest version. Found another user in a similar boat on Linux (no email) and a 3rd also on Win 7. Reached out to 2 of the Win 7 users.
